Map<String,bool> Imagemap_gunpo = {
  "assets/dogam_assets/Gyeonggi/군포/경기도_군포시_군포 동래정씨 동래군파 종택.jpg":false,
  "assets/dogam_assets/Gyeonggi/군포/경기도_군포시_나무재 집.jpg":false,
  "assets/dogam_assets/Gyeonggi/군포/경기도_군포시_누리천문대.jpg":false,
  "assets/dogam_assets/Gyeonggi/군포/경기도_군포시_능안공원.jpg":false,
  "assets/dogam_assets/Gyeonggi/군포/경기도_군포시_당정근린공원.jpg":false,
  "assets/dogam_assets/Gyeonggi/군포/경기도_군포시_반월호수공원.jpg":false,
  "assets/dogam_assets/Gyeonggi/군포/경기도_군포시_산본역광장분수대.jpg":false,
  "assets/dogam_assets/Gyeonggi/군포/경기도_군포시_산본중앙공원.jpg":false,
  "assets/dogam_assets/Gyeonggi/군포/경기도_군포시_수리사.jpg":false,
  "assets/dogam_assets/Gyeonggi/군포/경기도_군포시_수리산 관모봉.jpg":false,
  "assets/dogam_assets/Gyeonggi/군포/경기도_군포시_수리산 태을봉.jpg":false,
  "assets/dogam_assets/Gyeonggi/군포/경기도_군포시_철쭉공원.jpg":false,
  "assets/dogam_assets/Gyeonggi/군포/경기도_군포시_초막골생태공원.jpg":false,
  "assets/dogam_assets/Gyeonggi/군포/경기도_군포시_파고다관광.jpg":false,
};


List <String> url_gunpo_List=[
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "", 
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
];