Map<String,bool> Imagemap_gunpo = {
  "assets/dogam_assets/Gyeonggi/군포/경기도_군포시_수리사.jpg":false,
  "assets/dogam_assets/Gyeonggi/군포/경기도_군포시_반월호수공원.jpg":false,
  "assets/dogam_assets/Gyeonggi/군포/경기도_군포시_당정근린공원.jpg":false,
  "assets/dogam_assets/Gyeonggi/군포/경기도_군포시_능안공원.jpg":false,
  "assets/dogam_assets/Gyeonggi/군포/경기도_군포시_철쭉공원.jpg":false,
  "assets/dogam_assets/Gyeonggi/군포/경기도_군포시_누리천문대.jpg":false,
};


List <String> url_gunpo_List=[
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "", 
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
];