Map<String,bool> Imagemap_yeongdong = {
  "assets/dogam_assets/Chungbuk/영동/충청북도_영동군_강선대.jpg":false,
  "assets/dogam_assets/Chungbuk/영동/충청북도_영동군_난계국악박물관.jpg":false,
  "assets/dogam_assets/Chungbuk/영동/충청북도_영동군_노근리평화공원.jpg":false,
  "assets/dogam_assets/Chungbuk/영동/충청북도_영동군_물한계곡.jpg":false,
  "assets/dogam_assets/Chungbuk/영동/충청북도_영동군_민주지산자연휴양림.jpg":false,
  "assets/dogam_assets/Chungbuk/영동/충청북도_영동군_송호국민관광지.jpg":false,
  "assets/dogam_assets/Chungbuk/영동/충청북도_영동군_양산팔경 금강둘레길.jpg":false,
  "assets/dogam_assets/Chungbuk/영동/충청북도_영동군_영동 난계사.jpg":false,
  "assets/dogam_assets/Chungbuk/영동/충청북도_영동군_영동 포도터널.jpg":false,
  "assets/dogam_assets/Chungbuk/영동/충청북도_영동군_영동 한천정사.jpg":false,
  "assets/dogam_assets/Chungbuk/영동/충청북도_영동군_영동영국사석종형부도.jpg":false,
  "assets/dogam_assets/Chungbuk/영동/충청북도_영동군_영동와인터널.jpg":false,
  "assets/dogam_assets/Chungbuk/영동/충청북도_영동군_옥계폭포.jpg":false,
  "assets/dogam_assets/Chungbuk/영동/충청북도_영동군_용두정.jpg":false,
};


List <String> url_yeongdong_List=[
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
];