Map<String,bool> Imagemap_hwasun = {
  "assets/dogam_assets/Jeonnam/화순/전라남도_화순군_규봉암.jpg":false,
  "assets/dogam_assets/Jeonnam/화순/전라남도_화순군_너릿재 정상.jpg":false,
  "assets/dogam_assets/Jeonnam/화순/전라남도_화순군_만연폭포.jpg":false,
  "assets/dogam_assets/Jeonnam/화순/전라남도_화순군_망향정.jpg":false,
  "assets/dogam_assets/Jeonnam/화순/전라남도_화순군_백아산 하늘다리.jpg":false,
  "assets/dogam_assets/Jeonnam/화순/전라남도_화순군_세량지.jpg":false,
  "assets/dogam_assets/Jeonnam/화순/전라남도_화순군_수만리 들국화마을.jpg":false,
  "assets/dogam_assets/Jeonnam/화순/전라남도_화순군_수만리 철쭉공원.jpg":false,
  "assets/dogam_assets/Jeonnam/화순/전라남도_화순군_영벽정.jpg":false,
  "assets/dogam_assets/Jeonnam/화순/전라남도_화순군_유마사.jpg":false,
  "assets/dogam_assets/Jeonnam/화순/전라남도_화순군_화순 고인돌 유적지.jpg":false,
  "assets/dogam_assets/Jeonnam/화순/전라남도_화순군_화순 연둔리 숲정이.jpg":false,
  "assets/dogam_assets/Jeonnam/화순/전라남도_화순군_화순적벽.jpg":false,
  "assets/dogam_assets/Jeonnam/화순/전라남도_화순군_환산정.jpg":false,
};

List <String> url_hwasun_List=[
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
];