Map<String,bool> Imagemap_gurae = {
  "assets/dogam_assets/Jeonnam/구례/전라남도_구례군_구례 산수유마을.jpg":false,
  "assets/dogam_assets/Jeonnam/구례/전라남도_구례군_구례 오산 사성암 일원.jpg":false,
  "assets/dogam_assets/Jeonnam/구례/전라남도_구례군_구례관광특구.jpg":false,
  "assets/dogam_assets/Jeonnam/구례/전라남도_구례군_구례자연드림파크.jpg":false,
  "assets/dogam_assets/Jeonnam/구례/전라남도_구례군_사성암.jpg":false,
  "assets/dogam_assets/Jeonnam/구례/전라남도_구례군_산수유마을.jpg":false,
  "assets/dogam_assets/Jeonnam/구례/전라남도_구례군_산수유사랑공원.jpg":false,
  "assets/dogam_assets/Jeonnam/구례/전라남도_구례군_삼홍소.jpg":false,
  "assets/dogam_assets/Jeonnam/구례/전라남도_구례군_섬진강 대나무숲길.jpg":false,
  "assets/dogam_assets/Jeonnam/구례/전라남도_구례군_성삼재휴게소.jpg":false,
  "assets/dogam_assets/Jeonnam/구례/전라남도_구례군_용지동계곡.jpg":false,
  "assets/dogam_assets/Jeonnam/구례/전라남도_구례군_임걸령.jpg":false,
  "assets/dogam_assets/Jeonnam/구례/전라남도_구례군_지리산연곡사.jpg":false,
  "assets/dogam_assets/Jeonnam/구례/전라남도_구례군_천은사.jpg":false,
};

List <String> url_gurae_List=[
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
];