Map<String,bool> Imagemap_boeun = {
  "assets/dogam_assets/Chungbuk/보은/충청북도_보은군_구병리아름마을.jpg":false,
  "assets/dogam_assets/Chungbuk/보은/충청북도_보은군_대한불교조계종 법주사(法住寺).jpg":false,
  "assets/dogam_assets/Chungbuk/보은/충청북도_보은군_동학농민혁명 기념공원.jpg":false,
  "assets/dogam_assets/Chungbuk/보은/충청북도_보은군_만수계곡.jpg":false,
  "assets/dogam_assets/Chungbuk/보은/충청북도_보은군_충북알프스자연휴양림.jpg":false,
  "assets/dogam_assets/Chungbuk/보은/충청북도_보은군_팔상전.jpg":false,
  "assets/dogam_assets/Chungbuk/보은/충청북도_보은군_보은동헌.jpg":false,
  "assets/dogam_assets/Chungbuk/보은/충청북도_보은군_삼년산성.jpg":false,
  "assets/dogam_assets/Chungbuk/보은/충청북도_보은군_서원계곡.jpg":false,
  "assets/dogam_assets/Chungbuk/보은/충청북도_보은군_속리산 말티재 (말티고개).jpg":false,
  "assets/dogam_assets/Chungbuk/보은/충청북도_보은군_속리산국립공원.jpg":false,
  "assets/dogam_assets/Chungbuk/보은/충청북도_보은군_속리산조각공원.jpg":false,
  "assets/dogam_assets/Chungbuk/보은/충청북도_보은군_솔향공원.jpg":false,
  "assets/dogam_assets/Chungbuk/보은/충청북도_보은군_오장환문학관.jpg":false,
  "assets/dogam_assets/Chungbuk/보은/충청북도_보은군_팔상전.jpg":false,
};


List <String> url_boeun_List=[
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
];