Map<String,bool> Imagemap_daejeon = {
  "assets/dogam_assets/gwangyeok/대전/광역시_대전_국립중앙과학관.jpg":false,
  "assets/dogam_assets/gwangyeok/대전/광역시_대전_대동하늘공원.jpg":false,
  "assets/dogam_assets/gwangyeok/대전/광역시_대전_대전 엑스포 과학공원.jpg":false,
  "assets/dogam_assets/gwangyeok/대전/광역시_대전_대전스카이로드.jpg":false,
  "assets/dogam_assets/gwangyeok/대전/광역시_대전_대전시립미술관.jpg":false,
  "assets/dogam_assets/gwangyeok/대전/광역시_대전_대전오월드.jpg":false,
  "assets/dogam_assets/gwangyeok/대전/광역시_대전_뿌리공원.jpg":false,
  "assets/dogam_assets/gwangyeok/대전/광역시_대전_슬픈연가 촬영지.jpg":false,
  "assets/dogam_assets/gwangyeok/대전/광역시_대전_우암사적공원.jpg":false,
  "assets/dogam_assets/gwangyeok/대전/광역시_대전_으능정이 문화의 거리.jpg":false,
  "assets/dogam_assets/gwangyeok/대전/광역시_대전_이응노미술관.jpg":false,
  "assets/dogam_assets/gwangyeok/대전/광역시_대전_장태산 자연휴양림.jpg":false,
  "assets/dogam_assets/gwangyeok/대전/광역시_대전_테미공원.jpg":false,
  "assets/dogam_assets/gwangyeok/대전/광역시_대전_한밭수목원.jpg":false,
};

List <String> url_daejeon_List=[
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
];