Map<String,bool> Imagemap_yeongduk = {
  "assets/dogam_assets/gyeongbuk/영덕/경상북도_영덕군_괴시리 전통마을.jpg":false,
  "assets/dogam_assets/gyeongbuk/영덕/경상북도_영덕군_벌영메타세콰이어숲.jpg":false,
  "assets/dogam_assets/gyeongbuk/영덕/경상북도_영덕군_블루로드.jpg":false,
  "assets/dogam_assets/gyeongbuk/영덕/경상북도_영덕군_삼사해상공원 해양산책로.jpg":false,
  "assets/dogam_assets/gyeongbuk/영덕/경상북도_영덕군_삼사해상공원.jpg":false,
  "assets/dogam_assets/gyeongbuk/영덕/경상북도_영덕군_영덕 풍력발전단지.jpg":false,
  "assets/dogam_assets/gyeongbuk/영덕/경상북도_영덕군_영덕 화장실 노지.jpg":false,
  "assets/dogam_assets/gyeongbuk/영덕/경상북도_영덕군_영덕어촌민속전시관.jpg":false,
  "assets/dogam_assets/gyeongbuk/영덕/경상북도_영덕군_영덕해맞이공원.jpg":false,
  "assets/dogam_assets/gyeongbuk/영덕/경상북도_영덕군_오천솔밭유원지.jpg":false,
  "assets/dogam_assets/gyeongbuk/영덕/경상북도_영덕군_옥계유원지.jpg":false,
  "assets/dogam_assets/gyeongbuk/영덕/경상북도_영덕군_죽도산전망대(축산등대).jpg":false,
  "assets/dogam_assets/gyeongbuk/영덕/경상북도_영덕군_창포말등대.jpg":false,
  "assets/dogam_assets/gyeongbuk/영덕/경상북도_영덕군_해파랑공원.jpg":false,
};

List <String> url_yeongduk_List=[
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
];