Map<String,bool> Imagemap_cheongyang = {
  "assets/dogam_assets/chungnam/청양/충청남도_청양군_고운식물원.jpg":false,
  "assets/dogam_assets/chungnam/청양/충청남도_청양군_도림계곡.jpg":false,
  "assets/dogam_assets/chungnam/청양/충청남도_청양군_모덕사.jpg":false,
  "assets/dogam_assets/chungnam/청양/충청남도_청양군_사자산체험마을.jpg":false,
  "assets/dogam_assets/chungnam/청양/충청남도_청양군_우산성.jpg":false,
  "assets/dogam_assets/chungnam/청양/충청남도_청양군_작천계곡.jpg":false,
  "assets/dogam_assets/chungnam/청양/충청남도_청양군_지천구곡.jpg":false,
  "assets/dogam_assets/chungnam/청양/충청남도_청양군_천장호 출렁다리.jpg":false,
  "assets/dogam_assets/chungnam/청양/충청남도_청양군_청양목재문화체험장.jpg":false,
  "assets/dogam_assets/chungnam/청양/충청남도_청양군_청양알프스마을.jpg":false,
  "assets/dogam_assets/chungnam/청양/충청남도_청양군_칠갑산 장승공원.jpg":false,
  "assets/dogam_assets/chungnam/청양/충청남도_청양군_칠갑산얼음분수축제.jpg":false,
  "assets/dogam_assets/chungnam/청양/충청남도_청양군_칠갑산천문대.jpg":false,
  "assets/dogam_assets/chungnam/청양/충청남도_청양군_칠갑전망대.jpg":false,
};

List <String> url_cheongyang_List=[
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
];