Map<String,bool> Imagemap_anyang = {
  "assets/dogam_assets/Gyeonggi/안양/경기도_안양시_APAP 리.볼.버 Re. vol. ver.jpg":false,
  "assets/dogam_assets/Gyeonggi/안양/경기도_안양시_대한불교조계종 망해암.jpg":false,
  "assets/dogam_assets/Gyeonggi/안양/경기도_안양시_대한불교태고종 안양사.jpg":false,
  "assets/dogam_assets/Gyeonggi/안양/경기도_안양시_벽천광.jpg":false,
  "assets/dogam_assets/Gyeonggi/안양/경기도_안양시_병목안시민공원.jpg":false,
  "assets/dogam_assets/Gyeonggi/안양/경기도_안양시_분수대.jpg":false,
  "assets/dogam_assets/Gyeonggi/안양/경기도_안양시_삼덕공원.jpg":false,
  "assets/dogam_assets/Gyeonggi/안양/경기도_안양시_삼성산산림욕장.jpg":false,
  "assets/dogam_assets/Gyeonggi/안양/경기도_안양시_안양예술공원.jpg":false,
  "assets/dogam_assets/Gyeonggi/안양/경기도_안양시_천주교 수리산 순교 성지.jpg":false,
  "assets/dogam_assets/Gyeonggi/안양/경기도_안양시_평촌 1번가 문화의 거리.jpg":false,
  "assets/dogam_assets/Gyeonggi/안양/경기도_안양시_평촌중앙공원.jpg":false,
  "assets/dogam_assets/Gyeonggi/안양/경기도_안양시_학운공원.jpg":false,
  "assets/dogam_assets/Gyeonggi/안양/경기도_안양시_힐빙문화.jpg":false,
};


List <String> url_anyang_List=[
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "", 
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
];