Map<String,bool> Imagemap_mokpo = {
  "assets/dogam_assets/Jeonnam/목포/전라남도_목포시_고하도해안데크.jpg":false,
  "assets/dogam_assets/Jeonnam/목포/전라남도_목포시_노적봉예술공원.jpg":false,
  "assets/dogam_assets/Jeonnam/목포/전라남도_목포시_목포 갓바위 (천연기념물 제500호).jpg":false,
  "assets/dogam_assets/Jeonnam/목포/전라남도_목포시_목포 근대역사관 1관(구 목포일본영사관).jpg":false,
  "assets/dogam_assets/Jeonnam/목포/전라남도_목포시_목포 춤추는 바다분수.jpg":false,
  "assets/dogam_assets/Jeonnam/목포/전라남도_목포시_목포비밀장소.jpg":false,
  "assets/dogam_assets/Jeonnam/목포/전라남도_목포시_목포자연사박물관.jpg":false,
  "assets/dogam_assets/Jeonnam/목포/전라남도_목포시_목포진역사공원.jpg":false,
  "assets/dogam_assets/Jeonnam/목포/전라남도_목포시_서산동 시화골목.jpg":false,
  "assets/dogam_assets/Jeonnam/목포/전라남도_목포시_유달산 이등바위.jpg":false,
  "assets/dogam_assets/Jeonnam/목포/전라남도_목포시_유달산 일등바위(정상).jpg":false,
  "assets/dogam_assets/Jeonnam/목포/전라남도_목포시_儒達山.jpg":false,
  "assets/dogam_assets/Jeonnam/목포/전라남도_목포시_유달산낙조대.jpg":false,
  "assets/dogam_assets/Jeonnam/목포/전라남도_목포시_장미의거리.jpg":false,
};

List <String> url_mokpo_List=[
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
];