Map<String,bool> Imagemap_gapyeong= {
  "assets/dogam_assets/Gyeonggi/가평/경기도_가평군_가평레일파크.jpg":false,
  "assets/dogam_assets/Gyeonggi/가평/경기도_가평군_나인포레스트 이화원.jpg":false,
  "assets/dogam_assets/Gyeonggi/가평/경기도_가평군_남이섬.jpg":false,
  "assets/dogam_assets/Gyeonggi/가평/경기도_가평군_대성리국민관광지.jpg":false,
  "assets/dogam_assets/Gyeonggi/가평/경기도_가평군_명지계곡.jpg":false,
  "assets/dogam_assets/Gyeonggi/가평/경기도_가평군_명지폭포.jpg":false,
  "assets/dogam_assets/Gyeonggi/가평/경기도_가평군_쁘띠프랑스.jpg":false,
  "assets/dogam_assets/Gyeonggi/가평/경기도_가평군_아침고요수목원.jpg":false,
  "assets/dogam_assets/Gyeonggi/가평/경기도_가평군_에덴벚꽃길.jpg":false,
  "assets/dogam_assets/Gyeonggi/가평/경기도_가평군_유명산 자연휴양림.jpg":false,
  "assets/dogam_assets/Gyeonggi/가평/경기도_가평군_자라섬.jpg":false,
  "assets/dogam_assets/Gyeonggi/가평/경기도_가평군_조무락 계곡 폭포.jpg":false,
  "assets/dogam_assets/Gyeonggi/가평/경기도_가평군_조종천계곡.jpg":false,
  "assets/dogam_assets/Gyeonggi/가평/경기도_가평군_호명산 잣나무숲.jpg":false,
};
List <String> url_gapyeong_List=[
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "", 
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
];