Map<String,bool> Imagemap_goheong = {
  "assets/dogam_assets/Jeonnam/고흥/전라남도_고흥군_고흥 금탑사 비자나무 숲.jpg":false,
  "assets/dogam_assets/Jeonnam/고흥/전라남도_고흥군_고흥군.jpg":false,
  "assets/dogam_assets/Jeonnam/고흥/전라남도_고흥군_고흥만벚꽃길.jpg":false,
  "assets/dogam_assets/Jeonnam/고흥/전라남도_고흥군_고흥분청문화박물관.jpg":false,
  "assets/dogam_assets/Jeonnam/고흥/전라남도_고흥군_고흥유자공원.jpg":false,
  "assets/dogam_assets/Jeonnam/고흥/전라남도_고흥군_구도.jpg":false,
  "assets/dogam_assets/Jeonnam/고흥/전라남도_고흥군_길도(죽도).jpg":false,
  "assets/dogam_assets/Jeonnam/고흥/전라남도_고흥군_다도해해상국립공원 고흥분소.jpg":false,
  "assets/dogam_assets/Jeonnam/고흥/전라남도_고흥군_시호도 원시체험의 섬.jpg":false,
  "assets/dogam_assets/Jeonnam/고흥/전라남도_고흥군_시호도.jpg":false,
  "assets/dogam_assets/Jeonnam/고흥/전라남도_고흥군_연홍도.jpg":false,
  "assets/dogam_assets/Jeonnam/고흥/전라남도_고흥군_중산일몰전망대.jpg":false,
  "assets/dogam_assets/Jeonnam/고흥/전라남도_고흥군_초도.jpg":false
};
List <String> url_goheong_List=[
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
];