Map<String,bool> Imagemap_sejong = {
  "assets/dogam_assets/gwangyeok/세종/광역시_세종_국립세종수목원.jpg":false,
  "assets/dogam_assets/gwangyeok/세종/광역시_세종_금강7경(세종공원) 세종보좌안.jpg":false,
  "assets/dogam_assets/gwangyeok/세종/광역시_세종_금강자연휴양림.jpg":false,
  "assets/dogam_assets/gwangyeok/세종/광역시_세종_밀마루 전망대.jpg":false,
  "assets/dogam_assets/gwangyeok/세종/광역시_세종_베어트리파크.jpg":false,
  "assets/dogam_assets/gwangyeok/세종/광역시_세종_봉산동 향나무.jpg":false,
  "assets/dogam_assets/gwangyeok/세종/광역시_세종_비암사.jpg":false,
  "assets/dogam_assets/gwangyeok/세종/광역시_세종_세종 비암사 극락보전.jpg":false,
  "assets/dogam_assets/gwangyeok/세종/광역시_세종_세종전통시장.jpg":false,
  "assets/dogam_assets/gwangyeok/세종/광역시_세종_세종호수공원.jpg":false,
  "assets/dogam_assets/gwangyeok/세종/광역시_세종_영평사.jpg":false,
  "assets/dogam_assets/gwangyeok/세종/광역시_세종_운주산성.jpg":false,
  "assets/dogam_assets/gwangyeok/세종/광역시_세종_황룡사.jpg":false,
};
List <String> url_sejong_List=[
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
];