Map<String,bool> Imagemap_gwangju = {
  "assets/dogam_assets/gwangyeok/광주/광역시_광주_5.18자유공원.jpg":false,
  "assets/dogam_assets/gwangyeok/광주/광역시_광주_광주천.jpg":false,
  "assets/dogam_assets/gwangyeok/광주/광역시_광주_광주호 호수생태원.jpg":false,
  "assets/dogam_assets/gwangyeok/광주/광역시_광주_국립광주박물관.jpg":false,
  "assets/dogam_assets/gwangyeok/광주/광역시_광주_리프트카.jpg":false,
  "assets/dogam_assets/gwangyeok/광주/광역시_광주_무등산 국립공원.jpg":false,
  "assets/dogam_assets/gwangyeok/광주/광역시_광주_무등산 지산유원지.jpg":false,
  "assets/dogam_assets/gwangyeok/광주/광역시_광주_무등산서석대.jpg":false,
  "assets/dogam_assets/gwangyeok/광주/광역시_광주_송산유원지.jpg":false,
  "assets/dogam_assets/gwangyeok/광주/광역시_광주_어등산.jpg":false,
  "assets/dogam_assets/gwangyeok/광주/광역시_광주_운천저수지.jpg":false,
  "assets/dogam_assets/gwangyeok/광주/광역시_광주_월봉서원":false,
  "assets/dogam_assets/gwangyeok/광주/광역시_광주_펭귄마을.jpg":false,
  "assets/dogam_assets/gwangyeok/광주/광역시_광주_풍암 호수공원.jpg":false,
};
List <String> url_gwangju_List=[
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
];