Map<String,bool> Imagemap_danyang = {
  "assets/dogam_assets/Chungbuk/단양/충청북도_단양군_고수동굴.jpg":false,
  "assets/dogam_assets/Chungbuk/단양/충청북도_단양군_다리안계곡예악.jpg":false,
  "assets/dogam_assets/Chungbuk/단양/충청북도_단양군_다리안폭포.jpg":false,
  "assets/dogam_assets/Chungbuk/단양/충청북도_단양군_단양 천동동굴.jpg":false,
  "assets/dogam_assets/Chungbuk/단양/충청북도_단양군_단양 청춘패러.jpg":false,
  "assets/dogam_assets/Chungbuk/단양/충청북도_단양군_단양강 잔도길.jpg":false,
  "assets/dogam_assets/Chungbuk/단양/충청북도_단양군_단양다누리아쿠아리움.jpg":false,
  "assets/dogam_assets/Chungbuk/단양/충청북도_단양군_도담삼봉.jpg":false,
  "assets/dogam_assets/Chungbuk/단양/충청북도_단양군_만천하 스카이워크.jpg":false,
  "assets/dogam_assets/Chungbuk/단양/충청북도_단양군_사인암(舍人巖).jpg":false,
  "assets/dogam_assets/Chungbuk/단양/충청북도_단양군_새밭계곡.jpg":false,
  "assets/dogam_assets/Chungbuk/단양/충청북도_단양군_수양개빛터널.jpgg":false,
  "assets/dogam_assets/Chungbuk/단양/충청북도_단양군_온달관광지.jpg":false,
  "assets/dogam_assets/Chungbuk/단양/충청북도_단양군_이끼터널.jpg":false,
};


List <String> url_danyang_List=[
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
];