Map<String,bool> Imagemap_gwacheon = {
  "assets/dogam_assets/Gyeonggi/과천/경기도_과천시_과천 보광사 목조여래좌상.jpg":false,
  "assets/dogam_assets/Gyeonggi/과천/경기도_과천시_과천 연주암 삼층석탑.jpg":false,
  "assets/dogam_assets/Gyeonggi/과천/경기도_과천시_관악산(육봉 국기봉).jpg":false,
  "assets/dogam_assets/Gyeonggi/과천/경기도_과천시_관악산(팔봉 국기봉).jpg":false,
  "assets/dogam_assets/Gyeonggi/과천/경기도_과천시_관악산(학바위).jpg":false,
  "assets/dogam_assets/Gyeonggi/과천/경기도_과천시_국립과천과학관 곤충생태관.jpg":false,
  "assets/dogam_assets/Gyeonggi/과천/경기도_과천시_국립과천과학관.jpg":false,
  "assets/dogam_assets/Gyeonggi/과천/경기도_과천시_국립현대미술관 과천.jpg":false,
  "assets/dogam_assets/Gyeonggi/과천/경기도_과천시_뽀로로벽화.jpg":false,
  "assets/dogam_assets/Gyeonggi/과천/경기도_과천시_서울대공원.jpg":false,
  "assets/dogam_assets/Gyeonggi/과천/경기도_과천시_서울랜드.jpg":false,
  "assets/dogam_assets/Gyeonggi/과천/경기도_과천시_온온사.jpg":false,
  "assets/dogam_assets/Gyeonggi/과천/경기도_과천시_중앙공원.jpg":false,
  "assets/dogam_assets/Gyeonggi/과천/경기도_과천시_추사박물관.jpg":false,
};

List <String> url_gwacheon_List=[
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "", 
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
];