Map<String,bool> Imagemap_hampyeong = {
  "assets/dogam_assets/Jeonnam/함평/전라남도_함평군_꽃무릇공원.jpg":false,
  "assets/dogam_assets/Jeonnam/함평/전라남도_함평군_달맞이공원.jpg":false,
  "assets/dogam_assets/Jeonnam/함평/전라남도_함평군_민예학당.jpg":false,
  "assets/dogam_assets/Jeonnam/함평/전라남도_함평군_안악해수욕장.jpg":false,
  "assets/dogam_assets/Jeonnam/함평/전라남도_함평군_엑스포공원사업소.jpg":false,
  "assets/dogam_assets/Jeonnam/함평/전라남도_함평군_용천사.jpg":false,
  "assets/dogam_assets/Jeonnam/함평/전라남도_함평군_자산서원.jpg":false,
  "assets/dogam_assets/Jeonnam/함평/전라남도_함평군_한옥마을.jpg":false,
  "assets/dogam_assets/Jeonnam/함평/전라남도_함평군_함평 양서 파충류 생태공원.jpg":false,
  "assets/dogam_assets/Jeonnam/함평/전라남도_함평군_함평보광사범종.jpg":false,
  "assets/dogam_assets/Jeonnam/함평/전라남도_함평군_함평자연생태공원.jpg":false,
  "assets/dogam_assets/Jeonnam/함평/전라남도_함평군_황토와들꽃세상학습원.jpg":false
};
List <String> url_hampyeong_List=[
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
];