Map<String,bool> Imagemap_jangheong = {
  "assets/dogam_assets/Jeonnam/장흥/전라남도_장흥군_귀족호도박물관.jpg":false,
  "assets/dogam_assets/Jeonnam/장흥/전라남도_장흥군_보림사.jpg":false,
  "assets/dogam_assets/Jeonnam/장흥/전라남도_장흥군_사인정.jpg":false,
  "assets/dogam_assets/Jeonnam/장흥/전라남도_장흥군_선학동 유채마을.jpg":false,
  "assets/dogam_assets/Jeonnam/장흥/전라남도_장흥군_수인산성.jpg":false,
  "assets/dogam_assets/Jeonnam/장흥/전라남도_장흥군_심천공원.jpg":false,
  "assets/dogam_assets/Jeonnam/장흥/전라남도_장흥군_유치자연휴양림.jpg":false,
  "assets/dogam_assets/Jeonnam/장흥/전라남도_장흥군_이청준생가.jpg":false,
  "assets/dogam_assets/Jeonnam/장흥/전라남도_장흥군_장흥 무계고택.jpg":false,
  "assets/dogam_assets/Jeonnam/장흥/전라남도_장흥군_정남진 장흥토요시장.jpg":false,
  "assets/dogam_assets/Jeonnam/장흥/전라남도_장흥군_정남진 전망대.jpg":false,
  "assets/dogam_assets/Jeonnam/장흥/전라남도_장흥군_정남진 천문과학관.jpg":false,
  "assets/dogam_assets/Jeonnam/장흥/전라남도_장흥군_천관산관광농원.jpg":false,
  "assets/dogam_assets/Jeonnam/장흥/전라남도_장흥군_천관산도립공원.jpg":false,
};
List <String> url_jangheong_List=[
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
];