Map<String,bool> Imagemap_dongducheon = {
  "assets/dogam_assets/Gyeonggi/동두천/경기도_동두천시_경기북부어린이박물관.jpg":false,
  "assets/dogam_assets/Gyeonggi/동두천/경기도_동두천시_동두천시 외국인 관광특구.jpg":false,
  "assets/dogam_assets/Gyeonggi/동두천/경기도_동두천시_무지개약수터.jpg":false,
  "assets/dogam_assets/Gyeonggi/동두천/경기도_동두천시_베스트.jpg":false,
  "assets/dogam_assets/Gyeonggi/동두천/경기도_동두천시_소요산관광지야영장.jpg":false,
  "assets/dogam_assets/Gyeonggi/동두천/경기도_동두천시_소요산국민관광지.jpg":false,
  "assets/dogam_assets/Gyeonggi/동두천/경기도_동두천시_쇠목계곡.jpg":false,
  "assets/dogam_assets/Gyeonggi/동두천/경기도_동두천시_옥류폭포.jpg":false,
  "assets/dogam_assets/Gyeonggi/동두천/경기도_동두천시_원효폭포.jpg":false,
  "assets/dogam_assets/Gyeonggi/동두천/경기도_동두천시_자유수호평화박물관.jpg":false,
  "assets/dogam_assets/Gyeonggi/동두천/경기도_동두천시_자재암.jpg":false,
  "assets/dogam_assets/Gyeonggi/동두천/경기도_동두천시_장림계곡.jpg":false,
  "assets/dogam_assets/Gyeonggi/동두천/경기도_동두천시_탑동유원지.jpg":false,
  "assets/dogam_assets/Gyeonggi/동두천/경기도_동두천시_현충탑.jpg":false,
};



List <String> url_dongducheon_List=[
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "", 
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
];