name: cosbe_domo
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  dotted_border: ^2.0.0+2
  google_maps_flutter_web: ^0.3.3
  permission_handler: ^10.0.0
  google_maps_flutter: ^2.1.8
  location: ^4.4.0
  latlong: ^0.6.1
  latlong2: ^0.8.1
  async: ^2.8.2
  image_picker: ^0.8.5+3
  firebase_core: ^1.20.0
  firebase_storage: ^10.3.3
  cloud_firestore: ^3.4.1
  csv: ^5.0.1
  firebase_auth: ^3.7.0
  fluttertoast: ^8.0.9
  flutter_local_notifications: ^11.0.0
  flutter_secure_storage: ^6.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  assets:
    - assets/home_assets/
    - assets/chat_assets/
    - assets/dogam_assets/do_assets/
    - assets/dogam_assets/do_image_assets/
    - assets/logo/
    - assets/mypage_assets/
    - assets/recommend_assets/
    - assets/csv_assets/
    - assets/csv_assets/광역시/
    - assets/csv_assets/충청북도/
    - assets/csv_assets/경기도/
    - assets/csv_assets/경상북도/
    - assets/csv_assets/충청남도/
    - assets/csv_assets/전라남도/
    - assets/csv_assets/경상남도/
    - assets/csv_assets/전라북도/
    - assets/csv_assets/강원도/
    - assets/dogam_assets/do_image_assets/
    - assets/dogam_assets/Chungbuk/Si_assets/
    - assets/dogam_assets/Chungbuk/청주/
    - assets/dogam_assets/Chungbuk/괴산/
    - assets/dogam_assets/Chungbuk/단양/
    - assets/dogam_assets/Chungbuk/보은/
    - assets/dogam_assets/Chungbuk/영동/
    - assets/dogam_assets/Chungbuk/옥천/
    - assets/dogam_assets/Chungbuk/음성/
    - assets/dogam_assets/Chungbuk/제천/
    - assets/dogam_assets/Chungbuk/증평/
    - assets/dogam_assets/Chungbuk/진천/
    - assets/dogam_assets/Chungbuk/충주/
    - assets/dogam_assets/chungnam/Si_assets/
    - assets/dogam_assets/chungnam/계룡/
    - assets/dogam_assets/chungnam/공주/
    - assets/dogam_assets/chungnam/금산/
    - assets/dogam_assets/chungnam/논산/
    - assets/dogam_assets/chungnam/당진/
    - assets/dogam_assets/chungnam/보령/
    - assets/dogam_assets/chungnam/부여/
    - assets/dogam_assets/chungnam/서산/
    - assets/dogam_assets/chungnam/서천/
    - assets/dogam_assets/chungnam/아산/
    - assets/dogam_assets/chungnam/예산/
    - assets/dogam_assets/chungnam/천안/
    - assets/dogam_assets/chungnam/청양/
    - assets/dogam_assets/chungnam/태안/
    - assets/dogam_assets/chungnam/홍성/
    - assets/dogam_assets/Gangwon/Si_assets/
    - assets/dogam_assets/Gangwon/강릉/
    - assets/dogam_assets/Gangwon/고성/
    - assets/dogam_assets/Gangwon/동해/
    - assets/dogam_assets/Gangwon/삼척/
    - assets/dogam_assets/Gangwon/속초/
    - assets/dogam_assets/Gangwon/양구/
    - assets/dogam_assets/Gangwon/양양/
    - assets/dogam_assets/Gangwon/영월/
    - assets/dogam_assets/Gangwon/원주/
    - assets/dogam_assets/Gangwon/인제/
    - assets/dogam_assets/Gangwon/정선/
    - assets/dogam_assets/Gangwon/철원/
    - assets/dogam_assets/Gangwon/춘천/
    - assets/dogam_assets/Gangwon/태백/
    - assets/dogam_assets/Gangwon/평창/
    - assets/dogam_assets/Gangwon/홍천/
    - assets/dogam_assets/Gangwon/화천/
    - assets/dogam_assets/Gangwon/횡성/
    - assets/dogam_assets/gwangyeok/Si_assets/
    - assets/dogam_assets/gwangyeok/광주/
    - assets/dogam_assets/gwangyeok/대구/
    - assets/dogam_assets/gwangyeok/대전/
    - assets/dogam_assets/gwangyeok/부산/
    - assets/dogam_assets/gwangyeok/서울/
    - assets/dogam_assets/gwangyeok/세종/
    - assets/dogam_assets/gwangyeok/울산/
    - assets/dogam_assets/gwangyeok/인천/
    - assets/dogam_assets/gwangyeok/제주/
    - assets/dogam_assets/gyeongbuk/Si_assets/
    - assets/dogam_assets/gyeongbuk/경산/
    - assets/dogam_assets/gyeongbuk/경주/
    - assets/dogam_assets/gyeongbuk/고령/
    - assets/dogam_assets/gyeongbuk/구미/
    - assets/dogam_assets/gyeongbuk/군위/
    - assets/dogam_assets/gyeongbuk/김천/
    - assets/dogam_assets/gyeongbuk/문경/
    - assets/dogam_assets/gyeongbuk/봉화/
    - assets/dogam_assets/gyeongbuk/상주/
    - assets/dogam_assets/gyeongbuk/성주/
    - assets/dogam_assets/gyeongbuk/안동/
    - assets/dogam_assets/gyeongbuk/영덕/
    - assets/dogam_assets/gyeongbuk/영양/
    - assets/dogam_assets/gyeongbuk/영주/
    - assets/dogam_assets/gyeongbuk/영천/
    - assets/dogam_assets/gyeongbuk/예천/
    - assets/dogam_assets/gyeongbuk/울릉/
    - assets/dogam_assets/gyeongbuk/울진/
    - assets/dogam_assets/gyeongbuk/의성/
    - assets/dogam_assets/gyeongbuk/청도/
    - assets/dogam_assets/gyeongbuk/청송/
    - assets/dogam_assets/gyeongbuk/칠곡/
    - assets/dogam_assets/gyeongbuk/포항/
    - assets/dogam_assets/Gyeonggi/Si_assets/
    - assets/dogam_assets/Gyeonggi/가평/
    - assets/dogam_assets/Gyeonggi/고양/
    - assets/dogam_assets/Gyeonggi/과천/
    - assets/dogam_assets/Gyeonggi/광명/
    - assets/dogam_assets/Gyeonggi/광주/
    - assets/dogam_assets/Gyeonggi/구리/
    - assets/dogam_assets/Gyeonggi/군포/
    - assets/dogam_assets/Gyeonggi/김포/
    - assets/dogam_assets/Gyeonggi/남양주/
    - assets/dogam_assets/Gyeonggi/동두천/
    - assets/dogam_assets/Gyeonggi/부천/
    - assets/dogam_assets/Gyeonggi/성남/
    - assets/dogam_assets/Gyeonggi/수원/
    - assets/dogam_assets/Gyeonggi/시흥/
    - assets/dogam_assets/Gyeonggi/안산/
    - assets/dogam_assets/Gyeonggi/안성/
    - assets/dogam_assets/Gyeonggi/안양/
    - assets/dogam_assets/Gyeonggi/양주/
    - assets/dogam_assets/Gyeonggi/양평/
    - assets/dogam_assets/Gyeonggi/여주/
    - assets/dogam_assets/Gyeonggi/연천/
    - assets/dogam_assets/Gyeonggi/오산/
    - assets/dogam_assets/Gyeonggi/용인/
    - assets/dogam_assets/Gyeonggi/의왕/
    - assets/dogam_assets/Gyeonggi/의정부/
    - assets/dogam_assets/Gyeonggi/이천/
    - assets/dogam_assets/Gyeonggi/파주/
    - assets/dogam_assets/Gyeonggi/평택/
    - assets/dogam_assets/Gyeonggi/포천/
    - assets/dogam_assets/Gyeonggi/하남/
    - assets/dogam_assets/Gyeonggi/화성/
    - assets/dogam_assets/gyeongnam/Si_assets/
    - assets/dogam_assets/gyeongnam/거제/
    - assets/dogam_assets/gyeongnam/거창/
    - assets/dogam_assets/gyeongnam/고성/
    - assets/dogam_assets/gyeongnam/김해/
    - assets/dogam_assets/gyeongnam/남해/
    - assets/dogam_assets/gyeongnam/밀양/
    - assets/dogam_assets/gyeongnam/사천/
    - assets/dogam_assets/gyeongnam/산청/
    - assets/dogam_assets/gyeongnam/양산/
    - assets/dogam_assets/gyeongnam/의령/
    - assets/dogam_assets/gyeongnam/진주/
    - assets/dogam_assets/gyeongnam/창녕/
    - assets/dogam_assets/gyeongnam/창원/
    - assets/dogam_assets/gyeongnam/통영/
    - assets/dogam_assets/gyeongnam/하동/
    - assets/dogam_assets/gyeongnam/함안/
    - assets/dogam_assets/gyeongnam/함양/
    - assets/dogam_assets/gyeongnam/합천/
    - assets/dogam_assets/Jeonbuk/Si_assets/
    - assets/dogam_assets/Jeonbuk/고창/
    - assets/dogam_assets/Jeonbuk/군산/
    - assets/dogam_assets/Jeonbuk/김제/
    - assets/dogam_assets/Jeonbuk/남원/
    - assets/dogam_assets/Jeonbuk/무주/
    - assets/dogam_assets/Jeonbuk/부안/
    - assets/dogam_assets/Jeonbuk/순창/
    - assets/dogam_assets/Jeonbuk/완주/
    - assets/dogam_assets/Jeonbuk/익산/
    - assets/dogam_assets/Jeonbuk/임실/
    - assets/dogam_assets/Jeonbuk/장수/
    - assets/dogam_assets/Jeonbuk/전주/
    - assets/dogam_assets/Jeonbuk/정읍/
    - assets/dogam_assets/Jeonbuk/진안/
    - assets/dogam_assets/Jeonnam/Si_assets/
    - assets/dogam_assets/Jeonnam/강진/
    - assets/dogam_assets/Jeonnam/고흥/
    - assets/dogam_assets/Jeonnam/곡성/
    - assets/dogam_assets/Jeonnam/광양/
    - assets/dogam_assets/Jeonnam/구례/
    - assets/dogam_assets/Jeonnam/나주/
    - assets/dogam_assets/Jeonnam/담양/
    - assets/dogam_assets/Jeonnam/목포/
    - assets/dogam_assets/Jeonnam/무안/
    - assets/dogam_assets/Jeonnam/보성/
    - assets/dogam_assets/Jeonnam/순천/
    - assets/dogam_assets/Jeonnam/신안/
    - assets/dogam_assets/Jeonnam/여수/
    - assets/dogam_assets/Jeonnam/영광/
    - assets/dogam_assets/Jeonnam/영암/
    - assets/dogam_assets/Jeonnam/완도/
    - assets/dogam_assets/Jeonnam/장흥/
    - assets/dogam_assets/Jeonnam/진도/
    - assets/dogam_assets/Jeonnam/함평/
    - assets/dogam_assets/Jeonnam/해남/
    - assets/dogam_assets/Jeonnam/화순/
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
