Map<String,bool> Imagemap_hoengseong = {
  "assets/dogam_assets/Gangwon/횡성/강원도_횡성군_고라데이마을.jpg":false,
  "assets/dogam_assets/Gangwon/횡성/강원도_횡성군_국립청태산자연휴양림.jpg":false,
  "assets/dogam_assets/Gangwon/횡성/강원도_횡성군_국립횡성숲체원.jpg":false,
  "assets/dogam_assets/Gangwon/횡성/강원도_횡성군_노아의 숲.jpg":false,
  "assets/dogam_assets/Gangwon/횡성/강원도_횡성군_부곡계곡.jpg":false,
  "assets/dogam_assets/Gangwon/횡성/강원도_횡성군_신대계곡.jpg":false,
  "assets/dogam_assets/Gangwon/횡성/강원도_횡성군_운암정.jpg":false,
  "assets/dogam_assets/Gangwon/횡성/강원도_횡성군_자작나무숲미술관.jpg":false,
  "assets/dogam_assets/Gangwon/횡성/강원도_횡성군_천주교 풍수원 성당.jpg":false,
  "assets/dogam_assets/Gangwon/횡성/강원도_횡성군_횡성 호수길 제5구간.jpg":false,
  "assets/dogam_assets/Gangwon/횡성/강원도_횡성군_횡성댐.jpg":false,
  "assets/dogam_assets/Gangwon/횡성/강원도_횡성군_횡성루지체험장.jpg":false,
  "assets/dogam_assets/Gangwon/횡성/강원도_횡성군_횡성자연휴양림.jpg":false,
  "assets/dogam_assets/Gangwon/횡성/강원도_횡성군_횡성전통시장.jpg":false,
};

List <String> url_hoengseong_List=[
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
];