Map<String,bool> Imagemap_jangsu = {
  "assets/dogam_assets/Jeonbuk/장수/전라북도_장수군_(주)내추럴존.jpg":false,
  "assets/dogam_assets/Jeonbuk/장수/전라북도_장수군_논개생가.jpg":false,
  "assets/dogam_assets/Jeonbuk/장수/전라북도_장수군_대곡 관광지.jpg":false,
  "assets/dogam_assets/Jeonbuk/장수/전라북도_장수군_덕산계곡(방화동 생태길).jpg":false,
  "assets/dogam_assets/Jeonbuk/장수/전라북도_장수군_뜬봉샘.jpg":false,
  "assets/dogam_assets/Jeonbuk/장수/전라북도_장수군_뜬봉샘생태공원.jpg":false,
  "assets/dogam_assets/Jeonbuk/장수/전라북도_장수군_방화동 가족휴가촌.jpg":false,
  "assets/dogam_assets/Jeonbuk/장수/전라북도_장수군_방화동자연휴양림.jpg":false,
  "assets/dogam_assets/Jeonbuk/장수/전라북도_장수군_와룡자연휴양림.jpg":false,
  "assets/dogam_assets/Jeonbuk/장수/전라북도_장수군_의암사.jpg":false,
  "assets/dogam_assets/Jeonbuk/장수/전라북도_장수군_장수 논개 수상레저(수상스키장).jpg":false,
  "assets/dogam_assets/Jeonbuk/장수/전라북도_장수군_장수누리파크.jpg":false,
  "assets/dogam_assets/Jeonbuk/장수/전라북도_장수군_장수물빛공원.jpg":false,
  "assets/dogam_assets/Jeonbuk/장수/전라북도_장수군_장수향교.jpg":false,
};

List <String> url_jangsu_List=[
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
];