Map<String,bool> Imagemap_iksan = {
  "assets/dogam_assets/Jeonbuk/익산/전라북도_익산시_국립익산박물관.jpg":false,
  "assets/dogam_assets/Jeonbuk/익산/전라북도_익산시_마한박물관.jpg":false,
  "assets/dogam_assets/Jeonbuk/익산/전라북도_익산시_배산체육공원.jpg":false,
  "assets/dogam_assets/Jeonbuk/익산/전라북도_익산시_백제왕궁박물관.jpg":false,
  "assets/dogam_assets/Jeonbuk/익산/전라북도_익산시_성당포구마을.jpg":false,
  "assets/dogam_assets/Jeonbuk/익산/전라북도_익산시_수덕호.jpg":false,
  "assets/dogam_assets/Jeonbuk/익산/전라북도_익산시_왕궁리유적.jpg":false,
  "assets/dogam_assets/Jeonbuk/익산/전라북도_익산시_웅포관광지.jpg":false,
  "assets/dogam_assets/Jeonbuk/익산/전라북도_익산시_익산 문화예술의거리.jpg":false,
  "assets/dogam_assets/Jeonbuk/익산/전라북도_익산시_익산 미륵사지.jpg":false,
  "assets/dogam_assets/Jeonbuk/익산/전라북도_익산시_익산 쌍릉.jpg":false,
  "assets/dogam_assets/Jeonbuk/익산/전라북도_익산시_익산보석박물관.jpg":false,
  "assets/dogam_assets/Jeonbuk/익산/전라북도_익산시_천호동굴.jpg":false,
  "assets/dogam_assets/Jeonbuk/익산/전라북도_익산시_화석전시관.jpg":false,
};

List <String> url_iksan_List=[
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
];