Map<String,bool> Imagemap_ulleung= {
  "assets/dogam_assets/gyeongbuk/울릉/경상북도_울릉군_내수전 일출전망대.jpg":false,
  "assets/dogam_assets/gyeongbuk/울릉/경상북도_울릉군_내수전약수터.jpg":false,
  "assets/dogam_assets/gyeongbuk/울릉/경상북도_울릉군_대풍감.jpg":false,
  "assets/dogam_assets/gyeongbuk/울릉/경상북도_울릉군_독도박물관.jpg":false,
  "assets/dogam_assets/gyeongbuk/울릉/경상북도_울릉군_봉래폭포.jpg":false,
  "assets/dogam_assets/gyeongbuk/울릉/경상북도_울릉군_사동해수욕장.jpg":false,
  "assets/dogam_assets/gyeongbuk/울릉/경상북도_울릉군_안용복기념관.jpg":false,
  "assets/dogam_assets/gyeongbuk/울릉/경상북도_울릉군_울릉 성인봉 원시림.jpg":false,
  "assets/dogam_assets/gyeongbuk/울릉/경상북도_울릉군_울릉국화섬백리향군락지.jpg":false,
  "assets/dogam_assets/gyeongbuk/울릉/경상북도_울릉군_울릉도 태하 등대.jpg":false,
  "assets/dogam_assets/gyeongbuk/울릉/경상북도_울릉군_촛대바위.jpg":false,
  "assets/dogam_assets/gyeongbuk/울릉/경상북도_울릉군_코끼리바위(공암).jpg":false,
  "assets/dogam_assets/gyeongbuk/울릉/경상북도_울릉군_태하 향목 모노레일.jpg":false,
  "assets/dogam_assets/gyeongbuk/울릉/경상북도_울릉군_행남 해안산책로.jpg":false,
};

List <String> url_ulleung_List=[
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
];