Map<String,bool> Imagemap_hamyang = {
  "assets/dogam_assets/Chungbuk/Cheongju/suamgol.jpg":false,
  "assets/dogam_assets/Chungbuk/Cheongju/cheongju_museum.jpg":false,
  "assets/dogam_assets/Chungbuk/Cheongju/sangdang3.jpg":false,
  "assets/dogam_assets/Chungbuk/Cheongju/cheongju_zoo.jpg":false,
  "assets/dogam_assets/Chungbuk/Cheongju/cheongju_yonghwasa.jpg":false,
  "assets/dogam_assets/Chungbuk/Cheongju/cheongjuland.jpg":false,
  "assets/dogam_assets/Chungbuk/Cheongju/cheongju_garosu.jpg":false,
  "assets/dogam_assets/Chungbuk/Cheongju/cheongju_sungangil.jpg":false,
  "assets/dogam_assets/Chungbuk/Cheongju/cheongju_goinswae.jpg":false,
  "assets/dogam_assets/Chungbuk/Cheongju/cheongju_jungangpark.jpg":false,
  "assets/dogam_assets/Chungbuk/Cheongju/cheongju_cheongnamdae.jpg":false,
  "assets/dogam_assets/Chungbuk/Cheongju/cheongju_jungbukdong.jpg":false,
  "assets/dogam_assets/Chungbuk/Cheongju/cheongju_myeongam.jpg":false,
  "assets/dogam_assets/Chungbuk/Cheongju/cheongju_samilpark.jpg":false,
};

List <String> url_hamyang_List=[
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
];