Map<String,bool> Imagemap_wonju = {
  "assets/dogam_assets/Gangwon/원주/강원도_원주시_간현관광지.jpg":false,
  "assets/dogam_assets/Gangwon/원주/강원도_원주시_나오라쇼.jpg":false,
  "assets/dogam_assets/Gangwon/원주/강원도_원주시_뮤지엄 산.jpg":false,
  "assets/dogam_assets/Gangwon/원주/강원도_원주시_반계리 은행나무.jpg":false,
  "assets/dogam_assets/Gangwon/원주/강원도_원주시_소금산 그랜드밸리.jpg":false,
  "assets/dogam_assets/Gangwon/원주/강원도_원주시_소금산 울렁다리.jpg":false,
  "assets/dogam_assets/Gangwon/원주/강원도_원주시_소금산 출렁다리.jpg":false,
  "assets/dogam_assets/Gangwon/원주/강원도_원주시_영원사.jpg":false,
  "assets/dogam_assets/Gangwon/원주/강원도_원주시_원주 강원감영.jpg":false,
  "assets/dogam_assets/Gangwon/원주/강원도_원주시_원주 구룡사 보광루.jpg":false,
  "assets/dogam_assets/Gangwon/원주/강원도_원주시_원주레일파크.jpg":false,
  "assets/dogam_assets/Gangwon/원주/강원도_원주시_원주시역사박물관.jpg":false,
  "assets/dogam_assets/Gangwon/원주/강원도_원주시_원주중앙시장.jpg":false,
};

List <String> url_wonju_List=[
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
];