Map<String,bool> Imagemap_paju = {
  "assets/dogam_assets/Gyeonggi/파주/경기도_파주시_감악산 출렁다리.jpg":false,
  "assets/dogam_assets/Gyeonggi/파주/경기도_파주시_도라전망대.jpg":false,
  "assets/dogam_assets/Gyeonggi/파주/경기도_파주시_마장호수 출렁다리.jpg":false,
  "assets/dogam_assets/Gyeonggi/파주/경기도_파주시_반구정.jpg":false,
  "assets/dogam_assets/Gyeonggi/파주/경기도_파주시_벽초지수목원.jpg":false,
  "assets/dogam_assets/Gyeonggi/파주/경기도_파주시_오두산통일전망대.jpg":false,
  "assets/dogam_assets/Gyeonggi/파주/경기도_파주시_율곡수목원.jpg":false,
  "assets/dogam_assets/Gyeonggi/파주/경기도_파주시_임진각 평화누리공원.jpg":false,
  "assets/dogam_assets/Gyeonggi/파주/경기도_파주시_통일공원.jpg":false,
  "assets/dogam_assets/Gyeonggi/파주/경기도_파주시_파주 임진각 평화 곤돌라.jpg":false,
  "assets/dogam_assets/Gyeonggi/파주/경기도_파주시_프로방스 마을.jpg":false,
  "assets/dogam_assets/Gyeonggi/파주/경기도_파주시_하니랜드.jpg":false,
  "assets/dogam_assets/Gyeonggi/파주/경기도_파주시_헤이리 예술마을.jpg":false
};

List <String> url_paju_List=[
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "", 
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
];