Map<String,bool> Imagemap_milyang = {
  "assets/dogam_assets/gyeongnam/밀양/경상남도_밀양시_만어사(萬魚寺).jpg":false,
  "assets/dogam_assets/gyeongnam/밀양/경상남도_밀양시_미리미동국.jpg":false,
  "assets/dogam_assets/gyeongnam/밀양/경상남도_밀양시_밀양 사명대사 생가지.jpg":false,
  "assets/dogam_assets/gyeongnam/밀양/경상남도_밀양시_밀양 연꽃단지.jpg":false,
  "assets/dogam_assets/gyeongnam/밀양/경상남도_밀양시_밀양댐.jpg":false,
  "assets/dogam_assets/gyeongnam/밀양/경상남도_밀양시_밀양해천.jpg":false,
  "assets/dogam_assets/gyeongnam/밀양/경상남도_밀양시_삼문송림.jpg":false,
  "assets/dogam_assets/gyeongnam/밀양/경상남도_밀양시_얼음골.jpg":false,
  "assets/dogam_assets/gyeongnam/밀양/경상남도_밀양시_영남루.jpg":false,
  "assets/dogam_assets/gyeongnam/밀양/경상남도_밀양시_의열기념관.jpg":false,
  "assets/dogam_assets/gyeongnam/밀양/경상남도_밀양시_층층폭포.jpgg":false,
  "assets/dogam_assets/gyeongnam/밀양/경상남도_밀양시_트윈터널.jpg":false,
  "assets/dogam_assets/gyeongnam/밀양/경상남도_밀양시_종남산.jpg":false,
  "assets/dogam_assets/gyeongnam/밀양/경상남도_밀양시_호박소계곡.jpg":false,
};
List <String> url_milyang_List=[
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
];