Map<String,bool> Imagemap_jaecheon= {
  "assets/dogam_assets/Chungbuk/제천/충청북도_제천시_교동민화마을.jpg":false,
  "assets/dogam_assets/Chungbuk/제천/충청북도_제천시_금월봉.jpg":false,
  "assets/dogam_assets/Chungbuk/제천/충청북도_제천시_능강계곡.jpg":false,
  "assets/dogam_assets/Chungbuk/제천/충청북도_제천시_덕동계곡.jpg":false,
  "assets/dogam_assets/Chungbuk/제천/충청북도_제천시_덕주사.jpg":false,
  "assets/dogam_assets/Chungbuk/제천/충청북도_제천시_의림지.jpg":false,
  "assets/dogam_assets/Chungbuk/제천/충청북도_제천시_의림지솔밭공원.jpg":false,
  "assets/dogam_assets/Chungbuk/제천/충청북도_제천시_정방사.jpg":false,
  "assets/dogam_assets/Chungbuk/제천/충청북도_제천시_제천중앙시장.jpg":false,
  "assets/dogam_assets/Chungbuk/제천/충청북도_제천시_청풍랜드.jpg":false,
  "assets/dogam_assets/Chungbuk/제천/충청북도_제천시_청풍문화재단지.jpg":false,
  "assets/dogam_assets/Chungbuk/제천/충청북도_제천시_청풍호 관광 모노레일.jpg":false,
};
List <String> url_jaecheon_List=[
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
];