Map<String,bool> Imagemap_hwacheon = {
  "assets/dogam_assets/Gangwon/화천/강원도_화천군_광덕계곡.jpg":false,
  "assets/dogam_assets/Gangwon/화천/강원도_화천군_낭천산림욕장.jpg":false,
  "assets/dogam_assets/Gangwon/화천/강원도_화천군_딴산 유원지 인공폭포.jpg":false,
  "assets/dogam_assets/Gangwon/화천/강원도_화천군_딴산유원지.jpg":false,
  "assets/dogam_assets/Gangwon/화천/강원도_화천군_미륵바위.jpg":false,
  "assets/dogam_assets/Gangwon/화천/강원도_화천군_비래바위.jpg":false,
  "assets/dogam_assets/Gangwon/화천/강원도_화천군_비목공원.jpg":false,
  "assets/dogam_assets/Gangwon/화천/강원도_화천군_사랑나무.jpg":false,
  "assets/dogam_assets/Gangwon/화천/강원도_화천군_숲으로 다리.jpg":false,
  "assets/dogam_assets/Gangwon/화천/강원도_화천군_실내얼음조각광장.jpg":false,
  "assets/dogam_assets/Gangwon/화천/강원도_화천군_연꽃단지.jpg":false,
  "assets/dogam_assets/Gangwon/화천/강원도_화천군_용담계곡.jpg":false,
  "assets/dogam_assets/Gangwon/화천/강원도_화천군_평화의 댐.jpg":false,
  "assets/dogam_assets/Gangwon/화천/강원도_화천군_화천민속박물관.jpg":false,
};

List <String> url_hwacheon_List=[
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
];