Map<String,bool> Imagemap_samcheok = {
  "assets/dogam_assets/Gangwon/삼척/강원도_삼척시_강원종합박물관.jpg":false,
  "assets/dogam_assets/Gangwon/삼척/강원도_삼척시_내평계곡.jpg":false,
  "assets/dogam_assets/Gangwon/삼척/강원도_삼척시_대금굴.jpg":false,
  "assets/dogam_assets/Gangwon/삼척/강원도_삼척시_삼척 대이리 동굴지대.jpg":false,
  "assets/dogam_assets/Gangwon/삼척/강원도_삼척시_삼척 오십천변 장미공원.jpg":false,
  "assets/dogam_assets/Gangwon/삼척/강원도_삼척시_삼척모노레일.jpg":false,
  "assets/dogam_assets/Gangwon/삼척/강원도_삼척시_삼척해변역.jpg":false,
  "assets/dogam_assets/Gangwon/삼척/강원도_삼척시_삼척해상케이블카 장호역.jpg":false,
  "assets/dogam_assets/Gangwon/삼척/강원도_삼척시_삼척해양레일바이크 궁촌정거장.jpg":false,
  "assets/dogam_assets/Gangwon/삼척/강원도_삼척시_삼척해양레일바이크 용화정거장.jpg":false,
  "assets/dogam_assets/Gangwon/삼척/강원도_삼척시_용굴촛대바위길.jpg":false,
  "assets/dogam_assets/Gangwon/삼척/강원도_삼척시_죽서루.jpg":false,
  "assets/dogam_assets/Gangwon/삼척/강원도_삼척시_환선굴(幻仙窟).jpg":false,
  "assets/dogam_assets/Gangwon/삼척/강원도_삼척시_환선굴매표소.jpg":false,
};

List <String> url_samchoek_List=[
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
];