Map<String,bool> Imagemap_yeonggwang = {
  "assets/dogam_assets/Jeonnam/영광/전라남도_영광군_갈구여.jpg":false,
  "assets/dogam_assets/Jeonnam/영광/전라남도_영광군_백수해안공원.jpg":false,
  "assets/dogam_assets/Jeonnam/영광/전라남도_영광군_백수해안관광도로.jpg":false,
  "assets/dogam_assets/Jeonnam/영광/전라남도_영광군_백제불교최초도래지.jpg":false,
  "assets/dogam_assets/Jeonnam/영광/전라남도_영광군_법성포구.jpg":false,
  "assets/dogam_assets/Jeonnam/영광/전라남도_영광군_불갑저수지수변공원.jpg":false,
  "assets/dogam_assets/Jeonnam/영광/전라남도_영광군_불갑테마공원.jpg":false,
  "assets/dogam_assets/Jeonnam/영광/전라남도_영광군_숲쟁이 꽃동산.jpg":false,
  "assets/dogam_assets/Jeonnam/영광/전라남도_영광군_숲쟁이공원.jpg":false,
  "assets/dogam_assets/Jeonnam/영광/전라남도_영광군_영광 내산서원.jpg":false,
  "assets/dogam_assets/Jeonnam/영광/전라남도_영광군_영광노을전시관.jpg":false,
  "assets/dogam_assets/Jeonnam/영광/전라남도_영광군_영광산림박물관.jpg":false,
  "assets/dogam_assets/Jeonnam/영광/전라남도_영광군_천일염전.jpg":false,
  "assets/dogam_assets/Jeonnam/영광/전라남도_영광군_한마음공원.jpg":false,
};
List <String> url_yeonggwang_List=[
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
];