Map<String,bool> Imagemap_namwon = {
  "assets/dogam_assets/Jeonbuk/남원/전라북도_남원시_[지리산 둘레길 코스] 3구간.인월-금계.jpg":false,
  "assets/dogam_assets/Jeonbuk/남원/전라북도_남원시_광한루(廣寒樓).jpg":false,
  "assets/dogam_assets/Jeonbuk/남원/전라북도_남원시_광한루.jpg":false,
  "assets/dogam_assets/Jeonbuk/남원/전라북도_남원시_광한루원.jpg":false,
  "assets/dogam_assets/Jeonbuk/남원/전라북도_남원시_구룡계곡.jpg":false,
  "assets/dogam_assets/Jeonbuk/남원/전라북도_남원시_남원관광단지.jpg":false,
  "assets/dogam_assets/Jeonbuk/남원/전라북도_남원시_남원랜드.jpg":false,
  "assets/dogam_assets/Jeonbuk/남원/전라북도_남원시_남원역 폐역.jpg":false,
  "assets/dogam_assets/Jeonbuk/남원/전라북도_남원시_뱀사골 계곡.jpg":false,
  "assets/dogam_assets/Jeonbuk/남원/전라북도_남원시_오리정.jpg":false,
  "assets/dogam_assets/Jeonbuk/남원/전라북도_남원시_육모정계곡.jpg":false,
  "assets/dogam_assets/Jeonbuk/남원/전라북도_남원시_지리산허브밸리.jpg":false,
  "assets/dogam_assets/Jeonbuk/남원/전라북도_남원시_춘향테마파크.jpg":false,
  "assets/dogam_assets/Jeonbuk/남원/전라북도_남원시_춘향허브마을.jpg":false,
};
List <String> url_namwon_List=[
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
];