Map<String,bool> Imagemap_seongju= {
  "assets/dogam_assets/gyeongbuk/성주/경상북도_성주군_가야산야생화식물원.jpg":false,
  "assets/dogam_assets/gyeongbuk/성주/경상북도_성주군_독용산성.jpg":false,
  "assets/dogam_assets/gyeongbuk/성주/경상북도_성주군_성밖숲.jpg":false,
  "assets/dogam_assets/gyeongbuk/성주/경상북도_성주군_성주 성산동 고분군.jpg":false,
  "assets/dogam_assets/gyeongbuk/성주/경상북도_성주군_성주 세종대왕자 태실.jpg":false,
  "assets/dogam_assets/gyeongbuk/성주/경상북도_성주군_성주 쌍충사적비.jpg":false,
  "assets/dogam_assets/gyeongbuk/성주/경상북도_성주군_성주역사테마파크.jpg":false,
  "assets/dogam_assets/gyeongbuk/성주/경상북도_성주군_세목지.jpg":false,
  "assets/dogam_assets/gyeongbuk/성주/경상북도_성주군_세종대왕 왕자태실.jpg":false,
  "assets/dogam_assets/gyeongbuk/성주/경상북도_성주군_심원사.jpg":false,
  "assets/dogam_assets/gyeongbuk/성주/경상북도_성주군_청락정.jpg":false,
  "assets/dogam_assets/gyeongbuk/성주/경상북도_성주군_포천계곡.jpg":false,
  "assets/dogam_assets/gyeongbuk/성주/경상북도_성주군_회연서원.jpg":false,
};
List <String> url_seongju_List=[
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
];