Map<String,bool> Imagemap_uljin= {
  "assets/dogam_assets/gyeongbuk/울진/경상북도_울진군_금강소나무숲길.jpg":false,
  "assets/dogam_assets/gyeongbuk/울진/경상북도_울진군_덕구계곡 온천 원탕.jpg":false,
  "assets/dogam_assets/gyeongbuk/울진/경상북도_울진군_등기산 스카이워크.jpg":false,
  "assets/dogam_assets/gyeongbuk/울진/경상북도_울진군_불영계곡.jpg":false,
  "assets/dogam_assets/gyeongbuk/울진/경상북도_울진군_불영사(佛影寺).jpg":false,
  "assets/dogam_assets/gyeongbuk/울진/경상북도_울진군_성류굴.jpg":false,
  "assets/dogam_assets/gyeongbuk/울진/경상북도_울진군_왕피천케이블카.jpg":false,
  "assets/dogam_assets/gyeongbuk/울진/경상북도_울진군_울진아쿠아리움.jpg":false,
  "assets/dogam_assets/gyeongbuk/울진/경상북도_울진군_울진왕피천공원.jpg":false,
  "assets/dogam_assets/gyeongbuk/울진/경상북도_울진군_울진유황온천온탕.jpg":false,
  "assets/dogam_assets/gyeongbuk/울진/경상북도_울진군_죽변 해안 스카이레일.jpg":false,
  "assets/dogam_assets/gyeongbuk/울진/경상북도_울진군_하트해변.jpg":false,
  "assets/dogam_assets/gyeongbuk/울진/경상북도_울진군_해중전망대.jpg":false,
  "assets/dogam_assets/gyeongbuk/울진/경상북도_울진군_갓바위전망대.jpg":false,
};
List <String> url_uljin_List=[
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
];