Map<String,bool> Imagemap_jungeb = {
  "assets/dogam_assets/Jeonbuk/정읍/전라북도_정읍시_금선계곡.jpg":false,
  "assets/dogam_assets/Jeonbuk/정읍/전라북도_정읍시_내장산 용굴.jpg":false,
  "assets/dogam_assets/Jeonbuk/정읍/전라북도_정읍시_내장산국립공원.jpg":false,
  "assets/dogam_assets/Jeonbuk/정읍/전라북도_정읍시_내장산수목원.jpg":false,
  "assets/dogam_assets/Jeonbuk/정읍/전라북도_정읍시_내장산조각공원.jpg":false,
  "assets/dogam_assets/Jeonbuk/정읍/전라북도_정읍시_옥정호 구절초테마공원.jpg":false,
  "assets/dogam_assets/Jeonbuk/정읍/전라북도_정읍시_우화정.jpg":false,
  "assets/dogam_assets/Jeonbuk/정읍/전라북도_정읍시_원적계곡.jpg":false,
  "assets/dogam_assets/Jeonbuk/정읍/전라북도_정읍시_정읍 쌍화차거리.jpg":false,
  "assets/dogam_assets/Jeonbuk/정읍/전라북도_정읍시_정읍 피향정.jpg":false,
  "assets/dogam_assets/Jeonbuk/정읍/전라북도_정읍시_정읍사공원.jpg":false,
  "assets/dogam_assets/Jeonbuk/정읍/전라북도_정읍시_정읍시립박물관.jpg":false,
  "assets/dogam_assets/Jeonbuk/정읍/전라북도_정읍시_칠보물테마유원지.jpg":false
};
List <String> url_jungeb_List=[
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
];