Map<String,bool> Imagemap_anseong = {
  "assets/dogam_assets/Gyeonggi/안성/경기도_안성시_박두진 문학길.jpg":false,
  "assets/dogam_assets/Gyeonggi/안성/경기도_안성시_서운산성.jpg":false,
  "assets/dogam_assets/Gyeonggi/안성/경기도_안성시_석남사.jpg":false,
  "assets/dogam_assets/Gyeonggi/안성/경기도_안성시_솔밭공원":false,
  "assets/dogam_assets/Gyeonggi/안성/경기도_안성시_안성남사당공연장.jpg":false,
  "assets/dogam_assets/Gyeonggi/안성/경기도_안성시_안성맞춤가족공원.jpg":false,
  "assets/dogam_assets/Gyeonggi/안성/경기도_안성시_안성맞춤랜드.jpg":false,
  "assets/dogam_assets/Gyeonggi/안성/경기도_안성시_안성맞춤박물관.jpg":false,
  "assets/dogam_assets/Gyeonggi/안성/경기도_안성시_안성팜랜드.jpg":false,
  "assets/dogam_assets/Gyeonggi/안성/경기도_안성시_운수암.jpg":false,
  "assets/dogam_assets/Gyeonggi/안성/경기도_안성시_중앙대학교 키스로드.jpg":false,
  "assets/dogam_assets/Gyeonggi/안성/경기도_안성시_천주교 미리내 성지.jpg":false,
  "assets/dogam_assets/Gyeonggi/안성/경기도_안성시_청원사.jpg":false
};


List <String> url_anseong_List=[
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "", 
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
];