Map<String,bool> Imagemap_asan = {
  "assets/dogam_assets/chungnam/아산/충청남도_아산시_강당골.jpg":false,
  "assets/dogam_assets/chungnam/아산/충청남도_아산시_곡교천 은행나무길.jpg":false,
  "assets/dogam_assets/chungnam/아산/충청남도_아산시_송곡리은행나무길.jpg":false,
  "assets/dogam_assets/chungnam/아산/충청남도_아산시_신정호공원.jpg":false,
  "assets/dogam_assets/chungnam/아산/충청남도_아산시_신정호국민관광지.jpg":false,
  "assets/dogam_assets/chungnam/아산/충청남도_아산시_신정호유원지.jpg":false,
  "assets/dogam_assets/chungnam/아산/충청남도_아산시_아산 곡교천 은행나무길.jpg":false,
  "assets/dogam_assets/chungnam/아산/충청남도_아산시_영인산자연휴양림.jpg":false,
  "assets/dogam_assets/chungnam/아산/충청남도_아산시_외암민속관.jpg":false,
  "assets/dogam_assets/chungnam/아산/충청남도_아산시_외암민속마을.jpg":false,
  "assets/dogam_assets/chungnam/아산/충청남도_아산시_은행나무길.jpg":false,
  "assets/dogam_assets/chungnam/아산/충청남도_아산시_지중해마을.jpg":false,
  "assets/dogam_assets/chungnam/아산/충청남도_아산시_충남 아산 기쁨두배마을.jpg":false,
  "assets/dogam_assets/chungnam/아산/충청남도_아산시_피나클랜드 수목원.jpg":false,
};

List <String> url_asan_List=[
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
];