Map<String,bool> Imagemap_siheung = {
  "assets/dogam_assets/Gyeonggi/시흥/경기도_시흥시_관곡지.jpg":false,
  "assets/dogam_assets/Gyeonggi/시흥/경기도_시흥시_물왕 호수.jpg":false,
  "assets/dogam_assets/Gyeonggi/시흥/경기도_시흥시_미생의 다리(자전거 다리).jpg":false,
  "assets/dogam_assets/Gyeonggi/시흥/경기도_시흥시_배곧 한울공원.jpg":false,
  "assets/dogam_assets/Gyeonggi/시흥/경기도_시흥시_배곧생명공원.jpg":false,
  "assets/dogam_assets/Gyeonggi/시흥/경기도_시흥시_소산서원.jpg":false,
  "assets/dogam_assets/Gyeonggi/시흥/경기도_시흥시_시흥 연꽃테마파크.jpg":false,
  "assets/dogam_assets/Gyeonggi/시흥/경기도_시흥시_시흥갯골생태공원.jpg":false,
  "assets/dogam_assets/Gyeonggi/시흥/경기도_시흥시_오이도 빨강등대.jpg":false,
  "assets/dogam_assets/Gyeonggi/시흥/경기도_시흥시_오이도 선사유적공원.jpg":false,
  "assets/dogam_assets/Gyeonggi/시흥/경기도_시흥시_오이도포구 해양관광단지.jpg":false,
  "assets/dogam_assets/Gyeonggi/시흥/경기도_시흥시_옥구공원.jpg":false,
  "assets/dogam_assets/Gyeonggi/시흥/경기도_시흥시_용도수목원.jpg":false,
  "assets/dogam_assets/Gyeonggi/시흥/경기도_시흥시_월곶포구 시흥관광단지.jpg":false,
};
List <String> url_siheung_List=[
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "", 
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
];