Map<String,bool> Imagemap_yanggu = {
  "assets/dogam_assets/Gangwon/양구/강원도_양구군_DMZ펀치볼둘레길.jpg":false,
  "assets/dogam_assets/Gangwon/양구/강원도_양구군_광치계곡유원지.jpg":false,
  "assets/dogam_assets/Gangwon/양구/강원도_양구군_광치자연휴양림.jpg":false,
  "assets/dogam_assets/Gangwon/양구/강원도_양구군_국토정중앙천문대.jpg":false,
  "assets/dogam_assets/Gangwon/양구/강원도_양구군_두타연.jpg":false,
  "assets/dogam_assets/Gangwon/양구/강원도_양구군_박수근미술관.jpg":false,
  "assets/dogam_assets/Gangwon/양구/강원도_양구군_수입천.jpg":false,
  "assets/dogam_assets/Gangwon/양구/강원도_양구군_양구 인문학박물관.jpg":false,
  "assets/dogam_assets/Gangwon/양구/강원도_양구군_양구군관광안내소.jpg":false,
  "assets/dogam_assets/Gangwon/양구/강원도_양구군_양구선사박물관.jpg":false,
  "assets/dogam_assets/Gangwon/양구/강원도_양구군_용소 빙장.jpg":false,
  "assets/dogam_assets/Gangwon/양구/강원도_양구군_을지전망대.jpg":false,
  "assets/dogam_assets/Gangwon/양구/강원도_양구군_제4땅굴.jpg":false,
  "assets/dogam_assets/Gangwon/양구/강원도_양구군_해안야생화공원 (야생화원료 체험장).jpg":false,
};

List <String> url_yanggu_List=[
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
];