Map<String,bool> Imagemap_yangpyeong = {
  "assets/dogam_assets/Gyeonggi/양평/경기도_양평군_갈산공원.jpgg":false,
  "assets/dogam_assets/Gyeonggi/양평/경기도_양평군_더그림.jpg":false,
  "assets/dogam_assets/Gyeonggi/양평/경기도_양평군_세미원.jpg":false,
  "assets/dogam_assets/Gyeonggi/양평/경기도_양평군_양평 보릿고개마을.jpg":false,
  "assets/dogam_assets/Gyeonggi/양평/경기도_양평군_양평군립미술관.jpg":false,
  "assets/dogam_assets/Gyeonggi/양평/경기도_양평군_양평들꽃수목원.jpg":false,
  "assets/dogam_assets/Gyeonggi/양평/경기도_양평군_양평쉬자파크.jpg":false,
  "assets/dogam_assets/Gyeonggi/양평/경기도_양평군_양평핫플.jpg":false,
  "assets/dogam_assets/Gyeonggi/양평/경기도_양평군_용문산 용문사.jpg":false,
  "assets/dogam_assets/Gyeonggi/양평/경기도_양평군_용문산 자연휴양림.jpg":false,
  "assets/dogam_assets/Gyeonggi/양평/경기도_양평군_용문산관광지.jpg":false,
  "assets/dogam_assets/Gyeonggi/양평/경기도_양평군_중원계곡.jpg":false,
  "assets/dogam_assets/Gyeonggi/양평/경기도_양평군_풀향기허브나라.jpg":false,
  "assets/dogam_assets/Gyeonggi/양평/경기도_양평군_한화리조트 양평.jpg":false,
};
List <String> url_yangpyeong_List=[
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "", 
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
];