Map<String,bool> Imagemap_gangneung= {
  "assets/dogam_assets/Gangwon/강릉/강원도_강릉시_강릉 선교장.jpg":false,
  "assets/dogam_assets/Gangwon/강릉/강원도_강릉시_강릉솔향수목원.jpg":false,
  "assets/dogam_assets/Gangwon/강릉/강원도_강릉시_강릉임해자연휴양림.jpg":false,
  "assets/dogam_assets/Gangwon/강릉/강원도_강릉시_경포아쿠아리움.jpg":false,
  "assets/dogam_assets/Gangwon/강릉/강원도_강릉시_경포호.jpg":false,
  "assets/dogam_assets/Gangwon/강릉/강원도_강릉시_경포호수광장.jpg":false,
  "assets/dogam_assets/Gangwon/강릉/강원도_강릉시_멍에전망대.jpg":false,
  "assets/dogam_assets/Gangwon/강릉/강원도_강릉시_모래시계공원.jpg":false,
  "assets/dogam_assets/Gangwon/강릉/강원도_강릉시_안반데기.jpg":false,
  "assets/dogam_assets/Gangwon/강릉/강원도_강릉시_오죽헌.jpg":false,
  "assets/dogam_assets/Gangwon/강릉/강원도_강릉시_월화거리.jpg":false,
  "assets/dogam_assets/Gangwon/강릉/강원도_강릉시_정동진 시간박물관.jpg":false,
  "assets/dogam_assets/Gangwon/강릉/강원도_강릉시_정동진레일바이크.jpg":false,
  "assets/dogam_assets/Gangwon/강릉/강원도_강릉시_허균·허난설헌 기념공원.jpg":false,
};

List <String> url_gangneung_List=[
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
];