Map<String,bool> Imagemap_tongyeong = {
  "assets/dogam_assets/gyeongnam/통영/경상남도_통영시_스카이라인루지 통영.jpg":false,
  "assets/dogam_assets/gyeongnam/통영/경상남도_통영시_동피랑 벽화마을.jpg":false,
  "assets/dogam_assets/gyeongnam/통영/경상남도_통영시_통영해저터널.jpg":false,
  "assets/dogam_assets/gyeongnam/통영/경상남도_통영시_이순신공원.jpg":false,
  "assets/dogam_assets/gyeongnam/통영/경상남도_통영시_서피랑.jpg":false,
  "assets/dogam_assets/gyeongnam/통영/경상남도_통영시_우도.jpg":false,
  "assets/dogam_assets/gyeongnam/통영/경상남도_통영시_소매물도등대.jpg":false,
"assets/dogam_assets/gyeongnam/통영/경상남도_통영시_매물도.jpg":false,
  "assets/dogam_assets/gyeongnam/통영/경상남도_통영시_통영중앙전통시장.jpg":false,
  "assets/dogam_assets/gyeongnam/통영/경상남도_통영시_통영대교.jpg":false,
};
List <String> url_tongyeong_List=[
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
];