Map<String,bool> Imagemap_seocheon = {
  "assets/dogam_assets/chungnam/서천/충청남도_서천군_국립생태원 에코리움.jpg":false,
  "assets/dogam_assets/chungnam/서천/충청남도_서천군_국립생태원.jpg":false,
  "assets/dogam_assets/chungnam/서천/충청남도_서천군_국립해양생물자원관.jpg":false,
  "assets/dogam_assets/chungnam/서천/충청남도_서천군_국립희리산해송자연휴양림.jpg":false,
  "assets/dogam_assets/chungnam/서천/충청남도_서천군_금강하구둑관광단지.jpg":false,
  "assets/dogam_assets/chungnam/서천/충청남도_서천군_기벌포 해전전망대.jpg":false,
  "assets/dogam_assets/chungnam/서천/충청남도_서천군_마량리동백나무숲.jpg":false,
  "assets/dogam_assets/chungnam/서천/충청남도_서천군_서천식물예술원.jpg":false,
  "assets/dogam_assets/chungnam/서천/충청남도_서천군_서천판교마을.jpg":false,
  "assets/dogam_assets/chungnam/서천/충청남도_서천군_월하성어촌체험마을.jpg":false,
  "assets/dogam_assets/chungnam/서천/충청남도_서천군_장항송림산림욕장.jpg":false,
  "assets/dogam_assets/chungnam/서천/충청남도_서천군_장항스카이워크.jpg":false,
  "assets/dogam_assets/chungnam/서천/충청남도_서천군_조류생태전시관.jpg":false,
  "assets/dogam_assets/chungnam/서천/충청남도_서천군_한국최초 성경전래지 기념관.jpg":false,
};

List <String> url_seocheon_List=[
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
];