Map<String,bool> Imagemap_wanju = {
  "assets/dogam_assets/Jeonbuk/완주/전라북도_완주군_고산자연휴양림.jpg":false,
  "assets/dogam_assets/Jeonbuk/완주/전라북도_완주군_대둔산도립공원.jpg":false,
  "assets/dogam_assets/Jeonbuk/완주/전라북도_완주군_대아 수목원.jpg":false,
  "assets/dogam_assets/Jeonbuk/완주/전라북도_완주군_대한민국 술테마박물관.jpg":false,
  "assets/dogam_assets/Jeonbuk/완주/전라북도_완주군_모악산관광단지.jpg":false,
  "assets/dogam_assets/Jeonbuk/완주/전라북도_완주군_물고기마을.jpg":false,
  "assets/dogam_assets/Jeonbuk/완주/전라북도_완주군_삼례문화예술촌.jpg":false,
  "assets/dogam_assets/Jeonbuk/완주/전라북도_완주군_안덕건강힐링체험마을.jpg":false,
  "assets/dogam_assets/Jeonbuk/완주/전라북도_완주군_완주 화암사 우화루.jpg":false,
  "assets/dogam_assets/Jeonbuk/완주/전라북도_완주군_운장산계곡.jpg":false,
  "assets/dogam_assets/Jeonbuk/완주/전라북도_완주군_위봉사.jpg":false,
  "assets/dogam_assets/Jeonbuk/완주/전라북도_완주군_위봉폭포.jpg":false,
  "assets/dogam_assets/Jeonbuk/완주/전라북도_완주군_전북도립미술관.jpg":false,
  "assets/dogam_assets/Jeonbuk/완주/전라북도_완주군_창포마을안티에이징센터.jpg":false,
};

List <String> url_wanju_List=[
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
];