Map<String,bool> Imagemap_namyangju = {
  "assets/dogam_assets/Gyeonggi/남양주/경기도_남양주시_구 능내역.jpg":false,
  "assets/dogam_assets/Gyeonggi/남양주/경기도_남양주시_남양주시립박물관.jpg":false,
  "assets/dogam_assets/Gyeonggi/남양주/경기도_남양주시_다산길.jpg":false,
  "assets/dogam_assets/Gyeonggi/남양주/경기도_남양주시_다산생태공원.jpg":false,
  "assets/dogam_assets/Gyeonggi/남양주/경기도_남양주시_몽골문화촌.jpg":false,
  "assets/dogam_assets/Gyeonggi/남양주/경기도_남양주시_묘적사.jpg":false,
  "assets/dogam_assets/Gyeonggi/남양주/경기도_남양주시_물의정원.jpg":false,
  "assets/dogam_assets/Gyeonggi/남양주/경기도_남양주시_비금계곡.jpg":false,
  "assets/dogam_assets/Gyeonggi/남양주/경기도_남양주시_산들소리 수목원.jpg":false,
  "assets/dogam_assets/Gyeonggi/남양주/경기도_남양주시_수종사.jpg":false,
  "assets/dogam_assets/Gyeonggi/남양주/경기도_남양주시_어린이비전센터.jpg":false,
  "assets/dogam_assets/Gyeonggi/남양주/경기도_남양주시_오남호수공원.jpg":false,
  "assets/dogam_assets/Gyeonggi/남양주/경기도_남양주시_천마산군립공원.jpg":false,
  "assets/dogam_assets/Gyeonggi/남양주/경기도_남양주시_팔현계곡 八賢溪谷.jpg":false,
};

List <String> url_namyangju_List=[
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "", 
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
];