Map<String,bool> Imagemap_gongju = {
  "assets/dogam_assets/chungnam/공주/충청남도_공주시_공산성.jpg":false,
  "assets/dogam_assets/chungnam/공주/충청남도_공주시_제민천.jpg":false,
  "assets/dogam_assets/chungnam/공주/충청남도_공주시_동학사계곡.jpg":false,
  "assets/dogam_assets/chungnam/공주/충청남도_공주시_국립공주박물관.jpg":false,
  "assets/dogam_assets/chungnam/공주/충청남도_공주시_미르섬.jpg":false,
  "assets/dogam_assets/chungnam/공주/충청남도_공주시_금학생태공원.jpg":false,
  "assets/dogam_assets/chungnam/공주/충청남도_공주시_대한불교조계종 동학사(東鶴寺).jpg":false,
  "assets/dogam_assets/chungnam/공주/충청남도_공주시_무령왕릉.jpg":false,
  "assets/dogam_assets/chungnam/공주/충청남도_공주시_공주한옥마을.jpg":false,
};
List <String> url_gongju_List=[
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
];