Map<String,bool> Imagemap_chuncheon = {
  "assets/dogam_assets/Gangwon/춘천/강원도_춘천시_강촌레일파크 김유정레일바이크.jpg":false,
  "assets/dogam_assets/Gangwon/춘천/강원도_춘천시_공지천 유원지.jpg":false,
  "assets/dogam_assets/Gangwon/춘천/강원도_춘천시_남이섬.jpg":false,
  "assets/dogam_assets/Gangwon/춘천/강원도_춘천시_소양강스카이워크.jpg":false,
  "assets/dogam_assets/Gangwon/춘천/강원도_춘천시_소양강처녀상.jpg":false,
  "assets/dogam_assets/Gangwon/춘천/강원도_춘천시_소양호.jpg":false,
  "assets/dogam_assets/Gangwon/춘천/강원도_춘천시_육림고개.jpg":false,
  "assets/dogam_assets/Gangwon/춘천/강원도_춘천시_의암호 스카이워크.jpg":false,
  "assets/dogam_assets/Gangwon/춘천/강원도_춘천시_제이드가든 수목원.jpg":false,
  "assets/dogam_assets/Gangwon/춘천/강원도_춘천시_청평사.jpgg":false,
  "assets/dogam_assets/Gangwon/춘천/강원도_춘천시_청평사계곡.jpg":false,
  "assets/dogam_assets/Gangwon/춘천/강원도_춘천시_춘천 삼악산 호수케이블카 (하부정차장).jpg":false,
  "assets/dogam_assets/Gangwon/춘천/강원도_춘천시_춘천물레길.jpg":false,
  "assets/dogam_assets/Gangwon/춘천/강원도_춘천시_춘천중도물레길.jpg":false,
};

List <String> url_chuncheon_List=[
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
];