Map<String,bool> Imagemap_gangjin = {
  "assets/dogam_assets/Jeonnam/강진/전라남도_강진군_가우도 길.jpg":false,
  "assets/dogam_assets/Jeonnam/강진/전라남도_강진군_가우도 저두.jpg":false,
  "assets/dogam_assets/Jeonnam/강진/전라남도_강진군_가우도 청자다리.jpg":false,
  "assets/dogam_assets/Jeonnam/강진/전라남도_강진군_가우도.jpg":false,
  "assets/dogam_assets/Jeonnam/강진/전라남도_강진군_강진만 생태공원.jpg":false,
  "assets/dogam_assets/Jeonnam/강진/전라남도_강진군_강진천변생태호수공원.jpg":false,
  "assets/dogam_assets/Jeonnam/강진/전라남도_강진군_금곡사.jpg":false,
  "assets/dogam_assets/Jeonnam/강진/전라남도_강진군_금릉경포대.jpg":false,
  "assets/dogam_assets/Jeonnam/강진/전라남도_강진군_다산초당(茶山草堂).jpg":false,
  "assets/dogam_assets/Jeonnam/강진/전라남도_강진군_무위사.jpg":false,
  "assets/dogam_assets/Jeonnam/강진/전라남도_강진군_분홍나루, 고바우전망대.jpg":false,
  "assets/dogam_assets/Jeonnam/강진/전라남도_강진군_사의재(四宜齋).jpg":false,
  "assets/dogam_assets/Jeonnam/강진/전라남도_강진군_석문공원.jpg":false,
  "assets/dogam_assets/Jeonnam/강진/전라남도_강진군_소석문.jpg":false,
};
List <String> url_gangjin_List=[
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
];