Map<String,bool> Imagemap_wando = {
  "assets/dogam_assets/Jeonnam/완도/전라남도_완도군_갈마도.jpg":false,
  "assets/dogam_assets/Jeonnam/완도/전라남도_완도군_다도해일출공원.jpg":false,
  "assets/dogam_assets/Jeonnam/완도/전라남도_완도군_망끝전망대.jpg":false,
  "assets/dogam_assets/Jeonnam/완도/전라남도_완도군_보길도 윤선도원림.jpg":false,
  "assets/dogam_assets/Jeonnam/완도/전라남도_완도군_보길도갯길.jpg":false,
  "assets/dogam_assets/Jeonnam/완도/전라남도_완도군_완도 모노레일.jpg":false,
  "assets/dogam_assets/Jeonnam/완도/전라남도_완도군_상왕봉.jpg":false,
  "assets/dogam_assets/Jeonnam/완도/전라남도_완도군_완도 예송리 상록수림.jpg":false,
  "assets/dogam_assets/Jeonnam/완도/전라남도_완도군_완도.jpg":false,
  "assets/dogam_assets/Jeonnam/완도/전라남도_완도군_완도타워.jpg":false,
  "assets/dogam_assets/Jeonnam/완도/전라남도_완도군_장도 청해진 유적지.jpg":false,
  "assets/dogam_assets/Jeonnam/완도/전라남도_완도군_장보고동상.jpg":false,
  "assets/dogam_assets/Jeonnam/완도/전라남도_완도군_전라남도완도자연휴양림.jpg":false,
  "assets/dogam_assets/Jeonnam/완도/전라남도_완도군_청해포구촬영장 (해신 촬영지).jpg":false,
};

List <String> url_wando_List=[
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
];