Map<String,bool> Imagemap_pohang = {
  "assets/dogam_assets/gyeongbuk/포항/경상북도_포항시_구룡포 일본인가옥거리.jpg":false,
  "assets/dogam_assets/gyeongbuk/포항/경상북도_포항시_구룡포근대역사관.jpg":false,
  "assets/dogam_assets/gyeongbuk/포항/경상북도_포항시_송도해변.jpg":false,
  "assets/dogam_assets/gyeongbuk/포항/경상북도_포항시_영일대 해상누각.jpg":false,
  "assets/dogam_assets/gyeongbuk/포항/경상북도_포항시_영일대해수욕장.jpg":false,
  "assets/dogam_assets/gyeongbuk/포항/경상북도_포항시_이가리 닻 전망대.jpg":false,
  "assets/dogam_assets/gyeongbuk/포항/경상북도_포항시_포항송도해수욕장.jpg":false,
  "assets/dogam_assets/gyeongbuk/포항/경상북도_포항시_포항운하.jpg":false,
  "assets/dogam_assets/gyeongbuk/포항/경상북도_포항시_포항함.jpg":false,
  "assets/dogam_assets/gyeongbuk/포항/경상북도_포항시_하옥계곡.jpg":false,
  "assets/dogam_assets/gyeongbuk/포항/경상북도_포항시_호미곶 해맞이광장.jpg":false,
  "assets/dogam_assets/gyeongbuk/포항/경상북도_포항시_호미곶.jpg":false,
  "assets/dogam_assets/gyeongbuk/포항/경상북도_포항시_환호공원 스페이스워크.jpg":false,
  "assets/dogam_assets/gyeongbuk/포항/경상북도_포항시_환호공원.jpg":false,
};
List <String> url_pohang_List=[
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
];