Map<String,bool> Imagemap_seosan = {
  "assets/dogam_assets/chungnam/서산/충청남도_서산시_간월암.jpg":false,
  "assets/dogam_assets/chungnam/서산/충청남도_서산시_개심사(開心寺).jpg":false,
  "assets/dogam_assets/chungnam/서산/충청남도_서산시_내아.jpg":false,
  "assets/dogam_assets/chungnam/서산/충청남도_서산시_망일사.jpg":false,
  "assets/dogam_assets/chungnam/서산/충청남도_서산시_문수사(文殊寺).jpg":false,
  "assets/dogam_assets/chungnam/서산/충청남도_서산시_서산 보원사지.jpg":false,
  "assets/dogam_assets/chungnam/서산/충청남도_서산시_서산 용현리 마애여래삼존상.jpg":false,
  "assets/dogam_assets/chungnam/서산/충청남도_서산시_서산동부전통시장.jpg":false,
  "assets/dogam_assets/chungnam/서산/충청남도_서산시_서산버드랜드.jpg":false,
  "assets/dogam_assets/chungnam/서산/충청남도_서산시_서산아라메 1코스.jpg":false,
  "assets/dogam_assets/chungnam/서산/충청남도_서산시_용비지.jpg":false,
  "assets/dogam_assets/chungnam/서산/충청남도_서산시_용유지(용비저수지).jpg":false,
  "assets/dogam_assets/chungnam/서산/충청남도_서산시_천수만.jpg":false,
  "assets/dogam_assets/chungnam/서산/충청남도_서산시_해미읍성.jpg":false,
};

List <String> url_seosan_List=[
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
];