Map<String,bool> Imagemap_busan = {
  "assets/dogam_assets/gwangyeok/부산/광역시_부산_감천문화마을.jpg":false,
  "assets/dogam_assets/gwangyeok/부산/광역시_부산_태종대.jpg":false,
  "assets/dogam_assets/gwangyeok/부산/광역시_부산_용두산공원.jpg":false,
  "assets/dogam_assets/gwangyeok/부산/광역시_부산_다이아몬드타워 (부산타워).jpg":false,
  "assets/dogam_assets/gwangyeok/부산/광역시_부산_오륙도 스카이워크.jpg":false,
  "assets/dogam_assets/gwangyeok/부산/광역시_부산_BIFF광장.jpg":false,
  "assets/dogam_assets/gwangyeok/부산/광역시_부산_청사포 다릿돌전망대.jpg":false,
  "assets/dogam_assets/gwangyeok/부산/광역시_부산_초량 이바구길.jpg":false,
  "assets/dogam_assets/gwangyeok/부산/광역시_부산_흰여울문화마을.jpg":false,
  "assets/dogam_assets/gwangyeok/부산/광역시_부산_해동용궁사.jpg":false,
  "assets/dogam_assets/gwangyeok/부산/광역시_부산_국제시장.jpg":false,
  "assets/dogam_assets/gwangyeok/부산/광역시_부산_168계단.jpg":false,
  "assets/dogam_assets/gwangyeok/부산/광역시_부산_아미산 전망대.jpg":false,
  "assets/dogam_assets/gwangyeok/부산/광역시_부산_광안대교.jpg":false,
};


List <String> url_busan_List=[
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
];