Map<String,bool> Imagemap_yeoju = {
  "assets/dogam_assets/Gyeonggi/여주/경기도_여주시_강천섬 유원지.jpg":false,
  "assets/dogam_assets/Gyeonggi/여주/경기도_여주시_문바위계곡.jpg":false,
  "assets/dogam_assets/Gyeonggi/여주/경기도_여주시_밀머리체험마을.jpg":false,
  "assets/dogam_assets/Gyeonggi/여주/경기도_여주시_세종국악당.jpg":false,
  "assets/dogam_assets/Gyeonggi/여주/경기도_여주시_세종대왕릉, 영릉.jpg":false,
  "assets/dogam_assets/Gyeonggi/여주/경기도_여주시_신륵사 국민관광지.jpg":false,
  "assets/dogam_assets/Gyeonggi/여주/경기도_여주시_여주 황학산 수목원.jpg":false,
  "assets/dogam_assets/Gyeonggi/여주/경기도_여주시_여주박물관.jpg":false,
  "assets/dogam_assets/Gyeonggi/여주/경기도_여주시_영월근린공원.jpg":false,
  "assets/dogam_assets/Gyeonggi/여주/경기도_여주시_영월루.jpg":false,
  "assets/dogam_assets/Gyeonggi/여주/경기도_여주시_이포나루.jpg":false,
  "assets/dogam_assets/Gyeonggi/여주/경기도_여주시_이포보.jpg":false,
  "assets/dogam_assets/Gyeonggi/여주/경기도_여주시_파사성지.jpg":false,
  "assets/dogam_assets/Gyeonggi/여주/경기도_여주시_여주 신륵사 조사당.jpg":false,
};

List <String> url_yeoju_List=[
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "", 
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
];