Map<String,bool> Imagemap_taebaek = {
  "assets/dogam_assets/Gangwon/태백/강원도_태백시_365세이프타운.jpg":false,
  "assets/dogam_assets/Gangwon/태백/강원도_태백시_검룡소(儉龍沼) - 한강의 발원지.jpg":false,
  "assets/dogam_assets/Gangwon/태백/강원도_태백시_구문소.jpg":false,
  "assets/dogam_assets/Gangwon/태백/강원도_태백시_매봉산.jpg":false,
  "assets/dogam_assets/Gangwon/태백/강원도_태백시_바람의 언덕.jpg":false,
  "assets/dogam_assets/Gangwon/태백/강원도_태백시_철암 탄광역사촌.jpg":false,
  "assets/dogam_assets/Gangwon/태백/강원도_태백시_태백 용연굴.jpg":false,
  "assets/dogam_assets/Gangwon/태백/강원도_태백시_태백고생대자연사박물관.jpg":false,
  "assets/dogam_assets/Gangwon/태백/강원도_태백시_태백산국립공원.jpg":false,
  "assets/dogam_assets/Gangwon/태백/강원도_태백시_태백석탄박물관.jpg":false,
  "assets/dogam_assets/Gangwon/태백/강원도_태백시_태백체험공원.jpg":false,
  "assets/dogam_assets/Gangwon/태백/강원도_태백시_태양의후예 촬영장.jpg":false,
  "assets/dogam_assets/Gangwon/태백/강원도_태백시_통리탄탄파크.jpg":false,
  "assets/dogam_assets/Gangwon/태백/강원도_태백시_황지자유시장.jpg":false,
};

List <String> url_taebaek_List=[
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
];