Map<String,bool> Imagemap_taean = {
  "assets/dogam_assets/chungnam/태안/충청남도_태안군_만리포 해수욕장.jpg":false,
  "assets/dogam_assets/chungnam/태안/충청남도_태안군_만리포전망타워.jpg":false,
  "assets/dogam_assets/chungnam/태안/충청남도_태안군_솔향기길 1코스.jpg":false,
  "assets/dogam_assets/chungnam/태안/충청남도_태안군_신두리해수욕장.jpg":false,
  "assets/dogam_assets/chungnam/태안/충청남도_태안군_안면도 자연휴양림.jpg":false,
  "assets/dogam_assets/chungnam/태안/충청남도_태안군_안면송림.jpg":false,
  "assets/dogam_assets/chungnam/태안/충청남도_태안군_용난굴.jpg":false,
  "assets/dogam_assets/chungnam/태안/충청남도_태안군_천리포수목원.jpg":false,
  "assets/dogam_assets/chungnam/태안/충청남도_태안군_청포대해수욕장.jpg":false,
  "assets/dogam_assets/chungnam/태안/충청남도_태안군_태안 방포항.jpg":false,
  "assets/dogam_assets/chungnam/태안/충청남도_태안군_태안 별주부마을.jpg":false,
  "assets/dogam_assets/chungnam/태안/충청남도_태안군_태안 신두리 해안사구.jpg":false,
  "assets/dogam_assets/chungnam/태안/충청남도_태안군_파도리 해식동굴.jpg":false,
  "assets/dogam_assets/chungnam/태안/충청남도_태안군_할미할아비바위.jpg":false,
};


List <String> url_taean_List=[
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
];