Map<String,bool> Imagemap_gimjae = {
  "assets/dogam_assets/Jeonbuk/김제/전라북도_김제시_귀신사.jpg":false,
  "assets/dogam_assets/Jeonbuk/김제/전라북도_김제시_금산사.jpg":false,
  "assets/dogam_assets/Jeonbuk/김제/전라북도_김제시_김제 금산사 미륵전.jpg":false,
  "assets/dogam_assets/Jeonbuk/김제/전라북도_김제시_김제 메타세콰이어길.jpg":false,
  "assets/dogam_assets/Jeonbuk/김제/전라북도_김제시_맛집.jpg":false,
  "assets/dogam_assets/Jeonbuk/김제/전라북도_김제시_망해사.jpg":false,
  "assets/dogam_assets/Jeonbuk/김제/전라북도_김제시_모악산도립공원.jpg":false,
  "assets/dogam_assets/Jeonbuk/김제/전라북도_김제시_백산관망대.jpg":false,
  "assets/dogam_assets/Jeonbuk/김제/전라북도_김제시_벽골제.jpg":false,
  "assets/dogam_assets/Jeonbuk/김제/전라북도_김제시_상가.jpg":false,
  "assets/dogam_assets/Jeonbuk/김제/전라북도_김제시_성산공원.jpg":false,
  "assets/dogam_assets/Jeonbuk/김제/전라북도_김제시_신털미산.jpg":false,
  "assets/dogam_assets/Jeonbuk/김제/전라북도_김제시_천주교 수류 성당.jpg":false,
  "assets/dogam_assets/Jeonbuk/김제/전라북도_김제시_펜션.jpg":false,
};

List <String> url_gimjae_List=[
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
];