Map<String,bool> Imagemap_chilgok = {
  "assets/dogam_assets/gyeongbuk/칠곡/경상북도_칠곡군_가산바위.jpg":false,
  "assets/dogam_assets/gyeongbuk/칠곡/경상북도_칠곡군_가산산성.jpg":false,
  "assets/dogam_assets/gyeongbuk/칠곡/경상북도_칠곡군_강나루체육공원.jpg":false,
  "assets/dogam_assets/gyeongbuk/칠곡/경상북도_칠곡군_관호산성.jpg":false,
  "assets/dogam_assets/gyeongbuk/칠곡/경상북도_칠곡군_금화계곡.jpg":false,
  "assets/dogam_assets/gyeongbuk/칠곡/경상북도_칠곡군_대둔사.jpg":false,
  "assets/dogam_assets/gyeongbuk/칠곡/경상북도_칠곡군_성 베네딕도회 왜관 수도원.jpg":false,
  "assets/dogam_assets/gyeongbuk/칠곡/경상북도_칠곡군_세아수목원휴양림.jpg":false,
  "assets/dogam_assets/gyeongbuk/칠곡/경상북도_칠곡군_송림사(松林寺).jpg":false,
  "assets/dogam_assets/gyeongbuk/칠곡/경상북도_칠곡군_송정자연휴양림.jpg":false,
  "assets/dogam_assets/gyeongbuk/칠곡/경상북도_칠곡군_왜관철교.jpg":false,
  "assets/dogam_assets/gyeongbuk/칠곡/경상북도_칠곡군_칠곡보 생태공원.jpg":false,
  "assets/dogam_assets/gyeongbuk/칠곡/경상북도_칠곡군_칠곡평화분수.jpg":false,
  "assets/dogam_assets/gyeongbuk/칠곡/경상북도_칠곡군_칠곡호국평화기념관.jpg":false,
};
List <String> url_chilgok_List=[
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
];