Map<String,bool> Imagemap_incheon = {
  "assets/dogam_assets/gwangyeok/인천/광역시_인천_G-타워 인천경제자유구역(IFEZ) 청사.jpg":false,
  "assets/dogam_assets/gwangyeok/인천/광역시_인천_강화 평화전망대.jpg":false,
  "assets/dogam_assets/gwangyeok/인천/광역시_인천_소무의도.jpg":false,
  "assets/dogam_assets/gwangyeok/인천/광역시_인천_송도 센트럴파크.jpg":false,
  "assets/dogam_assets/gwangyeok/인천/광역시_인천_송월동 동화마을.jpg":false,
  "assets/dogam_assets/gwangyeok/인천/광역시_인천_수도국산 달동네박물관.jpg":false,
  "assets/dogam_assets/gwangyeok/인천/광역시_인천_월미공원.jpg":false,
  "assets/dogam_assets/gwangyeok/인천/광역시_인천_월미도.jpg":false,
  "assets/dogam_assets/gwangyeok/인천/광역시_인천_인천 차이나타운.jpg":false,
  "assets/dogam_assets/gwangyeok/인천/광역시_인천_인천대공원.jpg":false,
  "assets/dogam_assets/gwangyeok/인천/광역시_인천_인천대교기념관.jpg":false,
  "assets/dogam_assets/gwangyeok/인천/광역시_인천_인천상륙작전기념관.jpg":false,
  "assets/dogam_assets/gwangyeok/인천/광역시_인천_자유공원.jpg":false,
  "assets/dogam_assets/gwangyeok/인천/광역시_인천_정서진.jpg":false,
};
List <String> url_incheon_List=[
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
];