Map<String,bool> Imagemap_gunwi = {
  "assets/dogam_assets/gyeongbuk/군위/경상북도_군위군_경북대학교 자연사박물관.jpg":false,
  "assets/dogam_assets/gyeongbuk/군위/경상북도_군위군_군위 아미타여래삼존 석굴.jpg":false,
  "assets/dogam_assets/gyeongbuk/군위/경상북도_군위군_군위상매댁.jpg":false,
  "assets/dogam_assets/gyeongbuk/군위/경상북도_군위군_김수환 추기경 사랑과 나눔공원.jpg":false,
  "assets/dogam_assets/gyeongbuk/군위/경상북도_군위군_동산계곡.jpg":false,
  "assets/dogam_assets/gyeongbuk/군위/경상북도_군위군_리틀포레스트 촬영지.jpg":false,
  "assets/dogam_assets/gyeongbuk/군위/경상북도_군위군_사라온 이야기마을.jpg":false,
  "assets/dogam_assets/gyeongbuk/군위/경상북도_군위군_압곡사.jpg":false,
  "assets/dogam_assets/gyeongbuk/군위/경상북도_군위군_인각사.jpg":false,
  "assets/dogam_assets/gyeongbuk/군위/경상북도_군위군_일연공원.jpg":false,
  "assets/dogam_assets/gyeongbuk/군위/경상북도_군위군_장곡자연휴양림.jpg":false,
  "assets/dogam_assets/gyeongbuk/군위/경상북도_군위군_팔공산 하늘정원.jpg":false,
  "assets/dogam_assets/gyeongbuk/군위/경상북도_군위군_화산마을.jpg":false,
  "assets/dogam_assets/gyeongbuk/군위/경상북도_군위군_화산산성.jpg":false,
};
List <String> url_gunwi_List=[
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
];