Map<String,bool> Imagemap_gwangyang = {
  "assets/dogam_assets/Jeonnam/광양/전라남도_광양시_관동마을.jpg":false,
  "assets/dogam_assets/Jeonnam/광양/전라남도_광양시_광양 옥룡사지.jpg":false,
  "assets/dogam_assets/Jeonnam/광양/전라남도_광양시_광양매화마을.jpg":false,
  "assets/dogam_assets/Jeonnam/광양/전라남도_광양시_광양매화문화관.jpg":false,
  "assets/dogam_assets/Jeonnam/광양/전라남도_광양시_광양매화축제.jpg":false,
  "assets/dogam_assets/Jeonnam/광양/전라남도_광양시_광양옥룡사지일원.jpg":false,
  "assets/dogam_assets/Jeonnam/광양/전라남도_광양시_광양와인동굴.jpg":false,
  "assets/dogam_assets/Jeonnam/광양/전라남도_광양시_구봉산 전망대.jpg":false,
  "assets/dogam_assets/Jeonnam/광양/전라남도_광양시_구시폭포.jpg":false,
  "assets/dogam_assets/Jeonnam/광양/전라남도_광양시_마동저수지 생태공원.jpg":false,
  "assets/dogam_assets/Jeonnam/광양/전라남도_광양시_망덕포구.jpg":false,
  "assets/dogam_assets/Jeonnam/광양/전라남도_광양시_배알도수변공원.jpg":false,
  "assets/dogam_assets/Jeonnam/광양/전라남도_광양시_섬진강.jpg":false,
  "assets/dogam_assets/Jeonnam/광양/전라남도_광양시_유당공원.jpg":false,
};
List <String> url_gwangyang_List=[
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
];