Map<String,bool> Imagemap_hanam = {
  "assets/dogam_assets/Gyeonggi/하남/경기도_하남시_하남역사박물관.jpg":false,
  "assets/dogam_assets/Gyeonggi/하남/경기도_하남시_하남나무고아원.jpg":false,
  "assets/dogam_assets/Gyeonggi/하남/경기도_하남시_미사경정공원.jpg":false,
  "assets/dogam_assets/Gyeonggi/하남/경기도_하남시_유니온타워.jpg":false,
  "assets/dogam_assets/Gyeonggi/하남/경기도_하남시_하남 유니온파크.jpg":false,
  "assets/dogam_assets/Gyeonggi/하남/경기도_하남시_하남 이성산성.jpg":false,
  "assets/dogam_assets/Gyeonggi/하남/경기도_하남시_아쿠아필드 하남.jpg":false,
};
List <String> url_hanam_List=[
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "", 
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
];