Map<String,bool> Imagemap_hanam = {
  "assets/dogam_assets/Gyeonggi/하남/경기도_하남시_곱돌광산약수터.jpg":false,
  "assets/dogam_assets/Gyeonggi/하남/경기도_하남시_미사경정공원.jpg":false,
  "assets/dogam_assets/Gyeonggi/하남/경기도_하남시_미사리유원지.jpg":false,
  "assets/dogam_assets/Gyeonggi/하남/경기도_하남시_아쿠아필드 하남.jpg":false,
  "assets/dogam_assets/Gyeonggi/하남/경기도_하남시_유니온타워.jpg":false,
  "assets/dogam_assets/Gyeonggi/하남/경기도_하남시_천주교 구산 순교 성지.jpg":false,
  "assets/dogam_assets/Gyeonggi/하남/경기도_하남시_팔당대교.jpg":false,
  "assets/dogam_assets/Gyeonggi/하남/경기도_하남시_하남 동사지.jpg":false,
  "assets/dogam_assets/Gyeonggi/하남/경기도_하남시_하남 미사리 유적.jpg":false,
  "assets/dogam_assets/Gyeonggi/하남/경기도_하남시_하남 유니온파크.jpg":false,
  "assets/dogam_assets/Gyeonggi/하남/경기도_하남시_하남 이성산성.jpg":false,
  "assets/dogam_assets/Gyeonggi/하남/경기도_하남시_하남나무고아원.jpg":false,
  "assets/dogam_assets/Gyeonggi/하남/경기도_하남시_하남역사박물관.jpg":false,
  "assets/dogam_assets/Gyeonggi/하남/경기도_하남시_하남위례길.jpg":false,
};
List <String> url_hanam_List=[
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "", 
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
];