Map<String,bool> Imagemap_uijeongbu = {
  "assets/dogam_assets/Gyeonggi/의정부/경기도_의정부시_망월사.jpg":false,
  "assets/dogam_assets/Gyeonggi/의정부/경기도_의정부시_백석천근린공원.jpg":false,
  "assets/dogam_assets/Gyeonggi/의정부/경기도_의정부시_북한산도봉 탐방지원센터(원도봉).jpg":false,
  "assets/dogam_assets/Gyeonggi/의정부/경기도_의정부시_북한산도봉 탐방지원센터(회룡).jpg":false,
  "assets/dogam_assets/Gyeonggi/의정부/경기도_의정부시_서계 박세당 사랑채.jpg":false,
  "assets/dogam_assets/Gyeonggi/의정부/경기도_의정부시_석림사.jpg":false,
  "assets/dogam_assets/Gyeonggi/의정부/경기도_의정부시_신숙주선생묘.jpg":false,
  "assets/dogam_assets/Gyeonggi/의정부/경기도_의정부시_안골계곡.jpg":false,
  "assets/dogam_assets/Gyeonggi/의정부/경기도_의정부시_원도봉유원지.jpg":false,
  "assets/dogam_assets/Gyeonggi/의정부/경기도_의정부시_직동근린공원.jpg":false,
  "assets/dogam_assets/Gyeonggi/의정부/경기도_의정부시_천보산 약수터.jpg":false,
  "assets/dogam_assets/Gyeonggi/의정부/경기도_의정부시_천주교 주교좌 의정부 성당.jpg":false,
  "assets/dogam_assets/Gyeonggi/의정부/경기도_의정부시_하늘전망대.jpg":false,
  "assets/dogam_assets/Gyeonggi/의정부/경기도_의정부시_회룡사.jpg":false,
};

List <String> url_uijeongbu_List=[
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "", 
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
];