Map<String,bool> Imagemap_jinan = {
  "assets/dogam_assets/Jeonbuk/진안/전라북도_진안군_꽃잔디동산.jpg":false,
  "assets/dogam_assets/Jeonbuk/진안/전라북도_진안군_마이산 돌탑.jpg":false,
  "assets/dogam_assets/Jeonbuk/진안/전라북도_진안군_데미샘.jpg":false,
  "assets/dogam_assets/Jeonbuk/진안/전라북도_진안군_마이산 등산로.jpg":false,
  "assets/dogam_assets/Jeonbuk/진안/전라북도_진안군_마이산도립공원.jpg":false,
  "assets/dogam_assets/Jeonbuk/진안/전라북도_진안군_마이산전망대.jpg":false,
  "assets/dogam_assets/Jeonbuk/진안/전라북도_진안군_백운동계곡.jpg":false,
  "assets/dogam_assets/Jeonbuk/진안/전라북도_진안군_부귀 메타세쿼이아 길.jpg":false,
  "assets/dogam_assets/Jeonbuk/진안/전라북도_진안군_사양제.jpg":false,
  "assets/dogam_assets/Jeonbuk/진안/전라북도_진안군_숫마이봉.jpg":false,
  "assets/dogam_assets/Jeonbuk/진안/전라북도_진안군_암마이봉.jpg":false,
  "assets/dogam_assets/Jeonbuk/진안/전라북도_진안군_와룡암.jpg":false,
  "assets/dogam_assets/Jeonbuk/진안/전라북도_진안군_진안 은수사 청실배나무.jpg":false,
  "assets/dogam_assets/Jeonbuk/진안/전라북도_진안군_진안시장.jpg":false,
};

List <String> url_jinan_List=[
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
];