Map<String,bool> Imagemap_changwon = {
  "경상남도_창원시_경남 창원시 의창구 동읍 메타세콰이어 길.jpg":false,
  "경상남도_창원시_비음산.jpg":false,
  "경상남도_창원시_비치로드.jpg":false,
  "경상남도_창원시_상남분수광장.jpg":false,
  "경상남도_창원시_여좌천.jpg":false,
  "경상남도_창원시_장미공원.jpg":false,
  "경상남도_창원시_저도스카이워크.jpg":false,
  "경상남도_창원시_주남저수지.jpg":false,
  "경상남도_창원시_진해루.jpg":false,
  "경상남도_창원시_창동예술촌.jpg":false,
  "경상남도_창원시_창원 가로수길.jpg":false,
  "경상남도_창원시_창원 중앙동 거리.jpg":false,
  "경상남도_창원시_창원시립마산박물관.jpg":false,
  "경상남도_창원시_해양드라마 세트장.jpg":false,
};

List <String> url_changwon_List=[
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
];