Map<String,bool> Imagemap_muju = {
  "assets/dogam_assets/Jeonbuk/무주/전라북도_무주군_구천동.jpg":false,
  "assets/dogam_assets/Jeonbuk/무주/전라북도_무주군_라제통문.jpg":false,
  "assets/dogam_assets/Jeonbuk/무주/전라북도_무주군_무주 머루와인.jpg":false,
  "assets/dogam_assets/Jeonbuk/무주/전라북도_무주군_무주 반딧불이.jpg":false,
  "assets/dogam_assets/Jeonbuk/무주/전라북도_무주군_무주 한풍루.jpg":false,
  "assets/dogam_assets/Jeonbuk/무주/전라북도_무주군_무주곤충박물관.jpg":false,
  "assets/dogam_assets/Jeonbuk/무주/전라북도_무주군_무주구천동계곡.jpg":false,
  "assets/dogam_assets/Jeonbuk/무주/전라북도_무주군_무주구천동관광단지.jpg":false,
  "assets/dogam_assets/Jeonbuk/무주/전라북도_무주군_무주문화관광.jpg":false,
  "assets/dogam_assets/Jeonbuk/무주/전라북도_무주군_무주반디랜드 관광안내소.jpg":false,
  "assets/dogam_assets/Jeonbuk/무주/전라북도_무주군_안국사.jpg":false,
  "assets/dogam_assets/Jeonbuk/무주/전라북도_무주군_지전마을돌담길.jpg":false,
  "assets/dogam_assets/Jeonbuk/무주/전라북도_무주군_천일폭포.jpg":false,
  "assets/dogam_assets/Jeonbuk/무주/전라북도_무주군_칠연계곡.jpg":false,
};

List <String> url_muju_List=[
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
];