Map<String,bool> Imagemap_gujae = {
  "assets/dogam_assets/gyeongnam/거제/경상남도_거제시_거제 관광모노레일.jpg":false,
  "assets/dogam_assets/gyeongnam/거제/경상남도_거제시_거제맹종죽테마파크.jpg":false,
  "assets/dogam_assets/gyeongnam/거제/경상남도_거제시_거제씨월드.jpg":false,
  "assets/dogam_assets/gyeongnam/거제/경상남도_거제시_거제자연예술랜드.jpg":false,
  "assets/dogam_assets/gyeongnam/거제/경상남도_거제시_거제장목관광단지.jpg":false,
  "assets/dogam_assets/gyeongnam/거제/경상남도_거제시_구조라 해수욕장.jpg":false,
  "assets/dogam_assets/gyeongnam/거제/경상남도_거제시_국사봉.jpg":false,
  "assets/dogam_assets/gyeongnam/거제/경상남도_거제시_다대 어촌체험마을.jpg":false,
  "assets/dogam_assets/gyeongnam/거제/경상남도_거제시_매미성.jpg":false,
  "assets/dogam_assets/gyeongnam/거제/경상남도_거제시_바람의 언덕.jpg":false,
  "assets/dogam_assets/gyeongnam/거제/경상남도_거제시_신선대 전망대.jpg":false,
  "assets/dogam_assets/gyeongnam/거제/경상남도_거제시_외도 보타니아.jpg":false,
  "assets/dogam_assets/gyeongnam/거제/경상남도_거제시_해안거님길.jpg":false,
  "assets/dogam_assets/gyeongnam/거제/경상남도_거제시_홍포전망대.jpg":false,
};

List <String> url_gujae_List=[
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
];