Map<String,bool> Imagemap_imsil = {
  "assets/dogam_assets/Jeonbuk/임실/전라북도_임실군_국사봉전망대.jpg":false,
  "assets/dogam_assets/Jeonbuk/임실/전라북도_임실군_붕어섬.jpg":false,
  "assets/dogam_assets/Jeonbuk/임실/전라북도_임실군_사선대관광지.jpg":false,
  "assets/dogam_assets/Jeonbuk/임실/전라북도_임실군_세심자연휴양림.jpg":false,
  "assets/dogam_assets/Jeonbuk/임실/전라북도_임실군_오수의견공원.jpg":false,
  "assets/dogam_assets/Jeonbuk/임실/전라북도_임실군_옥정호.jpg":false,
  "assets/dogam_assets/Jeonbuk/임실/전라북도_임실군_왜가리서식지.jpg":false,
  "assets/dogam_assets/Jeonbuk/임실/전라북도_임실군_요산공원.jpg":false,
  "assets/dogam_assets/Jeonbuk/임실/전라북도_임실군_임실 상이암 부도.jpg":false,
  "assets/dogam_assets/Jeonbuk/임실/전라북도_임실군_임실 이도리 미륵불상.jpg":false,
  "assets/dogam_assets/Jeonbuk/임실/전라북도_임실군_임실 진구사지 석등.jpg":false,
  "assets/dogam_assets/Jeonbuk/임실/전라북도_임실군_임실오수망루.jpg":false,
  "assets/dogam_assets/Jeonbuk/임실/전라북도_임실군_임실치즈마을.jpg":false,
  "assets/dogam_assets/Jeonbuk/임실/전라북도_임실군_임실치즈테마파크.jpg":false,
};

List <String> url_imsil_List=[
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
];