Map<String,bool> Imagemap_gumi = {
  "assets/dogam_assets/gyeongbuk/구미/경상북도_구미시_구미 에코랜드.jpg":false,
  "assets/dogam_assets/gyeongbuk/구미/경상북도_구미시_구미과학관.jpg":false,
  "assets/dogam_assets/gyeongbuk/구미/경상북도_구미시_구미정.jpg":false,
  "assets/dogam_assets/gyeongbuk/구미/경상북도_구미시_금오랜드.jpg":false,
  "assets/dogam_assets/gyeongbuk/구미/경상북도_구미시_금오산도립공원.jpg":false,
  "assets/dogam_assets/gyeongbuk/구미/경상북도_구미시_대혜폭포.jpg":false,
  "assets/dogam_assets/gyeongbuk/구미/경상북도_구미시_도리사.jpg":false,
  "assets/dogam_assets/gyeongbuk/구미/경상북도_구미시_도선굴.jpg":false,
  "assets/dogam_assets/gyeongbuk/구미/경상북도_구미시_동락공원.jpg":false,
  "assets/dogam_assets/gyeongbuk/구미/경상북도_구미시_수다사.jpg":false,
  "assets/dogam_assets/gyeongbuk/구미/경상북도_구미시_약사암.jpg":false,
  "assets/dogam_assets/gyeongbuk/구미/경상북도_구미시_옥성자연휴양림.jpg":false,
  "assets/dogam_assets/gyeongbuk/구미/경상북도_구미시_채미정.jpg":false,
  "assets/dogam_assets/gyeongbuk/구미/경상북도_구미시_해운사.jpg":false,
};
List <String> url_gumi_List=[
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
];