
String gangwon="assets/csv_assets/강원도/강원도_";
String gyeonggi="assets/csv_assets/경기도/경기도_";
String gyeongnam="assets/csv_assets/경상남도/경상남도_";
String gyeongbuk="assets/csv_assets/경상북도/경상북도_";
String gwangyeoksi="assets/csv_assets/광역시/광역시_";
String jeonnam="assets/csv_assets/전라남도/전라남도_";
String jeonbuk="assets/csv_assets/전라북도/전라북도_";
String chungnam="assets/csv_assets/충청남도/충청남도_";
String chungbuk="assets/csv_assets/충청북도/충청북도_";

List<List<String>> csv_List=[
  csv_gangwon_List,
  csv_gyeonggi_List,
  csv_gyeongnam_List,
  csv_gyeongbuk_List,
  csv_gwangyeoksi_List,
  csv_jeonnam_List,
  csv_jeonbuk_List,
  csv_chungnam_List,
  csv_chungbuk_List
];

List <String> csv_gangwon_List=[
  gangwon+"강릉시.csv",
  gangwon+"고성군.csv",
  gangwon+"동해시.csv",
  gangwon+"삼척시.csv",
  gangwon+"속초시.csv",
  gangwon+"양구군.csv",
  gangwon+"양양군.csv",
  gangwon+"영월군.csv",
  gangwon+"원주시.csv",
  gangwon+"인제군.csv",
  gangwon+"정선군.csv",
  gangwon+"철원군.csv",
  gangwon+"춘천시.csv",
  gangwon+"태백시.csv",
];
List <String> csv_gyeonggi_List=[
  gyeonggi+"가평군.csv",
  gyeonggi+"고양시.csv",
  gyeonggi+"과천시.csv",
  gyeonggi+"광명시.csv",
  gyeonggi+"광주시.csv",
  gyeonggi+"구리시.csv",
  gyeonggi+"군포시.csv",
  gyeonggi+"김포시.csv",
  gyeonggi+"남양주시.csv",
  gyeonggi+"동두천시.csv",
  gyeonggi+"부천시.csv",
  gyeonggi+"성남시.csv",
  gyeonggi+"수원시.csv",
  gyeonggi+"시흥시.csv",
  gyeonggi+"안산시.csv",
  gyeonggi+"안성시.csv",
  gyeonggi+"안양시.csv",
  gyeonggi+"양주시.csv",
  gyeonggi+"양평군.csv",
  gyeonggi+"여주시.csv",
  gyeonggi+"연천군.csv",
  gyeonggi+"오산시.csv",
  gyeonggi+"용인시.csv",
  gyeonggi+"의왕시.csv",
  gyeonggi+"의정부시.csv",
  gyeonggi+"이천시.csv",
  gyeonggi+"파주시.csv",
  gyeonggi+"평택시.csv",
  gyeonggi+"포천시.csv",
  gyeonggi+"하남시.csv",
  gyeonggi+"화성시.csv",
];

List <String> csv_gyeongnam_List=[
  gyeongnam+"거제시.csv",
  gyeongnam+"거창군.csv",
  gyeongnam+"고성군.csv",
  gyeongnam+"김해시.csv",
  gyeongnam+"남해군.csv",
  gyeongnam+"밀양시.csv",
  gyeongnam+"사천시.csv",
  gyeongnam+"산청군.csv",
  gyeongnam+"양산시.csv",
  gyeongnam+"의령군.csv",
  gyeongnam+"진주시.csv",
  gyeongnam+"창녕군.csv",
  gyeongnam+"창원시.csv",
  gyeongnam+"통영시.csv",
  gyeongnam+"하동군.csv",
  gyeongnam+"함안군.csv",
  gyeongnam+"함양군.csv",
  gyeongnam+"합천군.csv",
];

List <String> csv_gyeongbuk_List=[
  gyeongbuk+"경산시.csv",
  gyeongbuk+"경주시.csv",
  gyeongbuk+"고령군.csv",
  gyeongbuk+"구미시.csv",
  gyeongbuk+"군위군.csv",
  gyeongbuk+"김천시.csv",
  gyeongbuk+"문경시.csv",
  gyeongbuk+"봉화군.csv",
  gyeongbuk+"상주시.csv",
  gyeongbuk+"성주군.csv",
  gyeongbuk+"안동시.csv",
  gyeongbuk+"영덕군.csv",
  gyeongbuk+"영양군.csv",
  gyeongbuk+"영주시.csv",
  gyeongbuk+"영천시.csv",
  gyeongbuk+"예천군.csv",
  gyeongbuk+"울릉군.csv",
  gyeongbuk+"울진군.csv",
  gyeongbuk+"의성군.csv",
  gyeongbuk+"청도군.csv",
  gyeongbuk+"청송군.csv",
  gyeongbuk+"칠곡군.csv",
  gyeongbuk+"포항시.csv",
];

List <String> csv_gwangyeoksi_List=[
  gwangyeoksi+"광주.csv",
  gwangyeoksi+"대구.csv",
  gwangyeoksi+"대전.csv",
  gwangyeoksi+"부산.csv",
  gwangyeoksi+"서울.csv",
  gwangyeoksi+"세종.csv",
  gwangyeoksi+"울산.csv",
  gwangyeoksi+"인천.csv",
  gwangyeoksi+"제주.csv",
];

List <String> csv_jeonnam_List=[
  jeonnam+"강진군.csv",
  jeonnam+"고흥군.csv",
  jeonnam+"곡성군.csv",
  jeonnam+"광양시.csv",
  jeonnam+"구례군.csv",
  jeonnam+"나주시.csv",
  jeonnam+"담양군.csv",
  jeonnam+"목포시.csv",
  jeonnam+"무안군.csv",
  jeonnam+"보성군.csv",
  jeonnam+"순천시.csv",
  jeonnam+"신안군.csv",
  jeonnam+"여수시.csv",
  jeonnam+"영광군.csv",
  jeonnam+"영암군.csv",
  jeonnam+"완도군.csv",
  jeonnam+"장성군.csv",
  jeonnam+"장흥군.csv",
  jeonnam+"진도군.csv",
  jeonnam+"함평군.csv",
  jeonnam+"해남군.csv",
  jeonnam+"화순군.csv",
];

List <String> csv_jeonbuk_List=[
  jeonbuk+"고창군.csv",
  jeonbuk+"군산시.csv",
  jeonbuk+"김제시.csv",
  jeonbuk+"남원시.csv",
  jeonbuk+"무주군.csv",
  jeonbuk+"부안군.csv",
  jeonbuk+"순창군.csv",
  jeonbuk+"완주군.csv",
  jeonbuk+"익산시.csv",
  jeonbuk+"임실군.csv",
  jeonbuk+"장수군.csv",
  jeonbuk+"전주시.csv",
  jeonbuk+"정읍시.csv",
  jeonbuk+"진안군.csv",
];

List <String> csv_chungnam_List=[
  chungnam+"계룡시.csv",
  chungnam+"공주시.csv",
  chungnam+"금산군.csv",
  chungnam+"논산시.csv",
  chungnam+"당진시.csv",
  chungnam+"보령시.csv",
  chungnam+"부여군.csv",
  chungnam+"서산시.csv",
  chungnam+"서천군.csv",
  chungnam+"아산시.csv",
  chungnam+"예산군.csv",
  chungnam+"천안시.csv",
  chungnam+"청양군.csv",
  chungnam+"태안군.csv",
  chungnam+"홍성군.csv",
];

List <String> csv_chungbuk_List=[
  "assets/csv_assets/충청북도/충청북도_괴산군.csv",
  "assets/csv_assets/충청북도/충청북도_단양군.csv",
  "assets/csv_assets/충청북도/충청북도_보은군.csv",
  "assets/csv_assets/충청북도/충청북도_영동군.csv",
  "assets/csv_assets/충청북도/충청북도_옥천군.csv",
  "assets/csv_assets/충청북도/충청북도_음성군.csv",
  "assets/csv_assets/충청북도/충청북도_제천시.csv",
  "assets/csv_assets/충청북도/충청북도_증평군.csv",
  "assets/csv_assets/충청북도/충청북도_진천군.csv",
  "assets/csv_assets/충청북도/충청북도_청주시.csv",
  "assets/csv_assets/충청북도/충청북도_충주시.csv",
];