Map<String,bool> Imagemap_seongnam = {
  "assets/dogam_assets/Gyeonggi/성남/경기도_성남시_남한산성유원지.jpg":false,
  "assets/dogam_assets/Gyeonggi/성남/경기도_성남시_대원공원.jpg":false,
  "assets/dogam_assets/Gyeonggi/성남/경기도_성남시_망경암.jpg":false,
  "assets/dogam_assets/Gyeonggi/성남/경기도_성남시_백현동 카페거리.jpg":false,
  "assets/dogam_assets/Gyeonggi/성남/경기도_성남시_수내동 가옥.jpg":false,
  "assets/dogam_assets/Gyeonggi/성남/경기도_성남시_수진공원.jpg":false,
  "assets/dogam_assets/Gyeonggi/성남/경기도_성남시_신구대학교 식물원.jpg":false,
  "assets/dogam_assets/Gyeonggi/성남/경기도_성남시_위례중앙광장.jpg":false,
  "assets/dogam_assets/Gyeonggi/성남/경기도_성남시_율동공원.jpg":false,
  "assets/dogam_assets/Gyeonggi/성남/경기도_성남시_은행식물원.jpg":false,
  "assets/dogam_assets/Gyeonggi/성남/경기도_성남시_중앙공원.jpg":false,
  "assets/dogam_assets/Gyeonggi/성남/경기도_성남시_판교박물관.jpg":false,
  "assets/dogam_assets/Gyeonggi/성남/경기도_성남시_화랑공원.jpg":false,
  "assets/dogam_assets/Gyeonggi/성남/경기도_성남시_희망대공원.jpg":false,
};
List <String> url_seongnam_List=[
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "", 
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
];