Map<String,bool> Imagemap_yangyang = {
  "assets/dogam_assets/Gangwon/양양/강원도_양양군_낙산도립공원.jpg":false,
  "assets/dogam_assets/Gangwon/양양/강원도_양양군_낙산사.jpg":false,
  "assets/dogam_assets/Gangwon/양양/강원도_양양군_둔전계곡.jpg":false,
  "assets/dogam_assets/Gangwon/양양/강원도_양양군_모노골산림욕장.jpg":false,
  "assets/dogam_assets/Gangwon/양양/강원도_양양군_법수치계곡.jpg":false,
  "assets/dogam_assets/Gangwon/양양/강원도_양양군_송천떡마을영농조합법인.jpg":false,
  "assets/dogam_assets/Gangwon/양양/강원도_양양군_양양.jpg":false,
  "assets/dogam_assets/Gangwon/양양/강원도_양양군_오산리 선사유적박물관 ( Osan-ri Prehistory Museum ).jpg":false,
  "assets/dogam_assets/Gangwon/양양/강원도_양양군_오색약수터.jpg":false,
  "assets/dogam_assets/Gangwon/양양/강원도_양양군_의상대(義湘臺).jpg":false,
  "assets/dogam_assets/Gangwon/양양/강원도_양양군_주전골.jpg":false,
  "assets/dogam_assets/Gangwon/양양/강원도_양양군_죽도해변.jpg":false,
  "assets/dogam_assets/Gangwon/양양/강원도_양양군_하조대.jpg":false,
  "assets/dogam_assets/Gangwon/양양/강원도_양양군_휴휴암.jpg":false,
};

List <String> url_yangyang_List=[
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
];