Map<String,bool> Imagemap_bucheon = {
  "assets/dogam_assets/Gyeonggi/부천/경기도_부천시_고강선사유적공원.jpg":false,
  "assets/dogam_assets/Gyeonggi/부천/경기도_부천시_남부수자원생태공원.jpg":false,
  "assets/dogam_assets/Gyeonggi/부천/경기도_부천시_도당공원(도당근린공원).jpg":false,
  "assets/dogam_assets/Gyeonggi/부천/경기도_부천시_도당근린공원 백만송이장미원.jpg":false,
  "assets/dogam_assets/Gyeonggi/부천/경기도_부천시_부천로보파크.jpg":false,
  "assets/dogam_assets/Gyeonggi/부천/경기도_부천시_부천시립박물관.jpg":false,
  "assets/dogam_assets/Gyeonggi/부천/경기도_부천시_부천시립식물원.jpg":false,
  "assets/dogam_assets/Gyeonggi/부천/경기도_부천시_부천원미공원.jpg":false,
  "assets/dogam_assets/Gyeonggi/부천/경기도_부천시_부천자연생태공원.jpg":false,
  "assets/dogam_assets/Gyeonggi/부천/경기도_부천시_부천중앙공원.jpg":false,
  "assets/dogam_assets/Gyeonggi/부천/경기도_부천시_부천한옥체험마을.jpg":false,
  "assets/dogam_assets/Gyeonggi/부천/경기도_부천시_상동호수공원.jpg":false,
  "assets/dogam_assets/Gyeonggi/부천/경기도_부천시_안중근공원.jpg":false,
  "assets/dogam_assets/Gyeonggi/부천/경기도_부천시_한국만화박물관.jpg":false,
};



List <String> url_bucheon_List=[
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "", 
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
];