Map<String,bool> Imagemap_guri = {
  "assets/dogam_assets/Gyeonggi/구리/경기도_구리시_고구려대장간마을.jpg":false,
  "assets/dogam_assets/Gyeonggi/구리/경기도_구리시_고구려정.jpg":false,
  "assets/dogam_assets/Gyeonggi/구리/경기도_구리시_구리 왕숙체육공원.jpg":false,
  "assets/dogam_assets/Gyeonggi/구리/경기도_구리시_구리시곤충생태관.jpg":false,
  "assets/dogam_assets/Gyeonggi/구리/경기도_구리시_구리암사대교.jpg":false,
  "assets/dogam_assets/Gyeonggi/구리/경기도_구리시_구리역공원.jpg":false,
  "assets/dogam_assets/Gyeonggi/구리/경기도_구리시_구리전통시장.jpg":false,
  "assets/dogam_assets/Gyeonggi/구리/경기도_구리시_구리타워.jpg":false,
  "assets/dogam_assets/Gyeonggi/구리/경기도_구리시_구리한강공원.jpg":false,
  "assets/dogam_assets/Gyeonggi/구리/경기도_구리시_동구릉 재실.jpg":false,
  "assets/dogam_assets/Gyeonggi/구리/경기도_구리시_동구하늘공원.jpg":false,
  "assets/dogam_assets/Gyeonggi/구리/경기도_구리시_장자호수공원.jpg":false,
  "assets/dogam_assets/Gyeonggi/구리/경기도_구리시_토평공원.jpg":false,
  "assets/dogam_assets/Gyeonggi/구리/경기도_구리시_호수공원.jpg":false,
};

List <String> url_guri_List=[
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "", 
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
];