Map<String,bool> Imagemap_goesan= {
  "assets/dogam_assets/Chungbuk/괴산/충청북도_괴산군_갈론계곡.jpg":false,
  "assets/dogam_assets/Chungbuk/괴산/충청북도_괴산군_갈은구곡.jpg":false,
  "assets/dogam_assets/Chungbuk/괴산/충청북도_괴산군_괴산 문광저수지 은행나무길.jpg":false,
  "assets/dogam_assets/Chungbuk/괴산/충청북도_괴산군_목도강수욕장.jpg":false,
  "assets/dogam_assets/Chungbuk/괴산/충청북도_괴산군_사담계곡.jpg":false,
  "assets/dogam_assets/Chungbuk/괴산/충청북도_괴산군_성불산자연휴양림.jpg":false,
  "assets/dogam_assets/Chungbuk/괴산/충청북도_괴산군_수옥폭포.jpg":false,
  "assets/dogam_assets/Chungbuk/괴산/충청북도_괴산군_연하협 구름다리.jpg":false,
  "assets/dogam_assets/Chungbuk/괴산/충청북도_괴산군_제월대.jpg":false,
  "assets/dogam_assets/Chungbuk/괴산/충청북도_괴산군_조령산자연휴양림.jpg":false,
  "assets/dogam_assets/Chungbuk/괴산/충청북도_괴산군_초원의집.jpg":false,
  "assets/dogam_assets/Chungbuk/괴산/충청북도_괴산군_하담 김시양 신도비.jpg":false,
  "assets/dogam_assets/Chungbuk/괴산/충청북도_괴산군_화양구곡.jpg":false,
  "assets/dogam_assets/Chungbuk/괴산/충청북도_괴산군_화양동관광농원.jpg":false,
};

List <String> url_goesan_List=[
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
];