List<String> do_dogam_image=[
  'assets/dogam_assets/do_assets/seoul.jpg',
  'assets/dogam_assets/do_assets/gyeonggi.png',
  'assets/dogam_assets/do_assets/busan.jpg',
  'assets/dogam_assets/do_assets/chungbuk.jpg',
  'assets/dogam_assets/do_assets/jeonbuk.jpg',
  'assets/dogam_assets/do_assets/daegu.jpg',
  'assets/dogam_assets/do_assets/gangwon.jpg',
  'assets/dogam_assets/do_assets/daejeon.jpg',
  'assets/dogam_assets/do_assets/sejong.jpg',
  'assets/dogam_assets/do_assets/ulsan.jpg',
  'assets/dogam_assets/do_assets/gyeongbuk.jpg',
  'assets/dogam_assets/do_assets/gyeongnam.jpg',
  'assets/dogam_assets/do_assets/jeju.jpg',
  'assets/dogam_assets/do_assets/incheon.jpg',
  'assets/dogam_assets/do_assets/gwangju.jpg',
  'assets/dogam_assets/do_assets/chungnam.jpg'
];
List<String> do_dogam_text=[
  '서울',
  '경기도',
  '부산',
  '충청북도',
  '전라북도',
  '대구',
  '강원도',
  '대전',
  '세종',
  '울산',
  '경상북도',
  '경상남도',
  '제주',
  '인천',
  '광주',
  '충청남도',
];
List<String> do_dogam_detail=[
  '#야경이 아름다움 #한강',
  '# #',
  '#해수욕장 #제2의 수도권',
  '# #',
  '# #',
  '# #',
  '# #',
  '# #',
  '# #',
  '# #',
  '# #',
  '# #',
  '#흑돼지 #섬나라',
  '# #',
  '# #',
  '# #',
];//여기는 우리가 찾아서 하자
