Map<String,bool> Imagemap_yeongwol = {
  "assets/dogam_assets/Gangwon/영월/강원도_영월군_고씨동굴.jpg":false,
  "assets/dogam_assets/Gangwon/영월/강원도_영월군_김삿갓계곡.jpg":false,
  "assets/dogam_assets/Gangwon/영월/강원도_영월군_내리계곡.jpg":false,
  "assets/dogam_assets/Gangwon/영월/강원도_영월군_단종유배지(청령포).jpg":false,
  "assets/dogam_assets/Gangwon/영월/강원도_영월군_라디오스타 박물관.jpg":false,
  "assets/dogam_assets/Gangwon/영월/강원도_영월군_별마로천문대.jpg":false,
  "assets/dogam_assets/Gangwon/영월/강원도_영월군_서강.jpg":false,
  "assets/dogam_assets/Gangwon/영월/강원도_영월군_엄둔계곡.jpg":false,
  "assets/dogam_assets/Gangwon/영월/강원도_영월군_연하계곡.jpg":false,
  "assets/dogam_assets/Gangwon/영월/강원도_영월군_영월 선돌.jpg":false,
  "assets/dogam_assets/Gangwon/영월/강원도_영월군_영월 한반도 지형.jpg":false,
  "assets/dogam_assets/Gangwon/영월/강원도_영월군_용소폭포.jpg":false,
  "assets/dogam_assets/Gangwon/영월/강원도_영월군_장릉.jpg":false,
  "assets/dogam_assets/Gangwon/영월/강원도_영월군_한반도 뗏목마을.jpg":false,
};


List <String> url_yeongwol_List=[
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
];