Map<String,bool> Imagemap_jeonju = {
  "assets/dogam_assets/Jeonbuk/전주/전라북도_전주시_Visit jeonju.jpg":false,
  "assets/dogam_assets/Jeonbuk/전주/전라북도_전주시_객리단길.jpg":false,
  "assets/dogam_assets/Jeonbuk/전주/전라북도_전주시_경기전.jpg":false,
  "assets/dogam_assets/Jeonbuk/전주/전라북도_전주시_덕진공원.jpg":false,
  "assets/dogam_assets/Jeonbuk/전주/전라북도_전주시_자만벽화마을.jpg":false,
  "assets/dogam_assets/Jeonbuk/전주/전라북도_전주시_전동성당.jpg":false,
  "assets/dogam_assets/Jeonbuk/전주/전라북도_전주시_전주 풍패지관.jpg":false,
  "assets/dogam_assets/Jeonbuk/전주/전라북도_전주시_전주 한옥마을.jpg":false,
  "assets/dogam_assets/Jeonbuk/전주/전라북도_전주시_전주동물원.jpg":false,
  "assets/dogam_assets/Jeonbuk/전주/전라북도_전주시_전주한옥 레일바이크.jpg":false,
  "assets/dogam_assets/Jeonbuk/전주/전라북도_전주시_전주향교.jpg":false,
  "assets/dogam_assets/Jeonbuk/전주/전라북도_전주시_청연루.jpg":false,
  "assets/dogam_assets/Jeonbuk/전주/전라북도_전주시_한국도로공사 전주수목원.jpg":false,
  "assets/dogam_assets/Jeonbuk/전주/전라북도_전주시_호남제일문.jpg":false,
};

List <String> url_jeonju_List=[
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
];