Map<String,bool> Imagemap_yeoncheon = {
  "assets/dogam_assets/Gyeonggi/연천/경기도_연천군_동막리 응회암.jpg":false,
  "assets/dogam_assets/Gyeonggi/연천/경기도_연천군_백의리층.jpg":false,
  "assets/dogam_assets/Gyeonggi/연천/경기도_연천군_역고드름.jpg":false,
  "assets/dogam_assets/Gyeonggi/연천/경기도_연천군_연천 계곡.jpg":false,
  "assets/dogam_assets/Gyeonggi/연천/경기도_연천군_연천 숭의전지.jpg":false,
  "assets/dogam_assets/Gyeonggi/연천/경기도_연천군_연천 코스모스 축제장.jpg":false,
  "assets/dogam_assets/Gyeonggi/연천/경기도_연천군_연천전곡리유적(연천국화축제장).jpg":false,
  "assets/dogam_assets/Gyeonggi/연천/경기도_연천군_열두개울계곡.jpg":false,
  "assets/dogam_assets/Gyeonggi/연천/경기도_연천군_열쇠전망대.jpg":false,
  "assets/dogam_assets/Gyeonggi/연천/경기도_연천군_재인폭포.jpg":false,
  "assets/dogam_assets/Gyeonggi/연천/경기도_연천군_전곡선사박물관.jpg":false,
  "assets/dogam_assets/Gyeonggi/연천/경기도_연천군_초성김치마을.jpg":false,
  "assets/dogam_assets/Gyeonggi/연천/경기도_연천군_한탄강 관광지.jpg":false,
};
List <String> url_yeoncheon_List=[
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "", 
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
];