Map<String,bool> Imagemap_goyang = {
  "assets/dogam_assets/Gyeonggi/고양/경기도_고양시_일산호수공원.jpg":false,
  "assets/dogam_assets/Gyeonggi/고양/경기도_고양시_북한산성.jpg":false,
  "assets/dogam_assets/Gyeonggi/고양/경기도_고양시_행주산성.jpg":false,
  "assets/dogam_assets/Gyeonggi/고양/경기도_고양시_아쿠아플라넷 일산.jpg":false,
  "assets/dogam_assets/Gyeonggi/고양/경기도_고양시_일산문화공원.jpg":false,
  "assets/dogam_assets/Gyeonggi/고양/경기도_고양시_원마운트.jpg":false,
  "assets/dogam_assets/Gyeonggi/고양/경기도_고양시_서삼릉.jpg":false,
  "assets/dogam_assets/Gyeonggi/고양/경기도_고양시_서오릉.jpg":false,
  "assets/dogam_assets/Gyeonggi/고양/경기도_고양시_정발산공원.jpg":false,
  "assets/dogam_assets/Gyeonggi/고양/경기도_고양시_장항습지.jpg":false,
};

List <String> url_goyang_List=[
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "", 
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
];