Map<String,bool> Imagemap_mungyeong = {
  "assets/dogam_assets/gyeongbuk/문경/경상북도_문경시_고모산성.jpg":false,
  "assets/dogam_assets/gyeongbuk/문경/경상북도_문경시_문경단산모노레일.jpg":false,
  "assets/dogam_assets/gyeongbuk/문경/경상북도_문경시_문경새재 도립공원.jpg":false,
  "assets/dogam_assets/gyeongbuk/문경/경상북도_문경시_문경새재 제1관문 주흘관.jpg":false,
  "assets/dogam_assets/gyeongbuk/문경/경상북도_문경시_문경새재 제2관문 조곡관.jpg":false,
  "assets/dogam_assets/gyeongbuk/문경/경상북도_문경시_문경새재오픈세트장.jpg":false,
  "assets/dogam_assets/gyeongbuk/문경/경상북도_문경시_문경오미자테마터널.jpg":false,
  "assets/dogam_assets/gyeongbuk/문경/경상북도_문경시_문경철로자전거 진남역.jpg":false,
  "assets/dogam_assets/gyeongbuk/문경/경상북도_문경시_문경카트월드.jpg":false,
  "assets/dogam_assets/gyeongbuk/문경/경상북도_문경시_문경활공랜드 패러글라이딩.jpg":false,
  "assets/dogam_assets/gyeongbuk/문경/경상북도_문경시_선유동계곡.jpg":false,
  "assets/dogam_assets/gyeongbuk/문경/경상북도_문경시_쌍용계곡.jpg":false,
  "assets/dogam_assets/gyeongbuk/문경/경상북도_문경시_옛길박물관.jpg":false,
  "assets/dogam_assets/gyeongbuk/문경/경상북도_문경시_진남교반.jpg":false,
};

List <String> url_mungyeong_List=[
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
];