Map<String,bool> Imagemap_gwangmyeong = {
  "assets/dogam_assets/Gyeonggi/광명/경기도_광명시_광명동굴.jpg":false,
  "assets/dogam_assets/Gyeonggi/광명/경기도_광명시_도덕산공원.jpg":false,
  "assets/dogam_assets/Gyeonggi/광명/경기도_광명시_충현박물관.jpg":false,
  "assets/dogam_assets/Gyeonggi/광명/경기도_광명시_도덕산.jpg":false,
  "assets/dogam_assets/Gyeonggi/광명/경기도_광명시_현충근린공원.jpg":false,
  "assets/dogam_assets/Gyeonggi/광명/경기도_광명시_뱀쇠다리.jpg":false,
};


List <String> url_gwangmyeong_List=[
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "", 
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
];