Map<String,bool> Imagemap_andong = {
  "assets/dogam_assets/gyeongbuk/안동/경상북도_안동시_만휴정.jpg":false,
  "assets/dogam_assets/gyeongbuk/안동/경상북도_안동시_부용대.jpg":false,
  "assets/dogam_assets/gyeongbuk/안동/경상북도_안동시_신세동 벽화마을.jpg":false,
  "assets/dogam_assets/gyeongbuk/안동/경상북도_안동시_안동 민속촌.jpg":false,
  "assets/dogam_assets/gyeongbuk/안동/경상북도_안동시_안동 임청각(臨淸閣).jpg":false,
  "assets/dogam_assets/gyeongbuk/안동/경상북도_안동시_안동 하회마을.jpg":false,
  "assets/dogam_assets/gyeongbuk/안동/경상북도_안동시_안동문화관광단지.jpg":false,
  "assets/dogam_assets/gyeongbuk/안동/경상북도_안동시_안동이천동석불상.jpg":false,
  "assets/dogam_assets/gyeongbuk/안동/경상북도_안동시_안동전통문화콘텐츠박물관.jpg":false,
  "assets/dogam_assets/gyeongbuk/안동/경상북도_안동시_안동학가산온천.jpg":false,
  "assets/dogam_assets/gyeongbuk/안동/경상북도_안동시_양진당.jpg":false,
  "assets/dogam_assets/gyeongbuk/안동/경상북도_안동시_영호루.jpg":false,
  "assets/dogam_assets/gyeongbuk/안동/경상북도_안동시_월영정(月映亭).jpg":false,
  "assets/dogam_assets/gyeongbuk/안동/경상북도_안동시_유교랜드.jpg":false,
};

List <String> url_andong_List=[
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
];