Map<String,bool> Imagemap_yaecheon= {
  "assets/dogam_assets/gyeongbuk/예천/경상북도_예천군_병암정.jpg":false,
  "assets/dogam_assets/gyeongbuk/예천/경상북도_예천군_선몽대.jpg":false,
  "assets/dogam_assets/gyeongbuk/예천/경상북도_예천군_신라식물원.jpg":false,
  "assets/dogam_assets/gyeongbuk/예천/경상북도_예천군_예천 금당실마을.jpg":false,
  "assets/dogam_assets/gyeongbuk/예천/경상북도_예천군_예천 삼강주막.jpg":false,
  "assets/dogam_assets/gyeongbuk/예천/경상북도_예천군_예천 용문사 대장전.jpg":false,
  "assets/dogam_assets/gyeongbuk/예천/경상북도_예천군_예천 천향리 석송령.jpg":false,
  "assets/dogam_assets/gyeongbuk/예천/경상북도_예천군_예천 초간정(草澗亭).jpg":false,
  "assets/dogam_assets/gyeongbuk/예천/경상북도_예천군_예천곤충생태체험관.jpg":false,
  "assets/dogam_assets/gyeongbuk/예천/경상북도_예천군_예천권씨 초간종택.jpg":false,
  "assets/dogam_assets/gyeongbuk/예천/경상북도_예천군_예천박물관.jpg":false,
  "assets/dogam_assets/gyeongbuk/예천/경상북도_예천군_예천온천.jpg":false,
  "assets/dogam_assets/gyeongbuk/예천/경상북도_예천군_용문사.jpg":false,
  "assets/dogam_assets/gyeongbuk/예천/경상북도_예천군_회룡포전망대.jpg":false,
};

List <String> url_yaecheon_List=[
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
];