Map<String,bool> Imagemap_yeosu = {
  "assets/dogam_assets/Jeonnam/여수/전라남도_여수시_여수해양레일바이크.jpg":false,
  "assets/dogam_assets/Jeonnam/여수/전라남도_여수시_여수해양공원.jpg":false,
  "assets/dogam_assets/Jeonnam/여수/전라남도_여수시_천사벽화마을.jpg":false,
  "assets/dogam_assets/Jeonnam/여수/전라남도_여수시_돌산공원.jpg":false,
  "assets/dogam_assets/Jeonnam/여수/전라남도_여수시_여수해상케이블카 돌산탑승장.jpg":false,
  "assets/dogam_assets/Jeonnam/여수/전라남도_여수시_이순신광장.jpg":false,
  "assets/dogam_assets/Jeonnam/여수/전라남도_여수시_장도.jpg":false,
  "assets/dogam_assets/Jeonnam/여수/전라남도_여수시_여수 자산공원.jpg":false,
  "assets/dogam_assets/Jeonnam/여수/전라남도_여수시_여수예술랜드.jpg":false,
  "assets/dogam_assets/Jeonnam/여수/전라남도_여수시_돌산도.jpg":false,
  "assets/dogam_assets/Jeonnam/여수/전라남도_여수시_이순신공원.jpg":false,
};
List <String> url_yeosu_List=[
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
];