Map<String,bool> Imagemap_haenam = {
  "assets/dogam_assets/Jeonnam/해남/전라남도_해남군_가마도.jpg":false,
  "assets/dogam_assets/Jeonnam/해남/전라남도_해남군_고산 윤선도 생가.jpg":false,
  "assets/dogam_assets/Jeonnam/해남/전라남도_해남군_금쇄동기.jpg":false,
  "assets/dogam_assets/Jeonnam/해남/전라남도_해남군_노승봉.jpg":false,
  "assets/dogam_assets/Jeonnam/해남/전라남도_해남군_달마산.jpg":false,
  "assets/dogam_assets/Jeonnam/해남/전라남도_해남군_대흥사.jpg":false,
  "assets/dogam_assets/Jeonnam/해남/전라남도_해남군_도솔봉약수터.jpg":false,
  "assets/dogam_assets/Jeonnam/해남/전라남도_해남군_두륜산대흥사계곡.jpg":false,
  "assets/dogam_assets/Jeonnam/해남/전라남도_해남군_땅끝모노레일.jpg":false,
  "assets/dogam_assets/Jeonnam/해남/전라남도_해남군_미황사.jpg":false,
  "assets/dogam_assets/Jeonnam/해남/전라남도_해남군_땅끝전망대.jpg":false,
  "assets/dogam_assets/Jeonnam/해남/전라남도_해남군_우항리공룡화석지.jpg":false,
  "assets/dogam_assets/Jeonnam/해남/전라남도_해남군_해남 전라우수영.jpg":false,
  "assets/dogam_assets/Jeonnam/해남/전라남도_해남군_해남공룡박물관.jpg":false,
};
List <String> url_haenam_List=[
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
];