Map<String,bool> Imagemap_gwangju2 = {
  "assets/dogam_assets/Gyeonggi/광주/경기도_광주시_화담숲.jpg":false,
  "assets/dogam_assets/Gyeonggi/광주/경기도_광주시_남한산성 전승문.jpg":false,
  "assets/dogam_assets/Gyeonggi/광주/경기도_광주시_율봄식물원.jpg":false,
  "assets/dogam_assets/Gyeonggi/광주/경기도_광주시_남한산성행궁.jpg":false,
  "assets/dogam_assets/Gyeonggi/광주/경기도_광주시_중대물빛공원.jpg":false,
  "assets/dogam_assets/Gyeonggi/광주/경기도_광주시_남한산성 지화문.jpg":false,
  "assets/dogam_assets/Gyeonggi/광주/경기도_광주시_남한산성 동문.jpg":false,
};

List <String> url_gwangju2_List=[
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "", 
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
];