Map<String,bool> Imagemap_yangsan = {
  "assets/dogam_assets/gyeongnam/양산/경상남도_양산시_가야진사공원.jpg":false,
  "assets/dogam_assets/gyeongnam/양산/경상남도_양산시_내원사계곡.jpg":false,
  "assets/dogam_assets/gyeongnam/양산/경상남도_양산시_배내골.jpg":false,
  "assets/dogam_assets/gyeongnam/양산/경상남도_양산시_순매원전망대.jpg":false,
  "assets/dogam_assets/gyeongnam/양산/경상남도_양산시_양산 디자인 공원.jpg":false,
  "assets/dogam_assets/gyeongnam/양산/경상남도_양산시_양산시립박물관.jpg":false,
  "assets/dogam_assets/gyeongnam/양산/경상남도_양산시_양산워터파크.jpg":false,
  "assets/dogam_assets/gyeongnam/양산/경상남도_양산시_양산타워.jpg":false,
  "assets/dogam_assets/gyeongnam/양산/경상남도_양산시_오봉산.jpg":false,
  "assets/dogam_assets/gyeongnam/양산/경상남도_양산시_임경대.jpg":false,
  "assets/dogam_assets/gyeongnam/양산/경상남도_양산시_전성산1봉 원효봉.jpg":false,
  "assets/dogam_assets/gyeongnam/양산/경상남도_양산시_통도사.jpg":false,
  "assets/dogam_assets/gyeongnam/양산/경상남도_양산시_홍룡사(虹龍寺).jpg":false,
  "assets/dogam_assets/gyeongnam/양산/경상남도_양산시_홍룡폭포(虹龍瀑布).jpg":false,
};
List <String> url_yangsan_List=[
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
];