Map<String,bool> Imagemap_yangsan = {
  "assets/dogam_assets/gyeongnam/양산/경상남도_양산시_양산타워.jpg":false,
  "assets/dogam_assets/gyeongnam/양산/경상남도_양산시_오봉산.jpg":false,
  "assets/dogam_assets/gyeongnam/양산/경상남도_양산시_배내골.jpg":false,
  "assets/dogam_assets/gyeongnam/양산/경상남도_양산시_임경대.jpg":false,
  "assets/dogam_assets/gyeongnam/양산/경상남도_양산시_양산워터파크.jpg":false,
  "assets/dogam_assets/gyeongnam/양산/경상남도_양산시_양산시립박물관.jpg":false,
  "assets/dogam_assets/gyeongnam/양산/경상남도_양산시_통도사.jpg":false,
};

List <String> url_yangsan_List=[
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
];