Map<String,bool> Imagemap_gimpo = {
  "assets/dogam_assets/Gyeonggi/김포/경기도_김포시_걸포중앙공원.jpg":false,
  "assets/dogam_assets/Gyeonggi/김포/경기도_김포시_김포 덕포진 교육 박물관.jpg":false,
  "assets/dogam_assets/Gyeonggi/김포/경기도_김포시_김포국제조각공원.jpg":false,
  "assets/dogam_assets/Gyeonggi/김포/경기도_김포시_김포레코파크.jpg":false,
  "assets/dogam_assets/Gyeonggi/김포/경기도_김포시_김포에코센터.jpg":false,
  "assets/dogam_assets/Gyeonggi/김포/경기도_김포시_김포함상공원.jpg":false,
  "assets/dogam_assets/Gyeonggi/김포/경기도_김포시_당산미.jpg":false,
  "assets/dogam_assets/Gyeonggi/김포/경기도_김포시_모담산 정상.jpg":false,
  "assets/dogam_assets/Gyeonggi/김포/경기도_김포시_문수산산림욕장.jpgg":false,
  "assets/dogam_assets/Gyeonggi/김포/경기도_김포시_애기봉.jpg":false,
  "assets/dogam_assets/Gyeonggi/김포/경기도_김포시_염하강철책길 입구.jpg":false,
  "assets/dogam_assets/Gyeonggi/김포/경기도_김포시_장릉.jpg":false,
  "assets/dogam_assets/Gyeonggi/김포/경기도_김포시_죽도.jpg":false,
  "assets/dogam_assets/Gyeonggi/김포/경기도_김포시_한강신도시 호수공원.jpg":false,
};

List <String> url_gimpo_List=[
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "", 
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
];