Map<String,bool> Imagemap_cheongju = {
  "assets/dogam_assets/Chungbuk/Cheongju/suamgol.jpg":false,
  "assets/dogam_assets/Chungbuk/Cheongju/cheongju_museum.jpg":false,
  "assets/dogam_assets/Chungbuk/Cheongju/sangdang3.jpg":false,
  "assets/dogam_assets/Chungbuk/Cheongju/cheongju_zoo.jpg":false,
  "assets/dogam_assets/Chungbuk/Cheongju/cheongju_yonghwasa.jpg":false,
  "assets/dogam_assets/Chungbuk/Cheongju/cheongjuland.jpg":false,
  "assets/dogam_assets/Chungbuk/Cheongju/cheongju_garosu.jpg":false,
  "assets/dogam_assets/Chungbuk/Cheongju/cheongju_sungangil.jpg":false,
  "assets/dogam_assets/Chungbuk/Cheongju/cheongju_goinswae.jpg":false,
  "assets/dogam_assets/Chungbuk/Cheongju/cheongju_jungangpark.jpg":false,
  "assets/dogam_assets/Chungbuk/Cheongju/cheongju_cheongnamdae.jpg":false,
  "assets/dogam_assets/Chungbuk/Cheongju/cheongju_jungbukdong.jpg":false,
  "assets/dogam_assets/Chungbuk/Cheongju/cheongju_myeongam.jpg":false,
  "assets/dogam_assets/Chungbuk/Cheongju/cheongju_samilpark.jpg":false,
};
Map<String,String> Imagemap_cheongju_title ={
  "수암골":"#벽화마을#전망대",
  "국립청주박물관":"#문화유산#국보",
  "상당산성":"#백제#둘레길",
  "청주동물원":"#청주랜드#동물원",
  "용화사":"#사찰#템플스테이",
  "청주랜드":"#어린이#놀이공원",
  "청주가로수길":"#가로수길#숲터널",
  "성안길":"#시내#상권중심",
  "청주고인쇄박물관":"#박물관#금속활자",
  "청주중앙공원":"#역사공원#망선루",
  "청남대":"#대통령별장#드라이브",
  "정북동 토성":"#인생사진#성곽",
  "명암유원지":"#유원지#저수지",
  "삼일공원":"#3.1운동#독립공원",
};
