Map<String,bool> Imagemap_hongcheon = {
  "assets/dogam_assets/Gangwon/홍천/강원도_홍천군_개야리유원지.jpg":false,
  "assets/dogam_assets/Gangwon/홍천/강원도_홍천군_대한불교조계종 수타사.jpg":false,
  "assets/dogam_assets/Gangwon/홍천/강원도_홍천군_남노일강변.jpg":false,
  "assets/dogam_assets/Gangwon/홍천/강원도_홍천군_마곡유원지.jpg":false,
  "assets/dogam_assets/Gangwon/홍천/강원도_홍천군_살둔계곡.jpg":false,
  "assets/dogam_assets/Gangwon/홍천/강원도_홍천군_서봉사계곡.jpg":false,
  "assets/dogam_assets/Gangwon/홍천/강원도_홍천군_수타사계곡.jpg":false,
  "assets/dogam_assets/Gangwon/홍천/강원도_홍천군_알파카월드.jpg":false,
  "assets/dogam_assets/Gangwon/홍천/강원도_홍천군_오션월드.jpg":false,
  "assets/dogam_assets/Gangwon/홍천/강원도_홍천군_용소계곡.jpg":false,
  "assets/dogam_assets/Gangwon/홍천/강원도_홍천군_테마파크.jpg":false,
  "assets/dogam_assets/Gangwon/홍천/강원도_홍천군_팔봉산 관광지.jpg":false,
  "assets/dogam_assets/Gangwon/홍천/강원도_홍천군_홍천 은행나무숲.jpg":false,
  "assets/dogam_assets/Gangwon/홍천/강원도_홍천군_홍천생명건강과학관.jpg":false,
};


List <String> url_hongcheon_List=[
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
];