Map<String,bool> Imagemap_pyeongtaek = {
  "assets/dogam_assets/Gyeonggi/평택/경기도_평택시_만기사.jpg":false,
  "assets/dogam_assets/Gyeonggi/평택/경기도_평택시_바람새마을.jpg":false,
  "assets/dogam_assets/Gyeonggi/평택/경기도_평택시_소풍정원.jpg":false,
  "assets/dogam_assets/Gyeonggi/평택/경기도_평택시_웃다리문화촌.jpg":false,
  "assets/dogam_assets/Gyeonggi/평택/경기도_평택시_이충레포츠공원.jpg":false,
  "assets/dogam_assets/Gyeonggi/평택/경기도_평택시_진위향교.jpg":false,
  "assets/dogam_assets/Gyeonggi/평택/경기도_평택시_팽성읍 객사.jpg":false,
  "assets/dogam_assets/Gyeonggi/평택/경기도_평택시_평택 센트럴돔 캐니언 파크.jpg":false,
  "assets/dogam_assets/Gyeonggi/평택/경기도_평택시_평택국제중앙시장.jpg":false,
  "assets/dogam_assets/Gyeonggi/평택/경기도_평택시_평택벚꽃길.jpg":false,
  "assets/dogam_assets/Gyeonggi/평택/경기도_평택시_평택시자연테마식물원.jpg":false,
  "assets/dogam_assets/Gyeonggi/평택/경기도_평택시_평택호관광지.jpg":false,
  "assets/dogam_assets/Gyeonggi/평택/경기도_평택시_평택호예술공원.jpg":false,
};

List <String> url_pyeongtaek_List=[
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "", 
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
];