Map<String,bool> Imagemap_damyang = {
  "assets/dogam_assets/Jeonnam/담양/전라남도_담양군_달빛 무월마을.jpg":false,
  "assets/dogam_assets/Jeonnam/담양/전라남도_담양군_담양 관방제림.jpg":false,
  "assets/dogam_assets/Jeonnam/담양/전라남도_담양군_담양 용마루길.jpg":false,
  "assets/dogam_assets/Jeonnam/담양/전라남도_담양군_담양호국민관광단지.jpg":false,
  "assets/dogam_assets/Jeonnam/담양/전라남도_담양군_메타세쿼이아가로수길.jpg":false,
  "assets/dogam_assets/Jeonnam/담양/전라남도_담양군_메타프로방스.jpg":false,
  "assets/dogam_assets/Jeonnam/담양/전라남도_담양군_면앙정.jpg":false,
  "assets/dogam_assets/Jeonnam/담양/전라남도_담양군_명옥헌 원림.jpg":false,
  "assets/dogam_assets/Jeonnam/담양/전라남도_담양군_명옥헌.jpg":false,
  "assets/dogam_assets/Jeonnam/담양/전라남도_담양군_삼지내마을.jpg":false,
  "assets/dogam_assets/Jeonnam/담양/전라남도_담양군_소쇄원 (瀟灑園).jpg":false,
  "assets/dogam_assets/Jeonnam/담양/전라남도_담양군_제월당 (霽月堂).jpg":false,
  "assets/dogam_assets/Jeonnam/담양/전라남도_담양군_죽녹원.jpg":false
};
List <String> url_damyang_List=[
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
];