Map<String,bool> Imagemap_gyeryong = {
  "assets/dogam_assets/chungnam/계룡/충청남도_계룡시_계룡문 雞龍門.jpg":false,
  "assets/dogam_assets/chungnam/계룡/충청남도_계룡시_계룡산 녹색농촌 체험마을 승마체험장.jpg":false,
  "assets/dogam_assets/chungnam/계룡/충청남도_계룡시_계룡산국립공원 동학사지구.jpg":false,
  "assets/dogam_assets/chungnam/계룡/충청남도_계룡시_계룡산에스케이.jpg":false,
  "assets/dogam_assets/chungnam/계룡/충청남도_계룡시_괴목정공원.jpg":false,
  "assets/dogam_assets/chungnam/계룡/충청남도_계룡시_두계천교.jpg":false,
  "assets/dogam_assets/chungnam/계룡/충청남도_계룡시_두마신원재.jpg":false,
  "assets/dogam_assets/chungnam/계룡/충청남도_계룡시_롯데관광.jpg":false,
  "assets/dogam_assets/chungnam/계룡/충청남도_계룡시_무궁화학습원.jpg":false,
  "assets/dogam_assets/chungnam/계룡/충청남도_계룡시_수락계곡.jpg":false,
  "assets/dogam_assets/chungnam/계룡/충청남도_계룡시_숭산 국제선원 무상사.jpg":false,
  "assets/dogam_assets/chungnam/계룡/충청남도_계룡시_신도안문화공원.jpg":false,
  "assets/dogam_assets/chungnam/계룡/충청남도_계룡시_이심원충신정려현판.jpg":false,
  "assets/dogam_assets/chungnam/계룡/충청남도_계룡시_향적산 사방댐 정자.jpg":false,
};

List <String> url_gyeryong_List=[
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
];