Map<String,bool> Imagemap_cheonan = {
  "assets/dogam_assets/chungnam/천안/충청남도_천안시_각원사.jpg":false,
  "assets/dogam_assets/chungnam/천안/충청남도_천안시_독립기념관.jpg":false,
  "assets/dogam_assets/chungnam/천안/충청남도_천안시_미나릿길 벽화마을.jpg":false,
  "assets/dogam_assets/chungnam/천안/충청남도_천안시_불당천.jpg":false,
  "assets/dogam_assets/chungnam/천안/충청남도_천안시_아라리오갤러리 천안.jpg":false,
  "assets/dogam_assets/chungnam/천안/충청남도_천안시_아름다운정원 화수목.jpg":false,
  "assets/dogam_assets/chungnam/천안/충청남도_천안시_용주정.jpg":false,
  "assets/dogam_assets/chungnam/천안/충청남도_천안시_유관순열사유적지.jpg":false,
  "assets/dogam_assets/chungnam/천안/충청남도_천안시_우정박물관.jpg":false,
  "assets/dogam_assets/chungnam/천안/충청남도_천안시_천안 영남루.jpg":false,
  "assets/dogam_assets/chungnam/천안/충청남도_천안시_천안박물관.jpg":false,
  "assets/dogam_assets/chungnam/천안/충청남도_천안시_천안삼거리공원.jpg":false,
  "assets/dogam_assets/chungnam/천안/충청남도_천안시_천호지.jpg":false,
  "assets/dogam_assets/chungnam/천안/충청남도_천안시_태조산공원.jpg":false,
};

List <String> url_cheonan_List=[
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
];