Map<String,bool> Imagemap_boryeong = {
  "assets/dogam_assets/chungnam/보령/충청남도_보령시_개화예술공원.jpg":false,
  "assets/dogam_assets/chungnam/보령/충청남도_보령시_국립오서산자연휴양림.jpg":false,
  "assets/dogam_assets/chungnam/보령/충청남도_보령시_군헌갯벌체험학습장.jpg":false,
  "assets/dogam_assets/chungnam/보령/충청남도_보령시_다보도.jpg":false,
  "assets/dogam_assets/chungnam/보령/충청남도_보령시_대천해수욕장 스카이바이크.jp":false,
  "assets/dogam_assets/chungnam/보령/충청남도_보령시_대천해수욕장.jpg":false,
  "assets/dogam_assets/chungnam/보령/충청남도_보령시_무창포갯벌.jpg":false,
  "assets/dogam_assets/chungnam/보령/충청남도_보령시_보령 머드 박물관.jpg":false,
  "assets/dogam_assets/chungnam/보령/충청남도_보령시_보령냉풍욕장.jpg":false,
  "assets/dogam_assets/chungnam/보령/충청남도_보령시_빙도.jpg":false,
  "assets/dogam_assets/chungnam/보령/충청남도_보령시_상화원(尙和園).jpg":false,
  "assets/dogam_assets/chungnam/보령/충청남도_보령시_성주계곡.jpg":false,
  "assets/dogam_assets/chungnam/보령/충청남도_보령시_성주산자연휴양림.jpg":false,
  "assets/dogam_assets/chungnam/보령/충청남도_보령시_월도.jpg":false,
};

List <String> url_boryeongList=[
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
];