Map<String,bool> Imagemap_pyeongchang = {
  "assets/dogam_assets/Gangwon/평창/강원도_평창군_금당계곡.jpg":false,
  "assets/dogam_assets/Gangwon/평창/강원도_평창군_대관령 하늘목장.jpg":false,
  "assets/dogam_assets/Gangwon/평창/강원도_평창군_대관령양떼목장.jpg":false,
  "assets/dogam_assets/Gangwon/평창/강원도_평창군_메밀꽃.jpg":false,
  "assets/dogam_assets/Gangwon/평창/강원도_평창군_봉평 메밀꽃밭.jpg":false,
  "assets/dogam_assets/Gangwon/평창/강원도_평창군_상원사(上院寺).jpg":false,
  "assets/dogam_assets/Gangwon/평창/강원도_평창군_오대산국립공원.jpg":false,
  "assets/dogam_assets/Gangwon/평창/강원도_평창군_원당계곡.jpg":false,
  "assets/dogam_assets/Gangwon/평창/강원도_평창군_육백마지기.jpg":false,
  "assets/dogam_assets/Gangwon/평창/강원도_평창군_이효석 문화마을.jpg":false,
  "assets/dogam_assets/Gangwon/평창/강원도_평창군_이효석문학관.jpg":false,
  "assets/dogam_assets/Gangwon/평창/강원도_평창군_허브나라농원.jpg":false,
  "assets/dogam_assets/Gangwon/평창/강원도_평창군_효석달빛언덕.jpg":false,
  "assets/dogam_assets/Gangwon/평창/강원도_평창군_흥정계곡.jpg":false,
};

List <String> url_pyeongchang_List=[
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
];