Map<String,bool> Imagemap_bonghwa = {
  "assets/dogam_assets/gyeongbuk/봉화/경상북도_봉화군_구마계곡,소천계곡.jpg":false,
  "assets/dogam_assets/gyeongbuk/봉화/경상북도_봉화군_국립백두대간수목원.jpg":false,
  "assets/dogam_assets/gyeongbuk/봉화/경상북도_봉화군_김생굴.jpg":false,
  "assets/dogam_assets/gyeongbuk/봉화/경상북도_봉화군_다덕약수관광지.jpg":false,
  "assets/dogam_assets/gyeongbuk/봉화/경상북도_봉화군_닭실(달실)마을.jpg":false,
  "assets/dogam_assets/gyeongbuk/봉화/경상북도_봉화군_백천계곡.jpg":false,
  "assets/dogam_assets/gyeongbuk/봉화/경상북도_봉화군_봉화선유교.jpg":false,
  "assets/dogam_assets/gyeongbuk/봉화/경상북도_봉화군_봉화전통문화마을.jpg":false,
  "assets/dogam_assets/gyeongbuk/봉화/경상북도_봉화군_분천 산타마을.jpg":false,
  "assets/dogam_assets/gyeongbuk/봉화/경상북도_봉화군_오전약수탕.jpg":false,
  "assets/dogam_assets/gyeongbuk/봉화/경상북도_봉화군_청량산도립공원.jpg":false,
  "assets/dogam_assets/gyeongbuk/봉화/경상북도_봉화군_청량폭포.jpg":false,
  "assets/dogam_assets/gyeongbuk/봉화/경상북도_봉화군_청암정(靑巖亭).jpg":false,
  "assets/dogam_assets/gyeongbuk/봉화/경상북도_봉화군_축서사.jpg":false,
};

List <String> url_bonghwa_List=[
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
];