Map<String,bool> Imagemap_jinju = {
  "assets/dogam_assets/gyeongnam/진주/경상남도_진주시_경상남도수목원.jpg":false,
  "assets/dogam_assets/gyeongnam/진주/경상남도_진주시_남가람공원.jpg":false,
  "assets/dogam_assets/gyeongnam/진주/경상남도_진주시_망진산봉수대.jpg":false,
  "assets/dogam_assets/gyeongnam/진주/경상남도_진주시_석류공원.jpg":false,
  "assets/dogam_assets/gyeongnam/진주/경상남도_진주시_의곡사.jpg":false,
  "assets/dogam_assets/gyeongnam/진주/경상남도_진주시_진주 의암.jpg":false,
  "assets/dogam_assets/gyeongnam/진주/경상남도_진주시_진주레일바이크 남강레저산업.jpg":false,
  "assets/dogam_assets/gyeongnam/진주/경상남도_진주시_진주매화숲.jpg":false,
  "assets/dogam_assets/gyeongnam/진주/경상남도_진주시_진주성 비석군.jpg":false,
  "assets/dogam_assets/gyeongnam/진주/경상남도_진주시_진주성.jpg":false,
  "assets/dogam_assets/gyeongnam/진주/경상남도_진주시_진주시음악분수대.jpg":false,
  "assets/dogam_assets/gyeongnam/진주/경상남도_진주시_진치령터널.jpg":false,
  "assets/dogam_assets/gyeongnam/진주/경상남도_진주시_촉석루.jpg":false,
  "assets/dogam_assets/gyeongnam/진주/경상남도_진주시_호국사.jpg":false,
};
List <String> url_jinju_List=[
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
];