Map<String,bool> Imagemap_goryeong = {
  "assets/dogam_assets/gyeongbuk/고령/경상북도_고령군_개경포 기념공원.jpg":false,
  "assets/dogam_assets/gyeongbuk/고령/경상북도_고령군_고령 고아리 벽화 고분.jpg":false,
  "assets/dogam_assets/gyeongbuk/고령/경상북도_고령군_고령 부례관광지.jpg":false,
  "assets/dogam_assets/gyeongbuk/고령/경상북도_고령군_고령 은행나무숲.jpg":false,
  "assets/dogam_assets/gyeongbuk/고령/경상북도_고령군_고령 주산성.jpg":false,
  "assets/dogam_assets/gyeongbuk/고령/경상북도_고령군_대가야 수목원.jpg":false,
  "assets/dogam_assets/gyeongbuk/고령/경상북도_고령군_대가야박물관.jpg":false,
  "assets/dogam_assets/gyeongbuk/고령/경상북도_고령군_대가야역사테마관광지.jpg":false,
  "assets/dogam_assets/gyeongbuk/고령/경상북도_고령군_대가야왕릉전시관.jpg":false,
  "assets/dogam_assets/gyeongbuk/고령/경상북도_고령군_대가야체험축제장.jpg":false,
  "assets/dogam_assets/gyeongbuk/고령/경상북도_고령군_봉이땅엔농장.jpg":false,
  "assets/dogam_assets/gyeongbuk/고령/경상북도_고령군_예마을.jpg":false,
  "assets/dogam_assets/gyeongbuk/고령/경상북도_고령군_우륵박물관.jpg":false,
  "assets/dogam_assets/gyeongbuk/고령/경상북도_고령군_지산동고분군.jpg":false,
};

List <String> url_goryeong_List=[
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
];