Map<String,bool> Imagemap_guchang = {
  "assets/dogam_assets/gyeongnam/거창/경상남도_거창군_거열산성군립공원.jpg":false,
  "assets/dogam_assets/gyeongnam/거창/경상남도_거창군_거창 Y자형출렁다리.jpg":false,
  "assets/dogam_assets/gyeongnam/거창/경상남도_거창군_거창 거열성.jpg":false,
  "assets/dogam_assets/gyeongnam/거창/경상남도_거창군_거창 요수정.jpg":false,
  "assets/dogam_assets/gyeongnam/거창/경상남도_거창군_거창박물관.jpg":false,
  "assets/dogam_assets/gyeongnam/거창/경상남도_거창군_거창사건추모공원.jpg":false,
  "assets/dogam_assets/gyeongnam/거창/경상남도_거창군_금원산생태수목원.jpg":false,
  "assets/dogam_assets/gyeongnam/거창/경상남도_거창군_금원산자연휴양림.jpg":false,
  "assets/dogam_assets/gyeongnam/거창/경상남도_거창군_백두산천지온천.jpg":false,
  "assets/dogam_assets/gyeongnam/거창/경상남도_거창군_연수사.jpg":false,
  "assets/dogam_assets/gyeongnam/거창/경상남도_거창군_용원정.jpg":false,
  "assets/dogam_assets/gyeongnam/거창/경상남도_거창군_창포원.jpg":false,
  "assets/dogam_assets/gyeongnam/거창/경상남도_거창군_황산전통한옥마을.jpg":false
};

List <String> url_guchang_List=[
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
];