Map<String,bool> Imagemap_gyeongju = {
  "assets/dogam_assets/gyeongbuk/경주/경상북도_경주시_경주 동궁원.jpg":false,
  "assets/dogam_assets/gyeongbuk/경주/경상북도_경주시_경주 양남주상절리.jpg":false,
  "assets/dogam_assets/gyeongbuk/경주/경상북도_경주시_경주 월정교.jpg":false,
  "assets/dogam_assets/gyeongbuk/경주/경상북도_경주시_경주교촌마을.jpg":false,
  "assets/dogam_assets/gyeongbuk/경주/경상북도_경주시_경주버드파크.jpg":false,
  "assets/dogam_assets/gyeongbuk/경주/경상북도_경주시_경주보문관광단지.jpg":false,
  "assets/dogam_assets/gyeongbuk/경주/경상북도_경주시_경주월드.jpg":false,
  "assets/dogam_assets/gyeongbuk/경주/경상북도_경주시_경주타워.jpg":false,
  "assets/dogam_assets/gyeongbuk/경주/경상북도_경주시_금장대.jpg":false,
  "assets/dogam_assets/gyeongbuk/경주/경상북도_경주시_동궁과 월지.jpg":false,
  "assets/dogam_assets/gyeongbuk/경주/경상북도_경주시_보문정 (普門亭).jpg":false,
  "assets/dogam_assets/gyeongbuk/경주/경상북도_경주시_석굴암.jpg":false,
  "assets/dogam_assets/gyeongbuk/경주/경상북도_경주시_첨성대.jpg":false,
  "assets/dogam_assets/gyeongbuk/경주/경상북도_경주시_황리단길.jpg":false,
};
List <String> url_gyeongju_List=[
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
];