Map<String,bool> Imagemap_hongseong = {
  "assets/dogam_assets/chungnam/홍성/충청남도_홍성군_국화동산.jpg":false,
  "assets/dogam_assets/chungnam/홍성/충청남도_홍성군_궁리항.jpg":false,
  "assets/dogam_assets/chungnam/홍성/충청남도_홍성군_김좌진 장군 생가지.jpg":false,
  "assets/dogam_assets/chungnam/홍성/충청남도_홍성군_노은단.jpg":false,
  "assets/dogam_assets/chungnam/홍성/충청남도_홍성군_속동갯벌마을.jpg":false,
  "assets/dogam_assets/chungnam/홍성/충청남도_홍성군_속동전망대.jpg":false,
  "assets/dogam_assets/chungnam/홍성/충청남도_홍성군_안회당과여하정.jpg":false,
  "assets/dogam_assets/chungnam/홍성/충청남도_홍성군_용봉사.jpg":false,
  "assets/dogam_assets/chungnam/홍성/충청남도_홍성군_용봉산 자연휴양림.jpg":false,
  "assets/dogam_assets/chungnam/홍성/충청남도_홍성군_조양문.jpg":false,
  "assets/dogam_assets/chungnam/홍성/충청남도_홍성군_한용운 선생 생가지.jpg":false,
  "assets/dogam_assets/chungnam/홍성/충청남도_홍성군_홍성 홍주의사총.jpg":false,
  "assets/dogam_assets/chungnam/홍성/충청남도_홍성군_홍성조류탐사과학관.jpg":false,
  "assets/dogam_assets/chungnam/홍성/충청남도_홍성군_홍주읍성.jpg":false,
};

List <String> url_hongseong_List=[
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
];