Map<String,bool> Imagemap_jincheon = {
  "assets/dogam_assets/Chungbuk/진천/충청북도_진천군_만뢰산자연생태공원.jpg":false,
  "assets/dogam_assets/Chungbuk/진천/충청북도_진천군_백곡천 공영주차장.jpg":false,
  "assets/dogam_assets/Chungbuk/진천/충청북도_진천군_보탑사.jpg":false,
  "assets/dogam_assets/Chungbuk/진천/충청북도_진천군_생거진천자연휴양림.jpg":false,
  "assets/dogam_assets/Chungbuk/진천/충청북도_진천군_연곡계곡.jpg":false,
  "assets/dogam_assets/Chungbuk/진천/충청북도_진천군_영수사.jpg":false,
  "assets/dogam_assets/Chungbuk/진천/충청북도_진천군_인공폭포(진천).jpg":false,
  "assets/dogam_assets/Chungbuk/진천/충청북도_진천군_진천 길상사.jpg":false,
  "assets/dogam_assets/Chungbuk/진천/충청북도_진천군_진천 이팝나무길.jpg":false,
  "assets/dogam_assets/Chungbuk/진천/충청북도_진천군_진천농교.jpg":false,
  "assets/dogam_assets/Chungbuk/진천/충청북도_진천군_진천역사테마공원.jpg":false,
  "assets/dogam_assets/Chungbuk/진천/충청북도_진천군_진천종박물관.jpg":false,
  "assets/dogam_assets/Chungbuk/진천/충청북도_진천군_천년정(진천).jpg":false,
  "assets/dogam_assets/Chungbuk/진천/충청북도_진천군_화랑공원.jpg":false,
};

List <String> url_jincheon_List=[
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
];