Map<String,bool> Imagemap_pocheon = {
  "assets/dogam_assets/Gyeonggi/포천/경기도_포천시_광릉추모공원.jpg":false,
  "assets/dogam_assets/Gyeonggi/포천/경기도_포천시_국립수목원.jpg":false,
  "assets/dogam_assets/Gyeonggi/포천/경기도_포천시_깊이울유원지.jpg":false,
  "assets/dogam_assets/Gyeonggi/포천/경기도_포천시_백운계곡.jpg":false,
  "assets/dogam_assets/Gyeonggi/포천/경기도_포천시_비둘기낭 폭포.jpg":false,
  "assets/dogam_assets/Gyeonggi/포천/경기도_포천시_산사원.jpg":false,
  "assets/dogam_assets/Gyeonggi/포천/경기도_포천시_산정호수.jpg":false,
  "assets/dogam_assets/Gyeonggi/포천/경기도_포천시_서운동산.jpg":false,
  "assets/dogam_assets/Gyeonggi/포천/경기도_포천시_수목원프로방스.jpg":false,
  "assets/dogam_assets/Gyeonggi/포천/경기도_포천시_포천 한탄강 하늘다리.jpg":false,
  "assets/dogam_assets/Gyeonggi/포천/경기도_포천시_포천 허브아일랜드.jpg":false,
  "assets/dogam_assets/Gyeonggi/포천/경기도_포천시_포천아트밸리.jpg":false,
  "assets/dogam_assets/Gyeonggi/포천/경기도_포천시_포천한탄강 벼룻길.jpg":false,
  "assets/dogam_assets/Gyeonggi/포천/경기도_포천시_화적연.jpg":false,
};
List <String> url_pocheon_List=[
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "", 
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
];