Map<String,bool> Imagemap_cheolwon = {
  "assets/dogam_assets/Gangwon/철원/강원도_철원군_고석정.jpg":false,
  "assets/dogam_assets/Gangwon/철원/강원도_철원군_고석정랜드.jpg":false,
  "assets/dogam_assets/Gangwon/철원/강원도_철원군_매월대폭포.jpg":false,
  "assets/dogam_assets/Gangwon/철원/강원도_철원군_삼부연폭포.jpg":false,
  "assets/dogam_assets/Gangwon/철원/강원도_철원군_송대소.jpg":false,
  "assets/dogam_assets/Gangwon/철원/강원도_철원군_순담계곡.jpg":false,
  "assets/dogam_assets/Gangwon/철원/강원도_철원군_월정리역(月井里驛).jpg":false,
  "assets/dogam_assets/Gangwon/철원/강원도_철원군_직탕폭포.jpg":false,
  "assets/dogam_assets/Gangwon/철원/강원도_철원군_철원 제2땅굴.jpg":false,
  "assets/dogam_assets/Gangwon/철원/강원도_철원군_철원 평화전망대.jpg":false,
  "assets/dogam_assets/Gangwon/철원/강원도_철원군_철원 한탄강 주상절리길 드르니 매표소.jpg":false,
  "assets/dogam_assets/Gangwon/철원/강원도_철원군_철원 한탄강 주상절리길 순담 매표소.jpg":false,
  "assets/dogam_assets/Gangwon/철원/강원도_철원군_철원 한탄강 주상절리길.jpg":false,
  "assets/dogam_assets/Gangwon/철원/강원도_철원군_한탄강 잔도(棧道) 주상절리길.jpg":false,
};

List <String> url_cheolwon_List=[
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
];