Map<String,bool> Imagemap_geumsan = {
  "assets/dogam_assets/chungnam/금산/충청남도_금산군_12폭포.jpg":false,
  "assets/dogam_assets/chungnam/금산/충청남도_금산군_개삼터 테마공원.jpg":false,
  "assets/dogam_assets/chungnam/금산/충청남도_금산군_금강솔바람길.jpg":false,
  "assets/dogam_assets/chungnam/금산/충청남도_금산군_금산 요광리 은행나무.jpg":false,
  "assets/dogam_assets/chungnam/금산/충청남도_금산군_금산 월영산 출렁다리.jpg":false,
  "assets/dogam_assets/chungnam/금산/충청남도_금산군_금산다락원 생명의집.jpg":false,
  "assets/dogam_assets/chungnam/금산/충청남도_금산군_금산산림문화타운.jpg":false,
  "assets/dogam_assets/chungnam/금산/충청남도_금산군_금산역사공원.jpg":false,
  "assets/dogam_assets/chungnam/금산/충청남도_금산군_원골유원지.jpg":false,
  "assets/dogam_assets/chungnam/금산/충청남도_금산군_적벽강.jpg":false,
  "assets/dogam_assets/chungnam/금산/충청남도_금산군_천태산 신안사.jpg":false,
  "assets/dogam_assets/chungnam/금산/충청남도_금산군_청강수계곡.jpg":false,
  "assets/dogam_assets/chungnam/금산/충청남도_금산군_칠백의총.jpg":false,
  "assets/dogam_assets/chungnam/금산/충청남도_금산군_하늘물빛정원.jpg":false,
};

List <String> url_geumsan_List=[
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
];