Map<String,bool> Imagemap_yeongyang = {
  "assets/dogam_assets/gyeongbuk/영양/경상북도_영양군_검마산자연휴양림.jpg":false,
  "assets/dogam_assets/gyeongbuk/영양/경상북도_영양군_남자현지사 생가지.jpg":false,
  "assets/dogam_assets/gyeongbuk/영양/경상북도_영양군_두들마을.jpg":false,
  "assets/dogam_assets/gyeongbuk/영양/경상북도_영양군_두들마을유물전시관.jpg":false,
  "assets/dogam_assets/gyeongbuk/영양/경상북도_영양군_만곡정사.jpg":false,
  "assets/dogam_assets/gyeongbuk/영양/경상북도_영양군_반딧불이생태학교.jpg":false,
  "assets/dogam_assets/gyeongbuk/영양/경상북도_영양군_삼의계곡.jpg":false,
  "assets/dogam_assets/gyeongbuk/영양/경상북도_영양군_선바위관광지.jpg":false,
  "assets/dogam_assets/gyeongbuk/영양/경상북도_영양군_수하계곡.jpg":false,
  "assets/dogam_assets/gyeongbuk/영양/경상북도_영양군_영양군 음식디미방 전통주 체험관.jpg":false,
  "assets/dogam_assets/gyeongbuk/영양/경상북도_영양군_영양반딧불이생태공원.jpg":false,
  "assets/dogam_assets/gyeongbuk/영양/경상북도_영양군_오무마을.jpg":false,
  "assets/dogam_assets/gyeongbuk/영양/경상북도_영양군_졸참나무와 당숲.jpg":false,
  };
List <String> url_yeongyang_List=[
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
];