Map<String,bool> Imagemap_injae = {
  "assets/dogam_assets/Gangwon/인제/강원도_인제군_내린천계곡.jpg":false,
  "assets/dogam_assets/Gangwon/인제/강원도_인제군_대승폭포.jpg":false,
  "assets/dogam_assets/Gangwon/인제/강원도_인제군_매바위인공폭포.jpg":false,
  "assets/dogam_assets/Gangwon/인제/강원도_인제군_방동약수터.jpg":false,
  "assets/dogam_assets/Gangwon/인제/강원도_인제군_백담사(百潭寺).jpg":false,
  "assets/dogam_assets/Gangwon/인제/강원도_인제군_비밀의 정원.jpg":false,
  "assets/dogam_assets/Gangwon/인제/강원도_인제군_십이선녀탕계곡.jpg":false,
  "assets/dogam_assets/Gangwon/인제/강원도_인제군_아침가리계곡.jpg":false,
  "assets/dogam_assets/Gangwon/인제/강원도_인제군_원대리 자작나무 숲.jpgg":false,
  "assets/dogam_assets/Gangwon/인제/강원도_인제군_인제문화관광.jpg":false,
  "assets/dogam_assets/Gangwon/인제/강원도_인제군_인제산촌민속박물관.jpgg":false,
  "assets/dogam_assets/Gangwon/인제/강원도_인제군_추대계곡.jpg":false,
  "assets/dogam_assets/Gangwon/인제/강원도_인제군_합강정.jpg":false,
};

List <String> url_injae_List=[
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
];