Map<String,bool> Imagemap_sacheon = {
  "assets/dogam_assets/gyeongnam/사천/경상남도_사천시_노산공원.jpg":false,
  "assets/dogam_assets/gyeongnam/사천/경상남도_사천시_백천사.jpg":false,
  "assets/dogam_assets/gyeongnam/사천/경상남도_사천시_부잔교 갯벌탐방로.jpg":false,
  "assets/dogam_assets/gyeongnam/사천/경상남도_사천시_비토섬.jpg":false,
  "assets/dogam_assets/gyeongnam/사천/경상남도_사천시_사천 각산봉화대.jpg":false,
  "assets/dogam_assets/gyeongnam/사천/경상남도_사천시_사천 무지개 해안도로.jpg":false,
  "assets/dogam_assets/gyeongnam/사천/경상남도_사천시_사천 선진리왜성.jpg":false,
  "assets/dogam_assets/gyeongnam/사천/경상남도_사천시_사천거북선마을.jpg":false,
  "assets/dogam_assets/gyeongnam/사천/경상남도_사천시_선진공원.jpg":false,
  "assets/dogam_assets/gyeongnam/사천/경상남도_사천시_수양공원.jpg":false,
  "assets/dogam_assets/gyeongnam/사천/경상남도_사천시_실안낙조.jpg":false,
  "assets/dogam_assets/gyeongnam/사천/경상남도_사천시_용소유원지.jpg":false,
  "assets/dogam_assets/gyeongnam/사천/경상남도_사천시_우천숲.jpg":false,
  "assets/dogam_assets/gyeongnam/사천/경상남도_사천시_창선·삼천포대교.jpg":false,
};
List <String> url_sacheon_List=[
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
];