Map<String,bool> Imagemap_hwaseong = {
  "assets/dogam_assets/Gyeonggi/화성/경기도_화성시_경기도 수원화성.jpg":false,
  "assets/dogam_assets/Gyeonggi/화성/경기도_화성시_궁평리해수욕장.jpg":false,
  "assets/dogam_assets/Gyeonggi/화성/경기도_화성시_궁평유원지.jpg":false,
  "assets/dogam_assets/Gyeonggi/화성/경기도_화성시_당성.jpg":false,
  "assets/dogam_assets/Gyeonggi/화성/경기도_화성시_만의사.jpg":false,
  "assets/dogam_assets/Gyeonggi/화성/경기도_화성시_매바위.jpg":false,
  "assets/dogam_assets/Gyeonggi/화성/경기도_화성시_백미항.jpg":false,
  "assets/dogam_assets/Gyeonggi/화성/경기도_화성시_서봉산산림욕장.jpg":false,
  "assets/dogam_assets/Gyeonggi/화성/경기도_화성시_우리꽃식물원.jpg":false,
  "assets/dogam_assets/Gyeonggi/화성/경기도_화성시_원평허브농원.jpg":false,
  "assets/dogam_assets/Gyeonggi/화성/경기도_화성시_제부도 바닷길.jpg":false,
  "assets/dogam_assets/Gyeonggi/화성/경기도_화성시_천주교 남양 성모 성지.jpg":false,
  "assets/dogam_assets/Gyeonggi/화성/경기도_화성시_행복텃밭.jpg":false,
  "assets/dogam_assets/Gyeonggi/화성/경기도_화성시_화성시 비봉습지공원.jpg":false,
};


List <String> url_hwaseong_List=[
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "", 
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
];