Map<String,bool> Imagemap_donghae = {
  "assets/dogam_assets/Gangwon/동해/강원도_동해시_감추사.jpg":false,
  "assets/dogam_assets/Gangwon/동해/강원도_동해시_까막바위.jpg":false,
  "assets/dogam_assets/Gangwon/동해/강원도_동해시_대한불교조계종 삼화사(三和寺).jpg":false,
  "assets/dogam_assets/Gangwon/동해/강원도_동해시_도째비골 스카이밸리.jpg":false,
  "assets/dogam_assets/Gangwon/동해/강원도_동해시_동해 논골담길.jpg":false,
  "assets/dogam_assets/Gangwon/동해/강원도_동해시_무릉계곡.jpg":false,
  "assets/dogam_assets/Gangwon/동해/강원도_동해시_무릉별유천지.jpg":false,
  "assets/dogam_assets/Gangwon/동해/강원도_동해시_바람의 언덕.jpg":false,
  "assets/dogam_assets/Gangwon/동해/강원도_동해시_천곡황금박쥐동굴.jpg":false,
  "assets/dogam_assets/Gangwon/동해/강원도_동해시_촛대바위.jpg":false,
  "assets/dogam_assets/Gangwon/동해/강원도_동해시_추암.jpg":false,
  "assets/dogam_assets/Gangwon/동해/강원도_동해시_추암해변.jpg":false,
  "assets/dogam_assets/Gangwon/동해/동해/강원도_동해시_추암해수욕장.jpg":false,
  "assets/dogam_assets/Gangwon/동해/강원도_동해시_한섬해변.jpg":false,
};
List <String> url_donghae_List=[
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
];