Map<String,bool> Imagemap_gimcheon = {
  "assets/dogam_assets/gyeongbuk/김천/경상북도_김천시_강변조각공원.jpg":false,
  "assets/dogam_assets/gyeongbuk/김천/경상북도_김천시_김천녹색미래과학관.jpg":false,
  "assets/dogam_assets/gyeongbuk/김천/경상북도_김천시_김천세계도자기박물관.jpg":false,
  "assets/dogam_assets/gyeongbuk/김천/경상북도_김천시_김호중 소리길.jpg":false,
  "assets/dogam_assets/gyeongbuk/김천/경상북도_김천시_부항댐 출렁다리.jpg":false,
  "assets/dogam_assets/gyeongbuk/김천/경상북도_김천시_불영산 청암사(佛靈山 靑巖寺).jpg":false,
  "assets/dogam_assets/gyeongbuk/김천/경상북도_김천시_사명대사공원.jpg":false,
  "assets/dogam_assets/gyeongbuk/김천/경상북도_김천시_수도산 자연휴양림.jpg":false,
  "assets/dogam_assets/gyeongbuk/김천/경상북도_김천시_수도암.jpg":false,
  "assets/dogam_assets/gyeongbuk/김천/경상북도_김천시_연화지.jpg":false,
  "assets/dogam_assets/gyeongbuk/김천/경상북도_김천시_영남제일문.jpg":false,
  "assets/dogam_assets/gyeongbuk/김천/경상북도_김천시_용추폭포.jpg":false,
  "assets/dogam_assets/gyeongbuk/김천/경상북도_김천시_인현왕후길.jpg":false,
  "assets/dogam_assets/gyeongbuk/김천/경상북도_김천시_직지문화공원.jpg":false,
};

List <String> url_gimcheon_List=[
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
];