Map<String,bool> Imagemap_eumseong = {
  "assets/dogam_assets/Chungbuk/음성/충청북도_음성군_가섭산.jpg":false,
  "assets/dogam_assets/Chungbuk/음성/충청북도_음성군_감우재전승기념관.jpg":false,
  "assets/dogam_assets/Chungbuk/음성/충청북도_음성군_반기문생가.jpg":false,
  "assets/dogam_assets/Chungbuk/음성/충청북도_음성군_반기문평화랜드.jpg":false,
  "assets/dogam_assets/Chungbuk/음성/충청북도_음성군_봉학골산림욕장.jpg":false,
  "assets/dogam_assets/Chungbuk/음성/충청북도_음성군_성산천.jpg":false,
  "assets/dogam_assets/Chungbuk/음성/충청북도_음성군_음성 미타사 마애여래입상.jpg":false,
  "assets/dogam_assets/Chungbuk/음성/충청북도_음성군_수레의산자연휴양림.jpg":false,
  "assets/dogam_assets/Chungbuk/음성/충청북도_음성군_음성큰바위얼굴조각공원.jpg":false,
  "assets/dogam_assets/Chungbuk/음성/충청북도_음성군_응천공원.jpg":false,
  "assets/dogam_assets/Chungbuk/음성/충청북도_음성군_천주교 감곡매괴 성모순례지 성당":false,
  "assets/dogam_assets/Chungbuk/음성/충청북도_음성군_철박물관.jpg":false,
  "assets/dogam_assets/Chungbuk/음성/충청북도_음성군_한독의약박물관.jpg":false,
  "assets/dogam_assets/Chungbuk/음성/충청북도_음성군_음성동요학교.jpg":false,
};

List <String> url_eumseong_List=[
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
];