Map<String,bool> Imagemap_icheon = {
  "assets/dogam_assets/Gyeonggi/이천/경기도_이천시_길상요.jpg":false,
  "assets/dogam_assets/Gyeonggi/이천/경기도_이천시_덕평공룡수목원.jpg":false,
  "assets/dogam_assets/Gyeonggi/이천/경기도_이천시_별빛정원 우주.jpg":false,
  "assets/dogam_assets/Gyeonggi/이천/경기도_이천시_부학봉.jpg":false,
  "assets/dogam_assets/Gyeonggi/이천/경기도_이천시_삼형제바위.jpg":false,
  "assets/dogam_assets/Gyeonggi/이천/경기도_이천시_설봉공원.jpg":false,
  "assets/dogam_assets/Gyeonggi/이천/경기도_이천시_이천 설봉산성.jpg":false,
  "assets/dogam_assets/Gyeonggi/이천/경기도_이천시_이천 신대리 백송.jpg":false,
  "assets/dogam_assets/Gyeonggi/이천/경기도_이천시_이천도예촌.jpg":false,
  "assets/dogam_assets/Gyeonggi/이천/경기도_이천시_이천도자기마을.jpg":false,
  "assets/dogam_assets/Gyeonggi/이천/경기도_이천시_이천산수유마을.jpg":false,
  "assets/dogam_assets/Gyeonggi/이천/경기도_이천시_이천시립박물관.jpg":false,
  "assets/dogam_assets/Gyeonggi/이천/경기도_이천시_이천시립월전미술관.jpg":false,
  "assets/dogam_assets/Gyeonggi/이천/경기도_이천시_이천온천공원.jpg":false,
};

List <String> url_icheon_List=[
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "", 
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
];