Map<String,bool> Imagemap_yesan= {
  "assets/dogam_assets/chungnam/예산/충청남도_예산군_덕산도립공원.jpg":false,
  "assets/dogam_assets/chungnam/예산/충청남도_예산군_덕산온천 관광지.jpg":false,
  "assets/dogam_assets/chungnam/예산/충청남도_예산군_봉수산자연휴양림.jpg":false,
  "assets/dogam_assets/chungnam/예산/충청남도_예산군_수덕사.jpg":false,
  "assets/dogam_assets/chungnam/예산/충청남도_예산군_예당 출렁다리.jpg":false,
  "assets/dogam_assets/chungnam/예산/충청남도_예산군_예당관광지.jpg":false,
  "assets/dogam_assets/chungnam/예산/충청남도_예산군_예당국민관광지.jpg":false,
  "assets/dogam_assets/chungnam/예산/충청남도_예산군_예당호 조각공원.jpg":false,
  "assets/dogam_assets/chungnam/예산/충청남도_예산군_예당호수.jpg":false,
  "assets/dogam_assets/chungnam/예산/충청남도_예산군_이남규선생고택.jpg":false,
  "assets/dogam_assets/chungnam/예산/충청남도_예산군_임존성.jpg":false,
  "assets/dogam_assets/chungnam/예산/충청남도_예산군_충의사.jpg":false,
  "assets/dogam_assets/chungnam/예산/충청남도_예산군_충효정.jpg":false,
  "assets/dogam_assets/chungnam/예산/충청남도_예산군_향천사.jpg":false,
};
List <String> url_yesan_List=[
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
];