Map<String,bool> Imagemap_sunchang = {
  "assets/dogam_assets/Jeonbuk/순창/전라북도_순창군_강천사.jpg":false,
  "assets/dogam_assets/Jeonbuk/순창/전라북도_순창군_강천산군립공원.jpg":false,
  "assets/dogam_assets/Jeonbuk/순창/전라북도_순창군_강천산군립공원매표소.jpg":false,
  "assets/dogam_assets/Jeonbuk/순창/전라북도_순창군_구장군 폭포.jpg":false,
  "assets/dogam_assets/Jeonbuk/순창/전라북도_순창군_순창 발효소스토굴.jpg":false,
  "assets/dogam_assets/Jeonbuk/순창/전라북도_순창군_순창고추장민속마을.jpg":false,
  "assets/dogam_assets/Jeonbuk/순창/전라북도_순창군_순창고추장익는 마을.jpg":false,
  "assets/dogam_assets/Jeonbuk/순창/전라북도_순창군_순창장류박물관.jpg":false,
  "assets/dogam_assets/Jeonbuk/순창/전라북도_순창군_용궐산 하늘길.jpg":false,
  "assets/dogam_assets/Jeonbuk/순창/전라북도_순창군_채계산 출렁다리.jpg":false,
  "assets/dogam_assets/Jeonbuk/순창/전라북도_순창군_추령장승촌.jpg":false,
  "assets/dogam_assets/Jeonbuk/순창/전라북도_순창군_팔각정.jpg":false,
  "assets/dogam_assets/Jeonbuk/순창/전라북도_순창군_향가유원지.jpg":false,
  "assets/dogam_assets/Jeonbuk/순창/전라북도_순창군_회문산자연휴양림.jpg":false,
};
List <String> url_sunchang_List=[
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
];