Map<String,bool> Imagemap_osan = {
  "assets/dogam_assets/Gyeonggi/오산/경기도_오산시_고인돌공원.jpg":false,
  "assets/dogam_assets/Gyeonggi/오산/경기도_오산시_궐리사.jpg":false,
  "assets/dogam_assets/Gyeonggi/오산/경기도_오산시_남촌동 벽화마을.jpg":false,
  "assets/dogam_assets/Gyeonggi/오산/경기도_오산시_독산성.jpg":false,
  "assets/dogam_assets/Gyeonggi/오산/경기도_오산시_물향기수목원.jpg":false,
  "assets/dogam_assets/Gyeonggi/오산/경기도_오산시_보적사.jpg":false,
  "assets/dogam_assets/Gyeonggi/오산/경기도_오산시_세마대.jpg":false,
  "assets/dogam_assets/Gyeonggi/오산/경기도_오산시_오산 미니어처 빌리지.jpg":false,
  "assets/dogam_assets/Gyeonggi/오산/경기도_오산시_오산 에코리움.jpg":false,
  "assets/dogam_assets/Gyeonggi/오산/경기도_오산시_오산 죽미령 평화공원.jpg":false,
  "assets/dogam_assets/Gyeonggi/오산/경기도_오산시_오산맑음터공원.jpg":false,
  "assets/dogam_assets/Gyeonggi/오산/경기도_오산시_오산버드파크.jpg":false,
  "assets/dogam_assets/Gyeonggi/오산/경기도_오산시_유엔군 초전기념관.jpg":false,
  "assets/dogam_assets/Gyeonggi/오산/경기도_오산시_죽미체육공원.jpg":false,
};

List <String> url_osan_List=[
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "", 
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
];