Map<String,bool> Imagemap_osan = {
  "assets/dogam_assets/Gyeonggi/오산/경기도_오산시_궐리사.jpg":false,
  "assets/dogam_assets/Gyeonggi/오산/경기도_오산시_독산성.jpg":false,
  "assets/dogam_assets/Gyeonggi/오산/경기도_오산시_고인돌공원.jpg":false,
  "assets/dogam_assets/Gyeonggi/오산/경기도_오산시_세마대.jpg":false,
  "assets/dogam_assets/Gyeonggi/오산/경기도_오산시_죽미체육공원.jpg":false,
  "assets/dogam_assets/Gyeonggi/오산/경기도_오산시_유엔군 초전기념관.jpg":false,
};

List <String> url_osan_List=[
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "", 
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
];